[[raspberry-pi-4-bootloader-configuration]]
== Raspberry Pi 4 启动加载程序配置

[[editing-the-configuration]]
=== 编辑配置


在编辑引导加载程序配置之前，请 xref:os.adoc#updating-and-upgrading-raspberry-pi-os[更新系统] 以获取最新版本的 `rpi-eeprom` 软件包。

查看当前的EEPROM配置: +
`rpi-eeprom-config`

对其进行编辑并将更新应用到最新的EEPROM版本，请执行以下操作: +
`sudo -E rpi-eeprom-config --edit`

有关 EEPROM 更新过程的详细信息，请参阅 xref:raspberry-pi.adoc#raspberry-pi-4-boot-eeprom[启动 EEPROM] 界面。

[[configuration-properties]]
=== 配置属性

本节介绍引导加载程序中可用的所有配置项。语法与 xref:config_txt.adoc[config.txt] 相同，但属性是特定于启动加载程序。除 EDID 外，还支持xref:config_txt.adoc#conditional-filters[条件筛选器] 。

[[BOOT_UART]]
==== BOOT_UART

如果设置为 `1`，则在GPIO14和GPIO15上启用 UART 调试输出，将接收调试终端配置为 115200bps、8 位、无奇偶校验位、1 个停止位。

默认值: `0`

[[WAKE_ON_GPIO]]
==== WAKE_ON_GPIO

如果设置为 `1`， 则 `sudo halt` 将在低功耗模式下运行，直到GPIO3或GLOBAL_EN接地短路。

默认值: `1`

[[POWER_OFF_ON_HALT]]
==== POWER_OFF_ON_HALT

如果设置为 `1` 且 `WAKE_ON_GPIO=0` ，则 `sudo halt` 将关闭所有PMIC输出。这是halt可能的最低功耗状态，但可能会给一些HAT带来问题，因为5V电压仍然存在。`GLOBAL_EN` 必须接地短路才能启动。

Raspberry Pi 400 具有一个专用的电源按钮，即使处理器关闭也能运行。默认启用此设置，但可以将`WAKE_ON_GPIO=2`设置为使用外部GPIO电源按钮，而非专用电源按钮。

默认值: `0`

[[BOOT_ORDER]]
==== BOOT_ORDER

该`BOOT_ORDER` 设置允许配置不同启动模式的优先级。它表示为 32 位无符号整数，其中每个半字节表示一个启动模式。按照最低有效半字节到最高有效半字节顺序尝试启动模式。


[discrete]
====== `BOOT_ORDER` 领域

BOOT_ORDER 定义不同启动模式的顺序，从右到左读取，最多可以定义 8 位数字。

|===
| 取值 | 模式 | 描述

| 0x0
| SD CARD DETECT
| 尝试 SD，然后等待卡检测指示卡已更改 - 现在已弃用，因为0xf（重新启动）可用。

| 0x1
| SD CARD
| SD 卡（或CM4上的eMMC）。

| 0x2
| NETWORK
| 网络启动 - 参见 xref:remote-access.adoc#network-boot-your-raspberry-pi[网络启动服务教程]

| 0x3
| RPIBOOT
| RPIBOOT - 参见 https://github.com/raspberrypi/usbboot[usbboot]

| 0x4
| USB-MSD
| USB 大容量存储启动 - 参见 xref:raspberry-pi.adoc#usb-mass-storage-boot[USB大容量存储启动]

| 0x5
| BCM-USB-MSD
| USB 2.0从USB-C端口启动（CM4：CM4IO 板上的 USB-A接口）。

| 0x6
| NVME
| 仅限 CM4：从连接到PCIe接口的NVMe固态硬盘启动。有关更多详细信息，参见 xref:raspberry-pi.adoc#nvme-ssd-boot[NVMe boot] 。

| 0x7
| HTTP
| 通过以太网进行 HTTP 引导。 有关更多详细信息，参见 xref:raspberry-pi.adoc#http-boot[HTTP boot] 。

| 0xe
| STOP
| 停止并显示错误模式。需要重启电源才能退出此状态。

| 0xf
| RESTART
| 从BOOT_ORDER字段中的第一个引导模式重新启动，即循环。
|===

`RPIBOOT` 旨在与CM4 一起使用来加载自定义调试镜像（例如 Linux RAM 磁盘）而非正常启动后。这是最后一个启动选项，因为它当前不支持超时或重试。

[discrete]
====== `BOOT_ORDER` 示例

|===
| BOOT_ORDER | 描述

| 0xf41
| 首先尝试 SD，然后尝试 USB-MSD，然后重复（如果BOOT_ORDER为空，则默认）。

| 0xf14
| 首先尝试 USB，然后尝试 SD，再重复。

| 0xf21
| 首先尝试 SD，然后尝试网络，再重复。
|===

[[MAX_RESTARTS]]
==== MAX_RESTARTS

如果遇到 RESTART (`0xf`) 启动模式的次数超过 MAX_RESTARTS 次，则会触发看门狗复位。不建议将其用于常规用途，但对于需要完全重置以解决硬件或网络接口问题的测试或远程系统可能很有用。

默认值: `-1` (无限)

[[SD_BOOT_MAX_RETRIES]]
==== SD_BOOT_MAX_RETRIES

SD启动失败后在转到 `BOOT_ORDER`定义的下一个启动模式之前重试的次数。 +
`-1` 意味着无限次重试。

默认值: `0`

[[NET_BOOT_MAX_RETRIES]]
==== NET_BOOT_MAX_RETRIES

网络启动失败后在转到 `BOOT_ORDER`定义的下一个启动模式之前重试的次数。 +
`-1` 意味着无限次重试。 +

默认值: `0`

[[DHCP_TIMEOUT]]
==== DHCP_TIMEOUT

当前迭代失败之前整个 DHCP 序列的超时时间（以ms为单位）。

最小值: `5000` +
默认值: `45000`

[[DHCP_REQ_TIMEOUT]]
==== DHCP_REQ_TIMEOUT

重试 DHCP 发现或 DHCP REQ 之前的超时时间（以ms为单位）。

最小值: `500` +
默认值: `4000`

[[TFTP_FILE_TIMEOUT]]
==== TFTP_FILE_TIMEOUT

通过 TFTP 下载单个文件的超时时间（以ms为单位）。

最小值: `5000` +
默认值: `30000`

[[TFTP_IP]]
==== TFTP_IP

TFTP 服务器的可选点分十进制 IP地址（例如192.168.1.99），用于覆盖DHCP请求的服务器IP。 +
这个在家庭网络上很有用，因为可以使用tftpd-hpa代替dnsmasq，其中宽带路由器是DHCP服务器。

默认值: ""

[[TFTP_PREFIX]]
==== TFTP_PREFIX

为了支持每个Raspberry Pi的唯一 TFTP 启动目录，启动加载程序会在文件名前面加上设备特定的目录。如果在前缀目录中找不到 start4.elf 和 start.elf，则清除前缀。
在早期型号上，序列号用作前缀，但在Raspberry Pi 4上，MAC地址不再从序列号生成，因此很难通过检查DHCPDISCOVER数据包在服务器上自动创建tftpboot目录。为了支持此功能，可以将TFTP_PREFIX自定义为 MAC 地址、固定值或序列号（默认）。

|===
| 取值 | 描述

| 0
| 使用序列号，例如 `9ffefdef/`

| 1
| 使用由 TFTP_PREFIX_STR 指定的字符串

| 2
| 使用 MAC 地址，例如 `dc-a6-32-01-36-c2/`
|===

默认值: 0

[[TFTP_PREFIX_STR]]
==== TFTP_PREFIX_STR

指定当 `TFTP_PREFIX` 设置为1时使用的自定义目录前缀字符串。例如:- `TFTP_PREFIX_STR=tftp_test/`

默认值: "" +
最大长度: 32个字符

[[PXE_OPTION43]]
==== PXE_OPTION43

使用不同的字符串覆盖 PXE Option43 匹配字符串。通常，将自定义应用于 DHCP 服务器比更改客户端行为更好，但如果无法做到这一点，则会提供此选项。

默认值: `Raspberry Pi Boot`

[[DHCP_OPTION97]]
==== DHCP_OPTION97

在早期版本中，客户端GUID(选项97)只是重复4次的序列号。默认情况下，新的GUID格式是 `RPi4` 的fourcc(0x 34695052-little endian)、板版本(例如0x00c03111) (4字节)、mac地址的4个最低有效字节和4字节序列号的串联。这是唯一的，但也为DHCP服务器提供结构化信息，允许Raspberry Pi 4计算机在不依赖以太网MAC OUID的情况下被识别。

指定 DHCP_OPTION97=0 以回复设置，或指定非零十六进制值以指定自定义 4 字节前缀。

默认值: `0x34695052`

[[MAC_ADDRESS]]
==== MAC_ADDRESS

用给定的值覆盖Raspberry Pi以太网 MAC 地址。例如 `dc:a6:32:01:36:c2`

默认值: ""

[[MAC_ADDRESS_OTP]]
==== MAC_ADDRESS_OTP
使用存储在 xref:raspberry-pi.adoc#write-and-read-customer-otp-values[Customer OTP] 寄存器中的值覆盖Raspberry Pi以太网 MAC 地址。

例如，要使用存储在 `Customer OTP` 的第0行 和第1行中的MAC地址。
----
MAC_ADDRESS_OTP=0,1
----

第一个值（示例中的第 0 行）包含 OUI 和 MAC 地址中最重要的 8 位。第二个值（示例中的第 1 行）存储 MAC 地址的剩余 16 位。 这与用于制造时编程的Raspberry Pi MAC地址的格式相同。

可以选择任意两个客户OTP行，并按任一顺序组合。
`Customer OTP` 行是 `vcgencmd otp_dump` 输出中的OTP寄存器36至43，因此，如果前两行编程如下，则 `MAC_ADDRESS_OTP=0,1` ，将给出 `e4:5f:01:20:24:7e` 的MAC地址。

----
36:247e0000
37:e45f0120
----

默认值: ""

[[static-ip-address-configuration]]
==== 静态IP地址配置

如果设置了TFTP_IP和以下选项，则跳过 DHCP 并应用静态 IP 配置。如果 TFTP 服务器与客户端位于同一子网上，则可以省略网关。

[[CLIENT_IP]]
===== CLIENT_IP

客户端的IP地址，例如 `192.168.0.32`

默认值: ""

[[SUBNET]]
===== SUBNET

子网掩码地址，例如 `255.255.255.0`

默认值: ""

[[GATEWAY]]
===== GATEWAY

如果 TFTP 服务器位于不同的子网上，则要使用的网关地址，例如 `192.168.0.1`

默认值: ""

[[DISABLE_HDMI]]
==== DISABLE_HDMI

如果 `DISABLE_HDMI=1` ，则禁用 xref:raspberry-pi.adoc#boot-diagnostics-on-the-raspberry-pi-4[HDMI 启动诊断] 显示。 其他非零值保留供将来使用。

默认值: `0`

[[HDMI_DELAY]]
==== HDMI_DELAY

除非发生致命错误，否则最多可跳过HDMI诊断显示的渲染长达 N 秒（默认为 5）。默认行为旨在避免在正常的SD / USB启动期间短暂出现启动加载程序诊断屏幕。

默认值: `5`

[[ENABLE_SELF_UPDATE]]
==== ENABLE_SELF_UPDATE

使启动加载程序能够从 TFTP 或 USB 大容量存储设备 （MSD） 启动文件系统更新自身。

如果启用了自更新，则启动加载程序将在启动文件系统中查找更新文件 （.sig/.upd）。如果更新镜像与当前镜像不同，则应更新并重置系统。否则，如果EEPROM镜像逐字节相同，则启动将继续正常进行。

注意:-

* SD启动中未启用自更新；ROM已经可以从SD卡加载recovery.bin。。
* 2021年之前的启动加载程序版本不支持 `自更新`.
* 对于网络启动，确保TFTP `boot` 目录可以通过NFS挂载，并且 `rpi-eeprom-update` 可以写入其中。

默认值: `1`

[[FREEZE_VERSION]]
==== FREEZE_VERSION

以前该属性仅由 `rpi-eeprom-update` 脚本检查，现在自更新被启用，启动加载程序也将检查这个属性。 如果设置为1，将覆盖 `ENABLE_SELF_UPDATE` 以停止自更新。 如果要禁用 `FREEZE_VERSION` 必须使用带recovery.bin的SD卡启动。

*自定义EEPROM更新脚本也必须检查该标志。*

默认值: `0`

[[HTTP_HOST]]
==== HTTP_HOST

如果启动了网络安装或HTTP，则会从该服务器下载 `boot.img` 和 `boot.sig` 。

无效的主机名将被忽略。应该只包含小写字母、数字字符和 `-` 或 `.` 。 如果设置了 `HTTP_HOST` ，则禁用HTTPS，而使用普通HTTP。您可以指定一个IP地址，以避免需要DNS查找。主机名中不要包含HTTP方案或/。

默认值: `fw-download-alias1.raspberrypi.com`

[[HTTP_PORT]]
==== HTTP_PORT

您可以使用此属性来更改用于网络安装和HTTP启动的端口。使用默认主机 `fw-download-alias1.raspberrypi.com` 时，启用HTTPS。如果更改了 `HTTP_HOST` ，则会禁用HTTPS，而使用普通HTTP。

禁用HTTPS时，即使 `HTTP_PORT`更改为 `443` ，仍将使用普通HTTP。

默认值：如果启用了HTTPS，默认值为 `443` ，否则为 `80` 。

[[HTTP_PATH]]
==== HTTP_PATH

用于网络安装和HTTP引导的路径。

这条道路的情况 *是* 很重要。
使用正斜杠(Linux)作为路径分隔符。
不需要前导和尾随正斜杠。

如果未设置 `HTTP_HOST` , 则忽略 `HTTP_PATH` , URL将为 `\https://fw-download-alias1.raspberrypi.com:443/net_install/boot.img` 。 如果设置了 `HTTP_HOST` 值， URL 将为 `\http://<HTTP_HOST>:<HTTP_PORT>/<HTTP_PATH>/boot.img`

默认值: `net_install`

[[IMAGER_REPO_URL]]
==== IMAGER_REPO_URL

嵌入式Raspberry Pi成像仪应用程序配置有启动时下载的json文件。

您可以更改嵌入式Raspberry Pi Imager应用程序使用的json文件的URL，让它提供您自己的图像。
您可以使用标准的 https://www.raspberrypi.com/software/[Raspberry Pi Imager] 应用程序通过 `--repo` 参数传递URL来测试这一点。

默认值: `\http://downloads.raspberrypi.org/os_list_imagingutility_v3.json`

[[NET_INSTALL_ENABLED]]
==== NET_INSTALL_ENABLED

启用网络安装时，如果引导程序检测到键盘，它会在引导时显示网络安装屏幕。

要启用网络安装，请添加 `NET_INSTALL_ENABLED=1`, 要禁用网络安装，请添加 `NET_INSTALL_ENABLED=0`。

如果设置了 `DISABLE_HDMI=1` ，此设置将被忽略，网络安装将被禁用。.

为了检测键盘，网络安装必须初始化USB控制器并枚举设备。这增加了大约1秒的启动时间，因此在某些嵌入式应用中禁用网络安装可能是有利的。

默认值: 在Raspberry Pi 4和Raspberry Pi 400上为 `1` ，在计算模块4上为 `0` 。

[[NET_INSTALL_KEYBOARD_WAIT]]
==== NET_INSTALL_KEYBOARD_WAIT

如果启用了网络安装，引导程序会尝试检测键盘和 `SHIFT` 键来启动网络安装。您可以使用此属性更改等待时间(以毫秒为单位)。 

将此项设置为 `0` 将禁用键盘等待，尽管如果没有找到引导文件并且USB引导模式 `4` 处于`BOOT_ORDER` 状态，仍然可以启动网络安装。

NOTE: 测试表明键盘和 SHIFT 检测至少需要 750 毫秒。

默认值: `900`

[[NETCONSOLE]]
==== NETCONSOLE - 高级日志记录

`NETCONSOLE` 将调试消息复制到网络接口。IP地址和端口由 `NETCONSOLE` 字符串定义。

NOTE: NETCONSOLE会一直阻塞，直到以太网链接建立或超时。超时值是 `DHCP_TIMEOUT` ，尽管除非请求网络启动，否则不会尝试DHCP。

[[format]]
===== 格式

参见 https://wiki.archlinux.org/index.php/Netconsole

----
src_port@src_ip/dev_name,dst_port@dst_ip/dst_mac
E.g. 6665@169.254.1.1/,6666@/
----

为了简化解析，引导加载程序要求每个字段分隔符都存在。必须指定源 IP 地址，但以下字段可以留空并分配默认值。

* src_port - 6665
* dev_name - "" (始终忽略设备名称)
* dst_port - 6666
* dst_ip - 255.255.255.255
* dst_mac - 00:00:00:00:00

查看数据的一种方法是将测试的Raspberry Pi 4连接到另一个运行WireShark的Raspberry Pi，选择 "`udp.srcport == 6665`" 作为过滤器，然后选择 `+Analyze -> Follow -> UDP stream+` 以ASCII日志的形式查看。

`NETCONSOLE` 默认情况下不应启用，因为它可能会导致网络问题。它可以通过 GPIO 过滤器按需启用，例如

----
# Enable debug if GPIO 7 is pulled low
[gpio7=0]
NETCONSOLE=6665@169.254.1.1/,6666@/
----

默认值: ""  (未启用) +
最大长度: 32个字符

[[PARTITION]]
==== 分区

如果没有通过 `reboot` 命令(例如sudo reboot N)或 `autoboot.txt` 中的 `boot_partition=N` 明确设置分区选项，则分区选项可用于指定引导分区号。
如果用户按下按钮，这可用于从救援分区引导。

----
# Boot from partition 2 if GPIO 7 is pulled low
[gpio7=0]
PARTITION=2
----

默认值: 0

[[USB_MSD_EXCLUDE_VID_PID]]
==== USB_MSD_EXCLUDE_VID_PID

最多 4 个 VID/PID 对的列表，指定引导加载程序应忽略的设备。如果这与 HUB 匹配，则不会枚举 HUB，从而导致排除所有下游设备。 
这旨在允许在引导枚举期间忽略有问题（例如枚举非常慢）的设备。这是特定于引导加载程序的，不会传递给操作系统。

格式是以逗号分隔的十六进制值列表，其中 VID 是最重要的半字节。不允许使用空格。 例如 `034700a0,a4231234`

默认值: ""

[[USB_MSD_DISCOVER_TIMEOUT]]
==== USB_MSD_DISCOVER_TIMEOUT

如果在此超时内未找到 USB 大容量存储设备，则停止 USB-MSD 并选择下一个启动模式。

最小值: `5000` (5 秒) +
默认值: `20000` (20 秒) +

[[USB_MSD_LUN_TIMEOUT]]
==== USB_MSD_LUN_TIMEOUT

在前进到下一个 LUN（例如多插槽 SD-CARD 读卡器）之前等待多长时间（以毫秒为单位）。这仍在调整中，但如果连接了旧的/慢速设备以及包含操作系统的快速USB-MSD设备，则可能有助于加快启动速度。

最小值: `100` +
默认值: `2000` (2 秒)

[[USB_MSD_PWR_OFF_TIME]]
==== USB_MSD_PWR_OFF_TIME

在 USB 大容量存储启动期间，USB 端口的电源会关闭一小段时间，以确保 USB 大容量存储设备的正确运行。大多数设备使用默认设置可以正常工作：仅当您在从特定设备启动时遇到问题时，才更改此设置。设置 `USB_MSD_PWR_OFF_TIME=0` 将防止在 USB 大容量存储启动期间关闭 USB 端口的电源。

最小值: `250` +
最大值: `5000` +
默认值: `1000` (1 秒)

[[USB_MSD_STARTUP_DELAY]]
==== USB_MSD_STARTUP_DELAY

如果已定义，则在 USB 主控制器初始化后，将 USB 枚举延迟给定超时。如果 USB 硬盘驱动器初始化需要很长时间并触发 USB 超时，则此延迟可用于为驱动程序提供额外的初始化时间。可能还需要增加整体 USB 超时 (`USB_MSD_DISCOVER_TIMEOUT`) 。

最小值: `0` +
最大值: `30000` (30 秒) +
默认值: `0`

[[VL805]]
==== VL805
仅限计算模块 4。

如果该 `VL805` 属性设置为 `1` ， 则引导加载程序将搜索 VL805 PCIe XHCI 控制器，并尝试使用嵌入在引导加载程序 EEPROM 中的 VL805 固件对其进行初始化。这使得工业设计能够使用 VL805 XHCI 控制器，而无需为 VL805 固件提供专用的 SPI EEPROM。

* 在计算模块 4 上，引导加载程序从不写入专用的 VL805 SPI EEPROM。此选项仅将控制器配置为从 SDRAM 加载固件。
* 如果 VL805 XHCI 控制器具有专用的 EEPROM，请不要使用此选项。它将无法初始化，因为VL805 ROM将尝试使用专用的SPI EEPROM（如果安装）。
* 嵌入式 VL805 固件采用与树莓派 4B 相同的 USB 配置（2 个 USB 3.0 端口和 4 个 USB 2.0 端口）。不支持加载备用 VL805 固件映像，应使用专用的 VL805 SPI EEPROM 进行此类配置。

默认值: `0`

[[XHCI_DEBUG]]
==== XHCI_DEBUG

此属性是一个位字段，用于控制大容量存储引导模式的 USB 调试消息的详细程度。启用所有这些消息会生成大量日志数据，这会减慢启动速度，甚至可能导致启动失败。对于详细日志，最好使用 `NETCONSOLE` 。

|===
| 取值 | 日志

| 0x1
| USB 描述符

| 0x2
| 大容量存储模式状态机

| 0x4
| 大容量存储模式状态机 - 详细

| 0x8
| 所有 USB 请求

| 0x10
| 设备和集线器状态机

| 0x20
| 所有 xHCI TRB（非常详细）

| 0x40
| 所有 xHCI 事件（非常详细）
|===

若要合并值，请将它们相加。例如：

----
# Enable mass storage and USB descriptor logging
XHCI_DEBUG=0x3
----

默认值: `0x0` (未启用 USB 调试消息)

[[config_txt]]
==== config.txt 部分

在读取 `config.txt` 之后，GPU固件 `start4.elf` 读取引导加载程序EEPROM配置并检查名为 `[config.txt]` 的部分。如果 `[config.txt]` 部分存在，那么从该段开始到文件结尾的内容将被附加到内存中从引导分区读取的 `config.txt` f文件的内容中。这可用于自动将设置应用于每个操作系统，例如dtoverlays。

WARNING: 如果指定了导致引导失败的无效配置，则必须重新刷新引导加载程序EEPROM。

[[configuration-properties-in-config-txt]]
===  `config.txt` 中的配置属性

[[boot_ramdisk]]
==== boot_ramdisk
如果该属性设置为 `1` ，那么引导加载程序将尝试加载一个名为 `boot.img` 的 ramdisk 文件， 其中包含 xref:configuration.adoc#boot-folder-contents[引导文件系统]。后续文件 (例如  `start4.elf`) 从ramdisk中读取，而不是从原始引导文件系统中读取。

`boot_ramdisk`的主要目的是支持 `secure-boot`, 但是，未签名的 `boot.img` 文件对于网络引导或 `RPIBOOT` 配置也很有用。

* 虚拟硬盘文件的最大大小为 96MB。
* `boot.img` 文件是原始磁盘 `.img` 文件。 推荐的格式是没有 MBR 的普通 FAT32 分区。
* 虚拟硬盘文件系统的内存在操作系统启动之前释放。
* 如果选择了 xref:raspberry-pi.adoc#fail-safe-os-updates-tryboot[TRYBOOT] 引导加载程序将搜索 `tryboot.img` 而不是 `boot.img`。
* 另参见 xref:config_txt.adoc#autoboot-txt[autoboot.txt]

有关 `secure-boot`和创建 `boot.img` 文件的更多信息，请参见 https://github.com/raspberrypi/usbboot/blob/master/Readme.md[USBBOOT]

默认值: `0`

[[boot_load_flags]]
==== boot_load_flags

自定义固件（裸机）的实验属性。

位 0 （0x1） 表示 .elf 文件是自定义固件。这将禁用任何兼容性检查（例如，是否支持 USB MSD 启动）并在启动可执行文件之前重置 PCIe。

默认值: `0x0`

[[uart_2ndstage]]
==== uart_2ndstage

如果 `uart_2ndstage` 为 `1` ，则启用UART的调试记录。该选项还会自动启用. 该选项还会自动启用 `start.elf` 中的UART日志记录。这也在 xref:config_txt.adoc#boot-options[Boot options] 页面中进行了描述。

`BOOT_UART` 属性还会启用引导加载程序UART日志记录，但不会启用 `start.elf` 中的UART日志记录，除非还设置了 `uart_2ndstage=1` 。

默认值: `0`

[[erase_eeprom]]
==== erase_eeprom

如果 `erase_eeprom` 设置为 `1` ， `recovery.bin` 将擦除整个SPI EEPROM，而不是刷新引导加载程序映像。该属性在正常启动过程中不起作用。

默认值: `0`

[[eeprom_write_protect]]
==== eeprom_write_protect

配置EEPROM `Write Status Register`。 这可以设置为将整个EEPROM标记为写保护或清除写保护。

此选项必须与 EEPROM `/WP` 引脚配合使用，该引脚控制EEPROM `Write Status Register` 。  拉低 `/WP` low (CM4 `EEPROM_nEP` 或 Pi4B `TP5`) 不会对EEPROM进行写保护，除非已经配置了`Write Status Register` 。

详情请参见 https://www.winbond.com/resource-files/w25x40cl_f%2020140325.pdf[Winbond W25x40cl datasheet] 。

`recovery.bin` 的 `config.txt` 中的 `eeprom_write_protect` 设置。

|===
| 取值 | 描述

| 1
| 配置写保护区域以覆盖整个EEPROM。

| 0
| 清除写保护区域。

| -1
| 什么都不做。
|===

NOTE: `flashrom` 不支持清除写保护区域，如果定义了写保护区域，将无法更新 EEPROM。

默认值: `-1`

[[bootloader_update]]
==== bootloader_update

此选项可以设置为 0 以阻止自我更新，而无需更新 EEPROM 配置。这在通过网络引导更新多个树莓派时有时很有用，因为此选项可以按树莓派控制（例如，通过 `config.txt` 中的序列号过滤器）。

默认值: `1`

[[secure-boot-configuration-properties-in-config-txt]]
===  `config.txt` 中的安全启动配置属性
以下 `config.txt` 属性用于对 `secure-boot` OTP设置进行编程。这些更改是不可逆的，并且只能在刷新引导加载程序EEPROM映像时通过RPIBOOT进行编程。这确保了 `secure-boot` 不能被远程设置或通过意外插入过时的SD卡映像来设置。

有关启用 `secure-boot` 的详细信息，请参见 https://github.com/raspberrypi/usbboot[USBBOOT] 中的 https://github.com/raspberrypi/usbboot/blob/master/Readme.md#secure-boot[secure-boot readme] 和    https://github.com/raspberrypi/usbboot/blob/master/secure-boot-example/README.md[secure-boot tutorial] 。

[[program_pubkey]]
==== program_pubkey
如果此属性设置为 `1`， 则 `recovery.bin` 会将 EEPROM 镜像中公钥的hash写入 OTP。设置后，启动加载程序将拒绝使用不同 RSA 密钥签名的 EEPROM 镜像或未签名镜像。

默认值: `0`

[[revoke_devkey]]
==== revoke_devkey
如果该属性被设置为 `1` ，则 `recovery.bin` 将 向OTP写入一个值，以防止ROM加载不支持`secure-boot` 的第二阶段引导加载程序的旧版本。此操作可以防止通过恢复到旧版本的启动加载程序来关闭安全引导。

默认值: `0`

[[program_rpiboot_gpio]]
==== program_rpiboot_gpio
由于Raspberry Pi 4B或Raspberry Pi 400上没有专用的 `nRPIBOOT` 跳线，因此必须使用替代GPIO，通过拉低GPIO来选择 `nRPIBOOT` 模式。而且只能选择一个GPIO，可用选项有2、4、5、7、8。此属性不依赖于 `安全启动`，但请验证此GPIO配置是否与任何可能在启动期间拉低GPIO的HAT发生冲突。

出于安全考虑，该属性只能通过 `RPIBOOT` 进行编程，因此必须首先使用 `erase_eeprom` 擦除启动加载程序EEPROM。这会导致BCM2711 ROM故障切换到 `RPIBOOT` 模式，则允许设置此选项。

默认值: ``

[[program_jtag_lock]]
==== program_jtag_lock
如果此属性设置为 `1` ，则 `recovery.bin` 将编程一个OTP值，以防止使用VideoCore JTAG。该选项要求同时设置 `program_pubkey` 和 `revoke_devkey` 。此选项可以防止故障分析，并且只能在设备经过全面测试后设置。

默认值: `0`

[[bootloader_update_stable]]
=== 更新到最新 / 稳定的启动加载程序
启动加载程序的默认版本仅针对关键修复和主要版本进行更新。最新/稳定启动加载程序更新较频繁以同步最新的修复和改进。

高级用户可以切换到最新/稳定启动加载程序以获得最新功能。 
打开命令提示符并启动`raspi-config`。

----
sudo raspi-config
----
导航至 `高级选项` ，再导航至 `启动加载程序版本` 。选择 `最新`，然后选择 `是` 进行确认。选择 `完成` 并确认你要重新启动。重新启动后，再次打开命令提示符并更新系统。
----
sudo apt update
sudo apt install rpi-eeprom  # Update rpi-eeprom to the latest version
----

如果运行`rpi-eeprom-update`，则会看到一个更新版本的启动加载程序可用，并且是 `稳定` 版本。

----
*** UPDATE AVAILABLE ***
BOOTLOADER: update available
   CURRENT: Tue 25 Jan 14:30:41 UTC 2022 (1643121041)
    LATEST: Thu 10 Mar 11:57:12 UTC 2022 (1646913432)
   RELEASE: stable (/lib/firmware/raspberrypi/bootloader/stable)
            Use raspi-config to change the release.
----

现在可以更新启动加载程序。

----
sudo rpi-eeprom-update -a
sudo reboot
----

如果你在Raspberry Pi重新启动后再次运行 `rpi-eeprom-update` ，你应该会看到 `当前` 日期已更新，表明使用的是最新版本的启动加载程序。

----
BOOTLOADER: up to date
   CURRENT: Thu 10 Mar 11:57:12 UTC 2022 (1646913432)
    LATEST: Thu 10 Mar 11:57:12 UTC 2022 (1646913432)
   RELEASE: stable (/lib/firmware/raspberrypi/bootloader/stable)
            Use raspi-config to change the release.
----
