[[http-boot]]
== HTTP 启动

网络安装功能使用HTTP通过以太网将Raspberry Pi启动到嵌入式 xref:getting-started.adoc#using-raspberry-pi-imager[Raspberry Pi Imager] 应用程序中。

除了网络安装之外，你还可以使用通过HTTP下载的文件以 xref:raspberry-pi.adoc#BOOT_ORDER[启动模式] `7`显式地启动设备。 即使 xref:raspberry-pi.adoc#NET_INSTALL_ENABLED[禁用了启动时网络安装] ，你仍然可以使用它。

例如，你可以将其添加到 `BOOT_ORDER` 作为备用启动方法，或者将其放在 GPIO 条件后，以便在 GPIO 引脚被拉低时从你自己的服务器使能HTTP启动。

例如，如果将以下内容添加到 eeprom 配置中，并且 GPIO 8（默认状态为1或高电平）将被拉低，则文件 `\http://downloads.raspberrypi.org:80/net_install/boot.img` 和 `\http://downloads.raspberrypi.org:80/net_install/boot.sig` 将被下载。如果在启动时使能网络安装，它将使用相同的 URL。如果 GPIO 8 未被拉低，则行为将保持不变。
```
[gpio8=0]
BOOT_ORDER=0xf7
HTTP_HOST=downloads.raspberrypi.org
NET_INSTALL_ENABLED=0
```

如果启用了安全启动且未设置 xref:raspberry-pi.adoc#HTTP_HOST[HTTP_HOST] ，则将忽略`BOOT_ORDER` 中的HTTP。

[[requirements]]
=== 要求

要使用 HTTP 启动，你需要 xref:raspberry-pi.adoc#bootloader_update_stable[使用最新 / 稳定的启动加载程序配置] 并更新到2022年3月10日或更高版本的启动加载程序。HTTP启动仅适用于以太网，因此你需要通过网线将Raspberry Pi连接到网络。

[[keys]]
=== 密钥

所有HTTP下载都必须签名。启动加载程序包括默认主机 `fw-download-alias1.raspberrypi.com`上文件的公钥。该密钥将用于验证网络安装镜像，*除非* 你设置了 xref:raspberry-pi.adoc#HTTP_HOST[HTTP_HOST] *并* 在eeprom中包含一个公钥。 这允许你在自己的服务器上托管Raspberry Pi网络安装镜像。

WARNING: 使用你自己的网络安装镜像需要你对镜像进行签名并将公钥添加到 eeprom中。如果你使用公共 eeprom 更新，你的密钥将丢失且需要重新添加。

https://github.com/raspberrypi/usbboot/blob/master/Readme.md[USBBOOT] 具有编程公钥所需的所有工具。你需要参照下文来操作：

----
# Add your PUBLIC key to the eeprom. boot.conf contains your modifications
rpi-eeprom-config -c boot.conf -p mypubkey.pem -o pieeprom.upd pieeprom.original.bin

# Generate signature for your eeprom
rpi-eeprom-digest -i pieeprom.upd -o pieeprom.sig

# Sign the network install image with your PRIVATE key
# Put boot.img and boot.sig on your web server
rpi-eeprom-digest -i boot.img -o boot.sig -k myprivkey.pem
----

[[secure-boot]]
=== 安全启动

如果使能了安全启动，则Raspberry Pi只能运行由客户私钥签名的代码。因此你如果需要使用网络安装或HTTP启动模式进行安全启动，你必须使用自己的密钥对 `boot.img` 进行签名并生成 `boot.sig` ，并将这些文件存放在一个路径下以供下载。eeprom中的公钥将用于验证图像。

如果使能了安全启动且未设置 xref:raspberry-pi.adoc#HTTP_HOST[HTTP_HOST] ，则将禁用网络安装和 HTTP 启动。

有关安全启动的详细信息，请参见 https://github.com/raspberrypi/usbboot/blob/master/secure-boot-recovery/README.md[USBBOOT]。
