[[network-booting]]
== 网络启动

本节介绍网络启动如何在Raspberry Pi 3B/3B+ 和 Raspberry Pi 2B v1.2上的工作原理。在Raspberry Pi 4上，网络启动是在EEPROM的第二阶段启动加载程序中实现。有关更多信息，请参见 xref:raspberry-pi.adoc#raspberry-pi-4-bootloader-configuration[Raspberry Pi 4 启动加载程序配置] 页面，我们还有一个 xref:remote-access.adoc#network-boot-your-raspberry-pi[关于设置网络启动系统的教程] 供参考。网络启动仅适用于上述型号的Raspberry Pi内置的有线适配器。不支持通过无线LAN启动，也不支持从任何其他有线网络设备启动。

如果需要进行网络启动，则启动 ROM 执行以下操作：

* 初始化板载以太网设备（Microchip LAN9500或LAN7500）
* 发送 DHCP 请求 (供应商类标识符 DHCP option 60 设置为 'PXEClient:Arch:00000:UNDI:002001')
* 接收 DHCP 回复
* (可选) 接收 DHCP 代理回复
* ARP 到 tftpboot 服务器
* ARP reply includes tftpboot server ethernet address
* TFTP RRQ 'bootcode.bin'
 ** 找不到文件：服务器回复 TFTP 错误响应以及文本错误消息
 ** 文件存在：服务器将使用文件的第一个块（512 字节）数据进行回复，并在标头中带有块号
  *** Raspberry Pi 使用包含块号的 TFTP ACK 数据包进行回复，并重复直到最后一个不是 512 字节的数据块
* TFTP RRQ 'bootsig.bin'
 ** 这通常会导致一个 `file not found` 错误。TFTP启动服务器能够处理这个问题。

从这一点开始，`bootcode.bin` 代码继续加载系统。它将尝试访问的第一个文件是 [`serial_number`]/start.elf 。如果不会发生错误，则任何其他要读取的文件都将以 `serial_number` 开头。这个操作很有用，因为它使你能够为Raspberry Pi创建带有单独的start.elf /内核目录。如果需要获得设备的序列号，你可以尝试这种启动模式，并查看使用 tcpdump / wireshark 访问了哪些文件，或者你可以运行标准的Raspberry Pi OS SD卡和 `cat /proc/cpuinfo` 。

如果你将所有文件放入 tftp 目录的根目录中，则将从那里访问所有后续文件。

[[debugging-network-boot-mode]]
=== 调试网络启动模式

首先检查OTP位是否正确编程，为此需要将 `program_usb_boot_mode=1` 添加
到config.txt中并重新启动（使用可以正确启动Raspberry Pi 操作系统的标准SD卡）。完成此操作后，你可以执行以下操作： 

[,bash]
----
 vcgencmd otp_dump | grep 17:
----

如果第 17 行包含 `3020000a` ，则 OTP 已正确编程。你现在可以取出SD卡并再插入以太网， Raspberry Pi通电后等待约5秒以太网的 LED灯会点亮。

要抓获服务器上的以太网数据包，请在 tftpboot 服务器（如果使用时存在区别可以使用 DHCP 服务器）上使用 tcpdump。你需要在tcpdump抓获数据包，否则你将无法看到直接发送的数据包。

----
sudo tcpdump -i eth0 -w dump.pcap
----

以上执行的命令会将eth0的所有内容写入dump.pcap文件，然后你可以对其进行后期处理或上传到 cloudshark.com 进行通信。

[[dhcp-request-reply]]
==== DHCP 请求 / 回复

你至少应该看到如下所示的DHCP请求和回复：

----
6:44:38.717115 IP (tos 0x0, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 348)
    0.0.0.0.68 > 255.255.255.255.67: [no cksum] BOOTP/DHCP, Request from b8:27:eb:28:f6:6d, length 320, xid 0x26f30339, Flags [none] (0x0000)
	  Client-Ethernet-Address b8:27:eb:28:f6:6d
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Discover
	    Parameter-Request Option 55, length 12:
	      Vendor-Option, Vendor-Class, BF, Option 128
	      Option 129, Option 130, Option 131, Option 132
	      Option 133, Option 134, Option 135, TFTP
	    ARCH Option 93, length 2: 0
	    NDI Option 94, length 3: 1.2.1
	    GUID Option 97, length 17: 0.68.68.68.68.68.68.68.68.68.68.68.68.68.68.68.68
	    Vendor-Class Option 60, length 32: "PXEClient:Arch:00000:UNDI:002001"
	    END Option 255, length 0
16:44:41.224619 IP (tos 0x0, ttl 64, id 57713, offset 0, flags [none], proto UDP (17), length 372)
    192.168.1.1.67 > 192.168.1.139.68: [udp sum ok] BOOTP/DHCP, Reply, length 344, xid 0x26f30339, Flags [none] (0x0000)
	  Your-IP 192.168.1.139
	  Server-IP 192.168.1.1
	  Client-Ethernet-Address b8:27:eb:28:f6:6d
	  Vendor-rfc1048 Extensions
	    Magic Cookie 0x63825363
	    DHCP-Message Option 53, length 1: Offer
	    Server-ID Option 54, length 4: 192.168.1.1
	    Lease-Time Option 51, length 4: 43200
	    RN Option 58, length 4: 21600
	    RB Option 59, length 4: 37800
	    Subnet-Mask Option 1, length 4: 255.255.255.0
	    BR Option 28, length 4: 192.168.1.255
	    Vendor-Class Option 60, length 9: "PXEClient"
	    GUID Option 97, length 17: 0.68.68.68.68.68.68.68.68.68.68.68.68.68.68.68.68
	    Vendor-Option Option 43, length 32: 6.1.3.10.4.0.80.88.69.9.20.0.0.17.82.97.115.112.98.101.114.114.121.32.80.105.32.66.111.111.116.255
	    END Option 255, length 0
----

回复的重要部分是Vendor-Option Option 43选项。此选项需要包含字符串 "Raspberry Pi Boot"，但由于对于启动ROM 中的错误，你可能需要在字符串末尾添加3个空格。

[[tftp-file-read]]
==== TFTP 文件读取

你将会知道Vendor Option选项是否被正确指定：如果被正确指定，你将看到正在发送的TFTP RRQ 数据包。 RRQ 可以通过第一个数据块或错误（表示找不到文件）来回复。在一些情况下，他们甚至会收到第一个数据包，然后传输被 Raspberry Pi 中止（在检查文件是否存在时会发生这种情况）。下面的示例包含3个数据包：原始读取请求、第一个数据块（始终为516字节并包含标头和512字节数据，尽管最后一个块始终小于 512 字节并且长度可能为0）和第三个数据包（包含与数据块中的帧号匹配的帧号的 ACK）。

----
16:44:41.224964 IP (tos 0x0, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 49)
    192.168.1.139.49152 > 192.168.1.1.69: [no cksum]  21 RRQ "bootcode.bin" octet
16:44:41.227223 IP (tos 0x0, ttl 64, id 57714, offset 0, flags [none], proto UDP (17), length 544)
    192.168.1.1.55985 > 192.168.1.139.49152: [udp sum ok] UDP, length 516
16:44:41.227418 IP (tos 0x0, ttl 128, id 0, offset 0, flags [none], proto UDP (17), length 32)
    192.168.1.139.49152 > 192.168.1.1.55985: [no cksum] UDP, length 4
----

[[known-problems]]
=== 已知问题

以太网启动模式存在许多已知问题。由于启动模式的实现是在芯片本身中，因此除了使用包含bootcode.bin文件的SD卡外，暂无其他解决方法。

[[dhcp-requests-time-out-after-five-tries]]
==== DHCP请求在5次尝试后超时

Raspberry Pi将尝试5次DHCP请求，中间间隔5秒，总时间为 25 秒。如果服务器在这段时间内无法响应，则Raspberry Pi将进入低功耗状态。除了SD卡上的bootcode.bin之外，暂无其他解决方法。

[[tftp-server-on-separate-subnet-not-supported]]
==== 不支持单独子网上的 TFTP 服务器

已在Raspberry Pi 3 Model B+ （BCM2837B0） 中修复。

[[dhcp-relay-broken]]
==== DHCP relay 已损坏

DHCP check也会检查hops值是否为 `1`，而 DHCP relay则不会检查。

已在Raspberry Pi 3 Model B+ 中修复。

[[raspberry-pi-boot-string]]
==== Raspberry Pi 启动字符串

由于计算字符串长度时出错，DHCP回复中的 "Raspberry Pi 启动 " 字符串需要额外的3个空格。

已在Raspberry Pi 3 Model B+ 中修复。

[[dhcp-uuid-constant]]
==== DHCP UUID 常量

设置DHCP UUID为常量值。

已在Raspberry Pi 3 Model B+ 中修复，该值设置为 32 位序列号。

[[arp-check-can-fail-to-respond-in-the-middle-of-tftp-transaction]]
==== ARP check 可能无法在 TFTP 事务中响应

Raspberry Pi只会在处于初始化阶段时响应 ARP 请求;一旦开始传输数据，其将无法继续响应。

已在Raspberry Pi 3 Model B+ 中修复。

[[dhcp-requestreplyack-sequence-not-correctly-implemented]]
==== DHCP 请求/回复/确认序列未正确实现

在启动时，Raspberry Pi 会广播一个 DHCP 发现数据包。DHCP 服务器使用 DHCPOFFER 数据包。然后Raspberry Pi 继续启动，无需执行 DHCPREQUEST 或等待 DHCPACK。这可能会导致两个单独的设备被提供相同的 IP 地址，并在未正确分配给客户端的情况下使用它。

在这种情况下，不同的 DHCP 服务器具有不同的行为。dnsmasq（取决于设置）将对 MAC 地址进行hash以确定 IP 地址，并 ping IP 地址以确保它尚未被使用。这杨操作减少了发生这种情况的可能性，因为它需要在hash中产品冲突。
