[[gpio-boot-mode]]
== GPIO 启动模式

NOTE: GPIO 启动模式适用于 Raspberry Pi 3A+、Raspberry Pi 3A+ 3B/ Raspberry Pi 3A+ 3B+、CM3和CM3+。

可以将Raspberry Pi配置为允许使用连接到 GPIO 连接器的硬件在开机时选择启动模式：即 GPIO 启动模式。这是通过设置SoC的OTP存储器中的位来完成的。设置位完成后，它们将会永久分配 5 个 GPIO 以允许进行此选择。如果设置了OTP 位，则无法取消操作；所以在设置之前需要仔细考虑启用此功能，因为这 5个GPIO线将始终控制启动。尽管在Raspberry Pi启动后可以将GPIO用于其他功能，但必须对齐进行设置，以便它们在Raspberry Pi启动时启用所需的启动模式。

若要启用 GPIO 启动模式，请将以下行添加到 `config.txt` 文件中:

----
program_gpio_bootmode=n
----

其中n表示需要使用的 GPIO组。 添加完成后后重新启动Raspberry Pi，以使用此设置对OTP进行编程。Bank 1包含GPIO22-26，Bank2包含GPIO39-43。除非你有CM，否则必须使Bank1：Bank 2中的GPIO仅在CM上可用。由于 OTP位的排列方式，如果首先为Bank1 编程 GPIO启动模式，则后续可以选择Bank2。反之则不然：若为 GPIO 启动模式选择Bank2，则后续无法选择Bank1。

启用 GPIO 启动模式后，Raspberry Pi 将不再启动。你必须拉起至少一个启动模式 GPIO 引脚才能启动 Raspberry Pi。

[[pin-assignments]]
=== 引脚分配

[[raspberry-pi-3b-and-compute-module-3]]
==== Raspberry Pi 3B 和CM3

[cols="^,^,^"]
|===
| Bank 1 | Bank 2 | 启动类型

| 22
| 39
| SD0

| 23
| 40
| SD1

| 24
| 41
| NAND (目前不支持Linux)

| 25
| 42
| SPI (目前不支持Linux)

| 26
| 43
| USB
|===

上表中的 USB 同时选择 USB 设备启动模式和 USB 主机启动模式。为了使用 USB 启动模式，必须在 OTP 内存中启用它。有关详细信息，请参见 xref:raspberry-pi.adoc#usb-device-boot-mode[USB设备启动] 和 xref:raspberry-pi.adoc#usb-host-boot-mode[USB主机启动].

[[newer-raspberry-pi-3b-bcm2837b0-with-the-metal-lid-raspberry-pi-3a-3b-and-compute-module-3]]
==== 较新的Raspberry Pi 3B（带金属盖的 BCM2837B0）、Raspberry Pi 3A+、Raspberry Pi 3B+和CM3+

[cols="^,^,^"]
|===
| Bank 1 | Bank 2 | 启动类型

| 20
| 37
| SD0

| 21
| 38
| SD1

| 22
| 39
| NAND (目前不支持Linux)

| 23
| 40
| SPI (目前不支持Linux)

| 24
| 41
| USB 设备

| 25
| 42
| USB 主机 - 大容量存储设备

| 26
| 43
| USB 主机 - 以太网
|===

NOTE: 按 GPIO线的数字顺序尝试各种启动模式，即先尝试SD0，再尝试SD1，然后尝试NAND 等。

[[boot-flow]]
=== Boot Flow

SD0是Broadcom SD卡/ MMC接口。当SoC内的启动ROM运行时，它始终将SD0连接到内置的microSD卡槽。在具有 eMMC 设备的CM上，SD0 连接到该模块;CM Lite SD0位于CM Lite的边缘连接器上，并连接到 CMIO 载板中的 microSD 卡槽。

SD1是Arasan SD卡/ MMC接口，也支持SDIO的能力。所有内置无线网的Raspberry Pi型号都使用SD1通过 SDIO连接到无线芯片。

GPIO 线路的默认拉力电阻为 50KΩ，如 https://datasheets.raspberrypi.com/bcm2835/bcm2835-peripherals.pdf[BCM2835 ARM 外设 datasheet] 的第102页所述。建议使用5KΩ的拉力电阻来拉起 GPIO 线路：这将使 GPIO 正常工作，但不会消耗太多功率。
