[[usb-mass-storage-boot]]
== USB大容量存储启动

NOTE: 适用于Raspberry Pi 2B v1.2、Raspberry Pi 3A+、Raspberry Pi 3B、Raspberry Pi 3B+、Raspberry Pi 4B、Raspberry Pi 400 和Raspberry Pi Zero 2 W，以及Raspberry Pi CM3、Raspberry Pi CM3+ 和Raspberry Pi CM4。

本页介绍如何从 USB 大容量存储设备（如闪存驱动器或 USB 硬盘）启动Raspberry Pi。连接 USB 设备（尤其是硬盘和 SSD）时，请注意其电源要求。如果你希望将多个SSD或硬盘连接到Raspberry Pi，则需要外部电源 - 有源硬盘盒或供电的USB hub。请注意，Raspberry Pi 4B之前的型号存在已知问题(某些USB设备无法启动)。

[[pi4]]
=== Raspberry Pi 4B 和 Raspberry Pi 400

Raspberry Pi 400 和新版的Raspberry Pi 4B 板中的启动加载程序默认支持 USB 启动，但可能需要修改 `BOOT_ORDER` 启动加载程序配置。在早期的Raspberry Pi 4B 板上，或者需要选择备用启动模式的场景，必须更新启动加载程序。

如下:-

* 通过 xref:raspberry-pi.adoc#imager[Raspberry Pi Imager] 更改启动模式的说明。
* 通过 xref:raspberry-pi.adoc#raspi-config[raspi-config] 更改启动模式的说明。
* 其他启动配置选项的 xref:raspberry-pi.adoc#raspberry-pi-4-bootloader-configuration[启动加载程序配置] 页面。

[[cm4]]
=== CM4

请参见 xref:compute-module.adoc#flashing-the-compute-module-emmc[烧录CM的eMMC] 以获取启动加载程序更新说明。

[[raspberry-pi-3b]]
=== Raspberry Pi 3B+

Raspberry Pi 3B+支持开箱即用的USB大容量存储启动。

[[raspberry-pi-2b-3a-3b-cm3-cm3-zero-2-w]]
=== Raspberry Pi 2B/3A+/3B/CM3/CM3+/Zero 2 W

在Raspberry Pi 2B v1.2/3A+/3B/Zero 2 W 和CM3、CM3+ 上，你必须首先启用 xref:raspberry-pi.adoc#usb-host-boot-mode[USB主机启动模式]。这是为了允许USB大容量存储启动和 xref:raspberry-pi.adoc#network-booting[网络启动]。请注意，Raspberry Pi 3A+ 或 Zero 2 W 不支持网络启动。

如果要启用 USB 主机启动模式，需要从 SD 卡启动Raspberry Pi，并使用特殊选项来设置一次性可编程 （OTP） 内存中的USB 主机启动模式位。设置此位后，不再需要SD卡。

IMPORTANT: 对OTP所做的任何更改都是永久性的，无法撤消。

NOTE: 在Raspberry Pi 3A+ 上，设置 OTP 位以启用 USB 主机启动模式将永久阻止Raspberry Pi在 USB 设备模式下启动。

你可以通过运行Raspberry Pi OS的SD卡对OTP位进行编程。

使用以下代码启用 USB 主机启动模式：

[,bash]
----
echo program_usb_boot_mode=1 | sudo tee -a /boot/config.txt
----

这会将 `program_usb_boot_mode=1` 添加到 `/boot/config.txt`的末尾。

请注意，尽管该选项已命名为 `program_usb_boot_mode`但其仅启用 USB 主机启动模式。USB 设备启动模式仅适用于Raspberry Pi的部分型号- 请参见 xref:raspberry-pi.adoc#usb-device-boot-mode[USB设备启动模式]。

下一步是使用 `sudo reboot` 重新启动Raspberry Pi，并检查 OTP 是否已编程：

[,bash]
----
vcgencmd otp_dump | grep 17:
17:3020000a
----

检查是否显示输出 `0x3020000a` 。如果不是，则 OTP 位尚未成功编程。在这种情况下，请再次执行编程过程。如果该位仍未设置，则表示Raspberry Pi硬件本身出现故障。

你可以从 `config.txt` 中删除 `program_usb_boot_mode` 行，再把SD卡放到另一个Raspberry Pi中，其就不会编程usb主机启动模式。确保 `config.txt` 末尾没有空行。

你可以从 USB 大容量存储设备启动，方法与从 SD 卡启动相同 - 有关详细信息，请参见以下部分。

[[booting-from-usb-mass-storage]]
=== 从USB大容量存储器启动

该 xref:getting-started.adoc#installing-the-operating-system[过程] 与SD卡相同 - 只需使用操作系统镜像对USB存储设备进行镜像即可。

准备存储设备后，将驱动器连接到Raspberry Pi并打开Raspberry Pi的电源，同时注意外部驱动器的额外 USB 电源要求。 
等待5~10秒后，Raspberry Pi开始启动并在连接的显示器上显示彩虹启动画面。确保未在Raspberry Pi中插入SD卡，因为如果插入了SD卡，其将首先从该卡启动。

请参见 xref:raspberry-pi.adoc#raspberry-pi-boot-modes[启动模式文档] ，获取启动顺序和备用启动模式（网络、USB设备、GPIO或 SD启动）的更多信息。

[[known-issues]]
=== 已知问题 

IMPORTANT:  *不* 适用于Raspberry Pi 4 Model B。

* 检查可启动 USB 设备的默认超时时间为2秒，部分闪存驱动器和硬盘的启动速度太慢。可以将此超时时间延长至5秒（将新文件timeout添加到SD卡），但请注意，部分设备可能需要更长的时间才能响应。
* 部分闪存驱动器具有非常具体的协议要求，启动代码无法处理这些要求，因此可能不兼容。

[[special-bootcode-bin-only-boot-mode-2]]
=== 特定的 `bootcode.bin`-only 启动模式

IMPORTANT: This does *not* apply to Raspberry Pi 4 Model B.

如果你无法使用特定的USB设备启动Raspberry Pi，则Raspberry Pi 2B v1.2/3A+/3B/3B +的替代方案是使用特定的 xref:raspberry-pi.adoc#raspberry-pi-boot-modes[bootcode.bin-only] 启动模式。Raspberry Pi仍将从SD卡启动，但bootcode.bin是从SD卡读取的唯一文件。

[[hardware-compatibility]]
=== 硬件兼容性

在尝试从 USB 大容量存储设备启动之前，建议验证该设备在 Linux 下是否正常工作。使用 SD 卡启动并插入 USB 大容量存储设备，则应该显示为可移动驱动器。这对于USB SATA适配器尤其重要，在大容量存储模式下，启动加载程序可能支持该适配器，但如果Linux选择 https://en.wikipedia.org/wiki/USB_Attached_SCSI[USB Attached SCSI - UAS] 模式，则该适配器会失败。请参见此https://forums.raspberrypi.com/viewtopic.php?t=245931[论坛帖子] ，了解 UAS 以及如何添加 https://www.kernel.org/doc/html/v5.0/admin-guide/kernel-parameters.html[usb-storage.quirks] 以解决此问题。

旋转硬盘驱动器需要带供电能力的 USB hub。即使看起来有效，如果没有供电能力的USB HUB可能会遇到间歇性故障。

[[multiple-bootable-drives]]
=== 多个可启动驱动器

当搜索可启动分区时，启动加载程序会并行扫描所有 USB 大容量存储设备，并选择第一个进行响应。如果启动分区不包含合适的 `start.elf` 文件，则选择下一个可用设备。无根据 USB 拓扑指定启动设备的方法，因为这会减慢启动速度并增加不必要且难以支持的配置复杂性。

NOTE:  `config.txt` 文件 xref:config_txt.adoc#conditional-filters[条件筛选器] 可用于在复杂的设备配置中选择备用固件。
