[[raspberry-pi-4-boot-eeprom]]
== Raspberry Pi 4 启动 EEPROM

Raspberry Pi 4、Raspberry Pi 400、CM4和CM4S使用 EEPROM 来启动系统。所有其他型号的Raspberry Pi计算机都使用位于启动文件系统中的 `bootcode.bin` 文件来启动系统。

NOTE: https://github.com/raspberrypi/rpi-eeprom/[Github] 上提供了用于创建  `rpi-eeprom` 包的脚本和预编译的二进制文件，该包用于更新Raspberry Pi 4引导加载程序和VLI USB控制器EEPROM。

[[boot-diagnostics]]
=== 启动诊断

如果在启动过程中发生错误，则将通过绿色 LED 显示 xref:configuration.adoc#led-warning-flash-codes[错误代码] 。较新版本的引导加载程序将显示 xref:raspberry-pi.adoc#boot-diagnostics-on-the-raspberry-pi-4[诊断消息] ，该消息将显示在两个HDMI显示器上。

[[updating-the-bootloader]]
=== 更新启动加载程序

[[raspberry-pi-4-and-raspberry-pi-400]]
==== Raspberry Pi 4 和 Raspberry Pi 400

Raspberry Pi OS 自动更新启动加载程序以进行关键错误修复。 手动更新启动加载程序或更改启动模式的推荐方法是 https://www.raspberrypi.com/software/[Raspberry Pi Imager] 和 xref:configuration.adoc#raspi-config[raspi-config]

[[imager]]
==== 使用 Raspberry Pi Imager 更新启动加载程序

IMPORTANT: 这是更新启动加载程序的推荐方法。

Raspberry Pi Imager 提供了一个 GUI，用于更新启动加载程序和选择启动模式。

. 下载 https://www.raspberrypi.com/software/[Raspberry Pi Imager]
. 选择备用 SD 卡，内容将被覆盖！
. 启动 `Raspberry Pi Imager`
. 在`Operating System`下选择 `Misc utility images`
. 选择 `Bootloader`
. 选择启动模式，即 `SD` (推荐)、 `USB`或`Network`.
. 选择 `SD card` ，然后单击 `Write`
. 使用新镜像启动Raspberry Pi并等待至少10秒钟。
. 更新成功时，绿色LED 将以稳定模式闪烁，HDMI 显示屏将呈现绿色。
. 关闭Raspberry Pi电源并取出 SD 卡。

[[raspi-config]]
==== 使用 raspi-config 更新启动加载程序

从Raspberry Pi OS中更改启动模式或启动加载程序版本，请运行 xref:configuration.adoc#raspi-config[raspi-config]

. xref:os.adoc#updating-and-upgrading-raspberry-pi-os[更新] Raspberry Pi操作系统获取最新版本的rpi-eeprom软件包。
. 运行 `sudo raspi-config`
. 选择 `Advanced Options`
. 选择 `Bootloader Version`
. 选择 `Default`（对于出厂默认设置）或 `Latest` （对于最新的稳定引导加载程序版本）。
. 重启

[[updating-the-eeprom-configuration]]
=== 更新EEPROM配置

启动行为（例如SD或USB启动）由嵌入在EEPROM镜像中的配置文件控制，并且可通过  `rpi-eeprom-config` 工具进行修改。

有关配置的详细信息，请参见 xref:raspberry-pi.adoc#raspberry-pi-4-bootloader-configuration[启动加载程序] 配置部分。

[[reading-the-current-eeprom-configuration]]
==== 读取当前的EEPROM配置

要查看当前启动加载程序在上次启动运行期间使用的配置，请运行 `rpi-eeprom-config` 或 `vcgencmd bootloader_config`.

[[reading-the-configuration-from-an-eeprom-image]]
==== 从EEPROM镜像读取配置

从EEPROM镜像读取配置：

[,bash]
----
rpi-eeprom-config pieeprom.bin
----

[[editing-the-current-bootloader-configuration]]
==== 编辑当前启动加载程序配置

以下命令将当前EEPROM配置加载到文本编辑器中。当编辑器关闭时， `rpi-eeprom-config` 将更新的配置应用于最新可用的EEPROM版本，并在系统重新启动时使用 `rpi-eeprom-update` 来规划更新:

[,bash]
----
sudo -E rpi-eeprom-config --edit
sudo reboot
----

如果更新的配置相同或为空，则不会进行任何更改。

编辑器由`EDITOR`环境变量选择。

[[applying-a-saved-configuration]]
==== 应用保存的配置

以下命令将 `boot.conf` 应用于最新可用的EEPROM镜像，并在系统重新启动时使用 `rpi-eeprom-update` 来规划更新。

----
sudo rpi-eeprom-config --apply boot.conf
sudo reboot
----

[[automaticupdates]]
=== 自动更新

 `rpi-eeprom-update` `systemd` 服务在启动时运行，如果有新的映像可用，它会应用更新，自动迁移当前的启动加载程序配置。

禁用自动更新：

[,bash]
----
sudo systemctl mask rpi-eeprom-update
----

重新启用自动更新：

[,bash]
----
sudo systemctl unmask rpi-eeprom-update
----

NOTE: 如果设置了 xref:raspberry-pi.adoc#FREEZE_VERSION[FREEZE_VERSION] 启动加载程序 EEPROM 配置，则 EEPROM 更新服务将跳过任何自动更新。如果安装了多个操作系统或交换 SD 卡时，则无需单独禁用 EEPROM 更新服务。

[[rpi-eeprom-update]]
==== `rpi-eeprom-update`

Raspberry Pi操作系统使用 `rpi-eeprom-update` 脚本来实现 <<automaticupdates,自动更新>> 服务。该脚本还可以交互运行或包装以创建自定义启动加载程序更新服务。

读取当前的EEPROM版本：

[,bash]
----
vcgencmd bootloader_version
----

检查是否有可用的更新：

[,bash]
----
sudo rpi-eeprom-update
----

安装更新：

----
sudo rpi-eeprom-update -a
sudo reboot
----

取消挂起的更新：

[,bash]
----
sudo rpi-eeprom-update -r
----

安装特定的启动加载程序EEPROM镜像：

[,bash]
----
sudo rpi-eeprom-update -d -f pieeprom.bin
----

`-d` 标志表示 `rpi-eeprom-update` 使用指定镜像文件中的配置，而不是自动迁移当前配置。

显示内置文档：

----
rpi-eeprom-update -h
----


[[bootloader-release]]
=== 启动加载程序发布状态

固件版本状态对应于启动加载程序固件镜像 (`+/lib/firmware/raspberrypi/bootloader/...+`)的特定子目录，并且可以更改以选择不同的发布流。

* `default` - 需要支持新硬件、修复关键错误和定期`更新` 版本测试的新功能时进行更新。
* `latest` - 当新功能成功通过 beta 测试时进行更新。
* `beta` - 测试新功能或实验性功能。

由于发布状态字符串只是一个子目录名称，因此可以创建自己的发布流，例如固定版本或自定义网络启动配置。

注意 `default` 和 `latest` 是指向 `critical` 和 `stable` 的旧版本名称的符号链接。

[[changing-the-bootloader-release]]
==== 更改启动加载程序版本

NOTE: 你可以通过编辑 `/etc/default/rpi-eeprom-update` 文件并将 `FIRMWARE_RELEASE_STATUS` 条目更改为相应的流，来更改更新期间要使用的发布流。

[[updating-the-bootloader-configuration-in-an-eeprom-image-file]]
==== 更新 EEPROM 镜像文件中的启动加载程序配置

以下命令用 `boot.conf` 替换 `pieeprom.bin` 中启动加载程序配置，并将新镜像写入 `new.bin`:

[,bash]
----
rpi-eeprom-config --config boot.conf --out new.bin pieeprom.bin
----

[[recovery-bin]]
==== recovery.bin

上电时，BCM2711 ROM会在SD卡上的引导分区的根目录中查找名为 `recovery.bin` 的文件。如果找到有效的recovery.bin，则ROM执行该文件，而不是EEPROM的内容。这种机制确保启动加载程序EEPROM始终可以重置为出厂默认设置的有效镜像。
另请参见 xref:raspberry-pi.adoc#raspberry-pi-4-boot-flow[Raspberry Pi 4 启动流程]

[[eeprom-update-files]]
==== EEPROM更新文件

[cols="1,1"]
|===
| 文件名
| 目的

| recovery.bin
| 启动加载程序EEPROM恢复可执行文件

| pieeprom.upd
| 启动加载程序 EEPROM 镜像

| pieeprom.bin
| 启动加载程序EEPROM镜像 - 与 pieeprom.upd 相同，但更改了 recovery.bin 行为

| pieeprom.sig
| 启动加载程序镜像的sha256 校验 (pieeprom.upd/pieeprom.bin)

| vl805.bin
| VLI805 USB 固件 EEPROM 镜像 - 在没有专用 VLI EEPROM 1.4 及更高版本的主板版本中被忽略

| vl805.sig| vl805.bin 的 sha256 校验
|===

* 如果启动加载程序更新镜像名为 `pieeprom.upd` ，则 `recovery.bin` 将被重命名为`recovery.000` ，当更新完成时，系统将重新启动。由于 `recovery.bin` 不再存在，ROM从EEPROM加载最新更新的启动加载程序，并且操作系统正常启动。
* 如果启动加载程序更新镜像名为 `pieeprom.bin` ，则 `recovery.bin` 将在更新完成后停止。更新成功时，HDMI输出将为绿色，绿色LED快速闪烁。如果更新失败，HDMI输出将为红色，并通过LED显示 xref:configuration.adoc#led-warning-flash-codes[错误代码] 。
*  `.sig` 文件包含相应镜像文件的十六进制sha256校验，后续可能会添加其他字段。
* BCM2711 ROM不支持从大容量的USB或TFTP加载 `recovery.bin` 。相反，新版本的启动加载程序支持自我更新机制，其中启动加载程序能够自行刷新EEPROM。请参见 xref:raspberry-pi.adoc#raspberry-pi-4-bootloader-configuration[启动加载程序配置] 页面上的`ENABLE_SELF_UPDATE`。
* `rpi-eeprom-update` 服务会在启动时会自动删除临时EEPROM更新文件。

有关 `rpi-eeprom-update` 配置文件的更多信息，请参见 `rpi-eeprom-update -h`。

[[eeprom-write-protect]]
==== EEPROM 写保护

启动加载程序和 VLI EEPROMs 都支持硬件写保护。 有关如何在刷新EEPROM时启用此功能的更多信息，请参见 xref:raspberry-pi.adoc#eeprom_write_protect[eeprom_write_protect] 选项。