[[parallel-display-interface-dpi]]
== 并行显示接口 (DPI)

所有具有 24-Pin接头和CM的 Raspberry Pi 板上均提供高达24位并行 RGB 接口。该接口允许并行 RGB 显示器以 RGB24（8位红色、8位绿色和8位蓝色）或 RGB666（每种颜色 6 位）或 RGB565（5 位红色、6 位绿色和 5 位蓝色）连接到 Raspberry Pi GPIO。

此接口由 GPU 固件控制，用户可以通过特殊的config.txt参数并启用正确的 Linux 设备树覆盖进行编程。

[[gpio-pins]]
=== GPIO Pins

Raspberry Pi GPIO 的Bank0 上可选择的替代功能之一是 DPI（显示并行接口），其为一个简单的时钟并行接口（最多8位R、G和B;时钟、启用、hsync 和 vsync）。此接口可用作 GPIO Bank0 上的备用功能 2（ALT2）：

[cols=2]
|===
|GPIO |ALT2

|GPIO0
|PCLK

|GPIO1
|DE

|GPIO2
|LCD_VSYNC

|GPIO3
|LCD_HSYNC

|GPIO4
|DPI_D0

|GPIO5
|DPI_D1

|GPIO6
|DPI_D2

|GPIO7
|DPI_D3

|GPIO8
|DPI_D4

|GPIO9
|DPI_D5

|GPIO10
|DPI_D6

|GPIO11
|DPI_D7

|GPIO12
|DPI_D8

|GPIO13
|DPI_D9

|GPIO14
|DPI_D10

|GPIO15
|DPI_D11

|GPIO16
|DPI_D12

|GPIO17
|DPI_D13

|GPIO18
|DPI_D14

|GPIO19
|DPI_D15

|GPIO20
|DPI_D16

|GPIO21
|DPI_D17

|GPIO22
|DPI_D18

|GPIO23
|DPI_D19

|GPIO24
|DPI_D20

|GPIO25
|DPI_D21

|GPIO26
|DPI_D22

|GPIO27
|DPI_D23
|===

NOTE: 可以通过多种方式以565、666或24位模式在DPI输出引脚上呈现颜色值(参见下表和下文的  `dpi_output_format` 参数的 `output_format` 部分):

[cols="1,1,^1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"]
|===
.2+h|*Mode* .2+h|*RGB bits* 24+h|*GPIO*
h|*27* h|*26* h|*25* h|*24* h|*23* h|*22* h|*21* h|*20* h|*19* h|*18* h|*17* h|*16* h|*15* h|*14* h|*13* h|*12* h|*11* h|*10* h|*9* h|*8* h|*7* h|*6* h|*5* h|*4*

|1
{set:cellbgcolor:!}
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-
|-

|2
|565
|-
|-
|-
|-
|-
|-
|-
|-
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3

|3
{set:cellbgcolor:!}
|565
|-
|-
|-
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|-
{set:cellbgcolor:!}
|-
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|-
{set:cellbgcolor:!}
|-
|-
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3

|4
{set:cellbgcolor:!}
|565
|-
|-
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|-
{set:cellbgcolor:!}
|-
|-
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|-
{set:cellbgcolor:!}
|-
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3
|-
{set:cellbgcolor:!}

|5
|666
|-
|-
|-
|-
|-
|-
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|2
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3
|2

|6
{set:cellbgcolor:!}
|666
|-
|-
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|2
|-
{set:cellbgcolor:!}
|-
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|-
{set:cellbgcolor:!}
|-
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3
|2

|7
{set:cellbgcolor:!}
|888
|7
{set:cellbgcolor:#E20000}
|6
|5
|4
|3
|2
|1
|0
|7
{set:cellbgcolor:#05FF0B}
|6
|5
|4
|3
|2
|1
|0
|7
{set:cellbgcolor:#5D6CFF}
|6
|5
|4
|3
|2
|1
|0

|===
{set:cellbgcolor:!}

[[disable-other-gpio-peripherals]]
=== 禁用其他GPIO外围设备

请注意，必须禁用使用冲突的 GPIO 引脚的所有其他外设覆盖层。在 config.txt 中，注意注释掉或反转任何支持 I2C 或 SPI 的 dtparams：

----
dtparam=i2c_arm=off
dtparam=spi=off
----

[[controlling-output-format]]
=== 控制输出格式

输出格式（时钟、颜色格式、同步极性、启用）可以通过传递到从以下字段创建的config.txt中的 `dpi_output_format` 参数的幻数（无符号整数或前缀为 0x 的十六进制值）进行控制：

----
output_format          = (dpi_output_format >>  0) & 0xf;
rgb_order              = (dpi_output_format >>  4) & 0xf;

output_enable_mode     = (dpi_output_format >>  8) & 0x1;
invert_pixel_clock     = (dpi_output_format >>  9) & 0x1;

hsync_disable          = (dpi_output_format >> 12) & 0x1;
vsync_disable          = (dpi_output_format >> 13) & 0x1;
output_enable_disable  = (dpi_output_format >> 14) & 0x1;

hsync_polarity         = (dpi_output_format >> 16) & 0x1;
vsync_polarity         = (dpi_output_format >> 17) & 0x1;
output_enable_polarity = (dpi_output_format >> 18) & 0x1;

hsync_phase            = (dpi_output_format >> 20) & 0x1;
vsync_phase            = (dpi_output_format >> 21) & 0x1;
output_enable_phase    = (dpi_output_format >> 22) & 0x1;

output_format:
   1: DPI_OUTPUT_FORMAT_9BIT_666
   2: DPI_OUTPUT_FORMAT_16BIT_565_CFG1
   3: DPI_OUTPUT_FORMAT_16BIT_565_CFG2
   4: DPI_OUTPUT_FORMAT_16BIT_565_CFG3
   5: DPI_OUTPUT_FORMAT_18BIT_666_CFG1
   6: DPI_OUTPUT_FORMAT_18BIT_666_CFG2
   7: DPI_OUTPUT_FORMAT_24BIT_888

rgb_order:
   1: DPI_RGB_ORDER_RGB
   2: DPI_RGB_ORDER_BGR
   3: DPI_RGB_ORDER_GRB
   4: DPI_RGB_ORDER_BRG

output_enable_mode:
   0: DPI_OUTPUT_ENABLE_MODE_DATA_VALID
   1: DPI_OUTPUT_ENABLE_MODE_COMBINED_SYNCS

invert_pixel_clock:
   0: RGB Data changes on rising edge and is stable at falling edge
   1: RGB Data changes on falling edge and is stable at rising edge.

hsync/vsync/output_enable_polarity:
   0: default for HDMI mode
   1: inverted

hsync/vsync/oe phases:
   0: DPI_PHASE_POSEDGE
   1: DPI_PHASE_NEGEDGE
----

注意，单比特字段都充当 "反转默认行为"。

[[controlling-timings-and-resolutions]]
=== 控制计时和分辨率

在2018年8月或更高版本的固件中，以前用于设置DPI计时的 `hdmi_timings` config.txt 条目已被新的 `dpi_timings` 参数取代。如果 `dpi_timings` 参数不存在，系统将使用 `hdmi_timings` 参数来确保向后兼容性。如果两者都不存在并且请求自定义模式，则使用VGAp60的默认参数集。

 `dpi_group` 和 `dpi_mode` config.txt 参数用于设置预定模式(HDMI使用的DMT或CEA模式)，或者用户可以生成 https://forums.raspberrypi.com/viewtopic.php?f=29&t=24679[自定义模式] 。

如果设置自定义 DPI 模式，则在config.txt中使用：

----
dpi_group=2
dpi_mode=87
----

这将告知驱动程序使用DPI面板的自定义 `dpi_timings` (旧固件使用 `hdmi_timings`) 计时。

 `dpi_timings` 参数指定为一组以空格分隔的参数：

----
dpi_timings=<h_active_pixels> <h_sync_polarity> <h_front_porch> <h_sync_pulse> <h_back_porch> <v_active_lines> <v_sync_polarity> <v_front_porch> <v_sync_pulse> <v_back_porch> <v_sync_offset_a> <v_sync_offset_b> <pixel_rep> <frame_rate> <interlaced> <pixel_freq> <aspect_ratio>

<h_active_pixels> = horizontal pixels (width)
<h_sync_polarity> = invert hsync polarity
<h_front_porch>   = horizontal forward padding from DE active edge
<h_sync_pulse>    = hsync pulse width in pixel clocks
<h_back_porch>    = vertical back padding from DE active edge
<v_active_lines>  = vertical pixels height (lines)
<v_sync_polarity> = invert vsync polarity
<v_front_porch>   = vertical forward padding from DE active edge
<v_sync_pulse>    = vsync pulse width in pixel clocks
<v_back_porch>    = vertical back padding from DE active edge
<v_sync_offset_a> = leave at zero
<v_sync_offset_b> = leave at zero
<pixel_rep>       = leave at zero
<frame_rate>      = screen refresh rate in Hz
<interlaced>      = leave at zero
<pixel_freq>      = clock frequency (width*height*framerate)
<aspect_ratio>    = *

* The aspect ratio can be set to one of eight values (choose closest for your screen):

HDMI_ASPECT_4_3 = 1
HDMI_ASPECT_14_9 = 2
HDMI_ASPECT_16_9 = 3
HDMI_ASPECT_5_4 = 4
HDMI_ASPECT_16_10 = 5
HDMI_ASPECT_15_9 = 6
HDMI_ASPECT_21_9 = 7
HDMI_ASPECT_64_27 = 8
----

[[overlays]]
=== 覆盖

Linux 设备树覆盖用于将 GPIO 引脚切换到正确的模式（alt function 2）。如前所述，GPU 负责驱动 DPI 显示器。因此无 Linux 驱动程序;覆盖只是正确设置 GPIO alt 功能。

提供 '全脂' DPI覆盖 (dpi24.dtb) ，将28 个 GPIO 设置为 ALT2 模式，提供 *完整* 的 24 位色彩总线以及水平和垂直同步、使能和像素时钟。请注意，这使用所有Bank0的 GPIO 引脚。

提供第二个覆盖 (vga666.dtb) 用于在666模式下驱动VGA监视器信号，该模式无需时钟和DE引脚（GPIO 0和1），只需GPIO4-21来实现颜色（使用模式5）。

这些覆盖层相当琐碎的，用户可以编辑它们以创建自定义覆盖层，以启用特定用例所需的引脚。

[[example-config-txt-settings]]
===  `config.txt` 设置示例

[[gert-vga666-adaptor]]
==== Gert VGA666 适配器

此设置适用于 https://github.com/fenlogic/vga666[Gert VGA 适配器].

请注意，上述 GitHub 链接中的文档提供的说明可能过时了，建议使用以下设置。

----
dtoverlay=vga666
enable_dpi_lcd=1
display_default_lcd=1
dpi_group=2
dpi_mode=82
----

[[800x480-lcd-panel]]
==== 800x480 LCD 面板

NOTE: 这是使用Adafruit的  https://www.adafruit.com/products/2453[DPI 附加板] 800x480 LCD面板进行测试的。

----
dtoverlay=dpi24
overscan_left=0
overscan_right=0
overscan_top=0
overscan_bottom=0
framebuffer_width=800
framebuffer_height=480
enable_dpi_lcd=1
display_default_lcd=1
dpi_group=2
dpi_mode=87
dpi_output_format=0x6f005
dpi_timings=800 0 40 48 88 480 0 13 3 32 0 0 0 60 0 32000000 6
----
