[[frequency-management-and-thermal-control]]
== 频率管理和热控制

所有Raspberry Pi产品均具备一定程度的热管理，以避免在重负载下过热。SoC 有一个内部温度传感器，GPU 上的软件会轮询以确保温度不超过预定义的限制，所有器件的温度预设最大值均为 85°C。可以将其设置为较低的值，但不能设置为较高的值。当器件的温度值接近极限时，芯片上使用的各种频率（ARM、GPU）和电压均会降低。频率和电压降低后，减少了产生的热量，使温度得到控制。

当内核温度介于 80°C 和 85°C 之间时，将显示一个警告图标(显示红色半填充温度计)，并且 ARM 内核将逐渐被限制。如果温度达到 85°C，将显示一个完全填充的温度计的图标，并且 ARM 内核和 GPU 都将受到限制。有关图标的图像，请参见 xref:configuration.adoc#firmware-warning-icons[告警图标] 的页面以获取具体的图片。

为了提供更好的散热和增强散热能力， Raspberry Pi 3 Model B+的PCB技术已升级。除此之外，还引入了软温度限制，即当温度达到 85°C 的限制之前最大限度地延长设备可以“冲刺”的时间。 当达到软限制时，时钟速度从1.4GHz降低到1.2GHz，工作电压也会降低。这个操作降低了温度上升的速度：我们可以用1.4GHz 的短时间换取1.2GHz 的较长时间。默认情况下，软限制被设置为 60°C，可以通过 xref:config_txt.adoc#overclocking-options[config.txt] 中的`temp_soft_limit` 设置进行更改。

Raspberry Pi 4 Model B继续采用与Raspberry Pi 3 Model B +相同的PCB技术，有助于产品更好的散热，且 *暂时未定义软限制* 。


[[using-dvfs]]
=== 使用 DVFS

NOTE: DVFS的讨论 *仅* 适用于 Raspberry Pi 4 Model B、Raspberry Pi 400和CM4。

Raspberry Pi 4设备实现动态电压和频率缩放 （DVFS），此技术允许Raspberry Pi 4设备在较低的温度下运行，同时提供相同的性能。

SoC 内部的各种时钟（例如 ARM、内核、V3D、ISP、H264、HEVC）由固件监控，当它们未全速运行时，提供给时钟驱动芯片的特定部分的电压相对于全速而言有所降低。实际上，仅提供足够的电压来保持模块以其运行的特定速度正常运行。这可能导致 SoC 使用的功率降低，从而减少产生的总热量。

由于运行欠压可能会导致系统稳定性问题，尤其是在使用欠压固定时钟外设(如PCIe)时。因此提供三种可用的DVFS模式，可在 `/boot/config.txt` 中使用以下属性进行配置。大多数系统应使用 `dvfs=3`，无头系统可能受益于 `dvfs=1` 的小功率降低，但存在PCIe稳定性问题的风险。

|===
| property=取值 | 描述

| dvfs=1
| 允许欠压

| dvfs=2
| 默认工作频率的固定电压

| dvfs=3
| 按需调整电压以实现超频(默认)。如果在 `config.txt` 中指定了 `over_voltage` ，则动态电压调整被禁用，导致系统恢复到 `dvfs=2` 。
|===

此外，还使用了分级CPU调速器来对ARM内核频率进行更精确的控制(表示DVFS更有效)。现在的步进为1500MHz、1000MHz、750MHz 和 600MHz。当SoC受到限制时，这些步进也可以提供帮助，并且意味着一直限制回600MHz的可能性要小得多，从而全面提高满载性能。

默认的CPU调控器是 `ondemand` ，可以使用 `cpufreq-set` 命令(来自 `cpufrequtils` 包)手动更改调控器，以减少空闲功耗:

[,bash]
----
 sudo apt install cpufrequtils
 sudo cpufreq-set -g powersave
----

[[measuring-temperatures]]
=== 测试温度

由于 Raspberry Pi 系列上使用的 SoC 架构以及在 Raspberry Pi OS 发行版中使用上游温度监控代码，故基于Linux的温度测量可能不准确。但是，该 `vcgencmd` 命令在直接与 GPU 通信时可以准确、即时地读取当前SoC温度：

[,bash]
----
 vcgencmd measure_temp
----

[[adding-heatsinks]]
=== Adding Heatsinks

虽然无需使用散热器来防止SoC过热损坏所(热节流机制可以处理该问题)，但如果你希望减少发生的热节流量，散热器或小风扇会有所帮助。根据具体情况，垂直安装 Raspberry Pi 也有助于散热，因为这样做可以改善空气流通。
