[[gpio]]
== 通用 I/O (GPIO)

通用 I/O (GPIO) 引脚可配置为通用输入、通用输出或多达六种特殊备用设置之一，其功能取决于引脚。

BCM2835 上有3个 GPIO组。3个组都有自己的VDD输入引脚。在Raspberry Pi上，所有GPIO组均使用3.3V供电。

WARNING: 将 GPIO 连接到高于 3.3V 的电压可能会破坏 SoC 内的 GPIO 模块。

Raspberry Pi的 P1 接头上提供了 Bank 0 中引脚选择。

[[gpio-pads]]
=== GPIO 焊盘

BCM2835封装上的GPIO连接有时在外设数据手册中称为 "焊盘" ，这是一个半导体设计术语，意思是 '芯片与外界的连接'。

焊盘是可配置的CMOS输出驱动器/输入缓冲器。基于寄存器的控制设置可用于：

* 内部上拉/下拉使能/禁用
* 输出 xref:raspberry-pi.adoc#gpio-pads-control[驱动强度]
* 输入施密特触发器滤波

[[power-on-states]]
==== 开机状态

所有 GPIO 引脚在上电复位时恢复为通用输入，且应用默认拉取状态，ARM 外设datasheet中的备用功能表对此进行了详细说明。大多数 GPIO 都应用了默认拉取。

[[interrupts]]
=== 中断

每个 GPIO 引脚在配置为通用输入时，都可以配置为 ARM 的中断源。可配置多个中断生成源：

* 电平敏感 (高/低)
* 上升沿/下降沿
* 异步上升沿/下降沿

电平中断保持中断状态，直到系统软件清除电平 (例如，通过为生成中断的附加外设提供服务)。

正常的上升沿/下降沿检测在检测中内置了少量同步。在系统时钟频率下，对引脚进行采样，产生中断的标准是3周期窗口内的稳定转换，即记录 '1 0 0' 或 '0 1 1'。异步检测绕过此同步，以便能够检测非常窄的事件。

[[alternative-functions]]
=== 替代功能

几乎所有的GPIO引脚都有替代功能。 可以配置 SoC 内部的外设模块出现在1组 GPIO 引脚中的一个或多个上，例如，I2C 总线可以配置为至少3个独立的位置。当引脚配置为备用功能时， xref:raspberry-pi.adoc#gpio-pads-control[焊盘控制]（ 如驱动强度或施密特滤波）仍然适用。

[[voltage-specifications]]
=== 电压规格

下表给出了基于 BCM2835、BCM2836、BCM2837 和RP3A0 的产品（例如 Raspberry Pi Zero 或 Raspberry Pi 3+）的 GPIO 引脚的各种电压规格。有关CM的信息，请参见  xref:compute-module.adoc#datasheets-and-schematics[相关的datasheet]。

|===
| 符号 | 参数 | 条件 | 最小值 | 典型值 | 最大值 | 单位

| V~IL~
| 输入低电压
| -
| -
| -
| 0.9
| V

| V~IH~
| 输入高电压^a^
| -
| 1.6
| -
| -
| V

| I~IL~
| 输入漏电流
| TA = +85◦C
| -
| -
| 5
| µA

| C~IN~
| 输入电容
| -
| -
| 5
| -
| pF

| V~OL~
| 输出低压^b^
| IOL = -2mA
| -
| -
| 0.14
| V

| V~OH~
| 输出高压^b^
| IOH = 2mA
| 3.0
| -
| -
| V

| I~OL~
| 输出低电流^c^
| VO = 0.4V
| 18
| -
| -
| mA

| I~OH~
| 输出高电流^c^
| VO = 2.3V
| 17
| -
| -
| mA

| R~PU~
| 上拉电阻
| -
| 50
| -
| 65
| kΩ

| R~PD~
| 下拉电阻
| -
| 50
| -
| 65
| kΩ
|===

^a^ 滞后启用 +
^b^ 默认驱动强度 (8mA) +
^c^ 最大驱动强度 (16mA)

下表给出了基于 BCM2711 的产品 (例如Raspberry Pi 4 和Raspberry Pi 400)的 GPIO 引脚的各种电压规格。有关处理器模块（CM）的信息，请参见 xref:compute-module.adoc#datasheets-and-schematics[相关的datasheet]。

|===
| 符号 | 参数 | 条件 | 最小值 | 典型值 | 最大值 | 单位

| V~IL~
| 输入低电压
| -
| -
| -
| 0.8
| V

| V~IH~
| 输入高电压^a^
| -
| 2.0
| -
| -
| V

| I~IL~
| 输入漏电流
| TA = +85◦C
| -
| -
| 10
| µA

| V~OL~
| 输出低电压^b^
| IOL = -4mA
| -
| -
| 0.4
| V

| V~OH~
| 输出高电压^b^
| IOH = 4mA
| 2.6
| -
| -
| V

| I~OL~
| 输出低电流^c^
| VO = 0.4V
| 7
| -
| -
| mA

| I~OH~
| 输出高电流^c^
| VO = 2.6V
| 7
| -
| -
| mA

| R~PU~
| 上拉电阻
| -
| 33
| -
| 73
| kΩ

| R~PD~
| 下拉电阻
| -
| 33
| -
| 73
| kΩ
|===

^a^ 滞后启用 +
^b^ 默认驱动强度 (4mA) +
^c^ 最大驱动强度 (8mA)
