[[otp-register-and-bit-definitions]]
== OTP 寄存器和位定义

Raspberry Pi系列使用的所有SoC都包含一个内置的一次性可编程（OTP）内存块。

尽管只有少数位置具有工厂编程的数据，它的长度为 66 个 32 位值。

显示 OTP 内容的 `vcgencmd` 为:

----
vcgencmd otp_dump
----

[[otp-registersl]]
=== OTP 寄存器

该列表包含登记册上的公开信息。如果此处未定义寄存器或位，则它不是公共的。

17 -- 启动模式寄存器

* Bit 1: 将振荡器频率设置为 19.2MHz
* Bit 3: 使能 SDIO 引脚上的上拉
* Bit 19: 启用 GPIO 启动模式
* Bit 20: 设置组以检查 GPIO 启动模式
* Bit 21: 使能从 SD 卡启动
* Bit 22: 设置启动的组
* Bit 28: 使能 USB 设备启动
* Bit 29: 使能 USB 主机启动（以太网和大容量存储）

NOTE: 在 BCM2711 上，启动模式由 xref:raspberry-pi.adoc#raspberry-pi-4-bootloader-configuration[启动加载程序 EEPROM 配置] 而不是 OTP 定义。

18 -- 启动模式寄存器的副本 +
28 -- 序列号 +
29 -- ~(序列号) +
30 -- xref:raspberry-pi.adoc#raspberry-pi-revision-codes[修订代码] ^1^ +
33 -- 扩展板修订 - 含义取决于主板型号。 +
这可以通过 `/proc/device-tree/chosen/rpi-boardrev-ext` 中的设备树获得，出于测试目的，可以通过在 `config.txt` 中的 `board_rev_ext` 来临时覆盖该OTP值。

* Compute Module 4
 ** Bit 30: 处理器模块（CM）是否安装了 WiFi 模块
  *** 0 - WiFi
  *** 1 - 无 WiFi
 ** Bit 31: 处理器模块（CM）是否安装了 EMMC 模块
  *** 0 - EMMC
  *** 1 - 无 EMMC (Lite版)
* Raspberry Pi 400
 ** Bits 0-7:  https://github.com/raspberrypi-ui/piwiz[piwiz] 使用的默认键盘国家码

36-43 -- xref:raspberry-pi.adoc#industrial-use-of-the-raspberry-pi[客户 OTP 值] +
45 -- MPG2 解码密钥 +
46 -- WVC1 解码密钥 +
47-54 -- 用于安全启动的 RSA 公钥的 SHA256 +
55    -- 安全启动标志（保留供启动加载程序使用） +
56-63 -- 256 位设备专用私钥 +
64-65 --  MAC 地址; 如果设置，系统将优先使用此地址，而不是基于序列号自动生成地址 +
66 -- 高级启动寄存器 (不是 BCM2711)

* Bits 0-6: ETH_CLK输出引脚的 GPIO
* Bit 7: 启用ETH_CLK输出
* Bits 8-14: LAN_RUN输出引脚的 GPIO
* Bit 15: 启用LAN_RUN输出
* Bit 24: 扩展 USB HUB超时参数
* Bit 25: ETH_CLK频率:
 ** 0 - 25MHz
 ** 1 - 24MHz

^1^还包含用于禁用过压、OTP 编程和 OTP 读取的位。
