[[industrial-use-of-the-raspberry-pi]]
== Raspberry Pi 的工业用途

Raspberry Pi通常用作其他产品的一部分。本文档介绍了一些可用于使用 Raspberry Pi 其他功能的额外工具。

[[one-time-programmable-settings]]
=== 一次性可编程设置

可以使用许多 OTP 值。要查看所有 xref:raspberry-pi.adoc#otp-register-and-bit-definitions[OTP 值] 的列表，你可以使用：

[,bash]
----
vcgencmd otp_dump
----

这个转储中的一些有用定义：

* 28 - 序列号
* 29 - 序列号的补码
* 30 - 修订吗

此外从 36 到 43（含），有8行 32 位可供客户使用

要对这些位进行编程，你需要使用 vcmailbox。 这是固件的 Linux 驱动程序接口，它将处理行的编程。为此，请参见 https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface[文档] 和 vcmailbox https://github.com/raspberrypi/userland/blob/master/host_applications/linux/apps/vcmailbox/vcmailbox.c[示例应用程序]。

vcmailbox应用程序可以直接从Raspberry Pi OS上的命令行使用。一个用法示例如下：

[,bash]
----
vcmailbox 0x00010004 8 8 0 0
----

这将返回类似以下内容：

----
0x00000020 0x80000000 0x00010004 0x00000008 0x800000008 0xnnnnnnnn 0x00000000 0x00000000
----

上面使用 https://github.com/raspberrypi/firmware/wiki/Mailbox-property-interface[邮箱属性接口] `GET_BOARD_SERIAL` ，请求大小为 8 字节，响应大小为 8 字节（为请求 0、0 发送两个整数）。对此的响应将是两个整数（0x00000020 和 0x80000000），后跟标签代码、请求长度、响应长度（将第 31 位设置表示它是响应），然后是 64 位序列号（其中 MS 32 位始终为 0）。

[[write-and-read-customer-otp-values]]
=== 写入和读取客户OTP值

WARNING: OTP 值是一次性可编程的，如果已经从 0 更改为 1，此操作无法撤销。

要设置客户 OTP 值，你需要使用 `SET_CUSTOMER_OTP` (0x38021) 标签，如下所示：

[,bash]
----
vcmailbox 0x00038021 [8 + number * 4] [8 + number * 4] [start_num] [number] [value] [value] [value] ...
----

* `start_num` = 从 0-7 编程的第一行
* `number` = 要编程的行数
* `value` = 要编程的每个值

因此，要将 OTP 客户行 4、5 和 6 分别编程为 0x11111111, 0x22222222, 0x33333333 ，你将使用：

[,bash]
----
vcmailbox 0x00038021 20 20 4 3 0x11111111 0x22222222 0x33333333
----

然后，这将对第 40、41 和 42 行进行编程。

要读回这些值，你可以使用：

[,bash]
----
vcmailbox 0x00030021 20 20 4 3 0 0 0
----

应显示：

----
0x0000002c 0x80000000 0x00030021 0x00000014 0x80000014 0x00000000 0x00000003 0x11111111 0x22222222 0x33333333
----

如果要将此功能集成到自己的代码中，应该能够使用 vcmailbox.c 代码作为示例来实现此目的。

[[locking-the-otp-changes]]
===锁定 OTP 更改

可以锁定 OTP 更改以避免再次编辑它们。这可以使用带有 OTP 写入邮箱的特殊参数来完成：

[,bash]
----
vcmailbox 0x00038021 8 8 0xffffffff 0xaffe0000
----

锁定后，无法再更改客户 OTP 值。请注意，此锁定操作是不可逆的。

[[making-customer-otp-bits-unreadable]]
=== 使客户OTP位不可读

完全可以防止客户的OTP位被读取。这可以使用带有 OTP 写入邮箱的特殊参数来完成：

[,bash]
----
vcmailbox 0x00038021 8 8 0xffffffff 0xaffebabe
----

此操作对于绝大多数用户来说是不太可能有用，并且是不可逆的。

[[device-specific-private-key]]
=== 设备专用密钥
8行 OTP（256 位）可用作特定于设备的私钥，旨在支持文件系统加密。

可以使用与管理客户OTP行类似的vcmailbox命令对这些行进行编程和读取。如果不需要安全启动/文件系统加密，则设备私钥行可用于存储通用信息。

* 只能通过 `vcmailbox` 命令读取设备私钥行，该命令需要访问 `/dev/vcio` ，该权限仅限于Raspberry Pi操作系统上的 `视频` 组。
* Raspberry Pi计算机无硬件保护的密钥存储。建议将此功能与 https://github.com/raspberrypi/usbboot/blob/master/secure-boot-example/README.md[安全启动] 结合使用，以限制对此数据的访问。
* Raspberry Pi OS不支持加密的根文件系统。

有关开源磁盘加密的详细信息，请参见 https://gitlab.com/cryptsetup/cryptsetup[cryptsetup] 。

[[key-programming-script-rpi-otp-private-key]]
==== 关键编程脚本 `rpi-otp-private-key`
 https://github.com/raspberrypi/usbboot/blob/master/tools/rpi-otp-private-key[rpi-otp-private-key] 脚本包装了设备私 `vcmailbox` API，以便更轻松地读取/写入与 OpenSSL 相同的格式密钥。

将密钥读取为 64 字节十六进制数字
[,bash]
----
rpi-otp-private-key
----

输出示例
----
f8dbc7b0a4fcfb1d706e298ac9d0485c2226ce8df7f7596ac77337bd09fbe160
----

将随机生成的 64 字节数字写入设备私钥。 +
**Warning: 此操作无法撤销。 **
[,bash]
----
# rpi-otp-private-key -w $(openssl rand -hex 32)
----

[[mailbox-api-for-readingwriting-the-key]]
==== 用于读取/写入密钥的邮箱 API
读取所有行。
[,bash]
----
vcmailbox 0x00030081 40 40 0 8 0 0 0 0 0 0 0 0
----

输出示例
----
0x00000040 0x80000000 0x00030081 0x00000028 0x80000028 0x00000000 0x00000008 0xf8dbc7b0 0xa4fcfb1d 0x706e298a 0xc9d0485c 0x2226ce8d 0xf7f7596a 0xc77337bd 0x09fbe160 0x00000000
----

写入所有行（将末尾的八个0替换为关键数据）
[,bash]
----
vcmailbox 0x00038081 40 40 0 8 0 0 0 0 0 0 0 0
----

写入上一示例中所示的密钥
----
vcmailbox 0x38081 40 40 0 8 0xf8dbc7b0 0xa4fcfb1d 0x706e298a 0xc9d0485c 0x2226ce8d 0xf7f7596a 0xc77337bd 0x09fbe160
----
