[[raspberry-pi-revision-codes]]
== Raspberry Pi 修订代码

每个不同的Raspberry Pi型号修订版都有一个唯一的修订代码。你可以通过运行以下命令查找Raspberry Pi的修订代码：

[,bash]
----
cat /proc/cpuinfo
----

最后三行显示硬件类型、修订代码和 Raspberry Pi 的唯一序列号。例如：

----
Hardware    : BCM2835
Revision    : a02082
Serial      : 00000000765fc593
----

NOTE: 从4.9版本内核开始，所有的Raspberry Pi计算机都报告 `BCM2835`，即使是BCM2836、BCM2837、BCM2711处理器的计算机。你不应该使用此字符串来检测处理器。使用以下信息或 `cat /sys/firmware/devicetree/base/model` 对修订代码进行解码。

[[old-style-revision-codes]]
=== 旧式修订代码

第一组Raspberry Pi型号顺序的十六进制修订代码为 `0002` ~ `0015`:

|===
| 代码 | 型号 | 修订 | RAM | 制造者

| 0002
| B
| 1.0
| 256MB
| Egoman

| 0003
| B
| 1.0
| 256MB
| Egoman

| 0004
| B
| 2.0
| 256MB
| Sony UK

| 0005
| B
| 2.0
| 256MB
| Qisda

| 0006
| B
| 2.0
| 256MB
| Egoman

| 0007
| A
| 2.0
| 256MB
| Egoman

| 0008
| A
| 2.0
| 256MB
| Sony UK

| 0009
| A
| 2.0
| 256MB
| Qisda

| 000d
| B
| 2.0
| 512MB
| Egoman

| 000e
| B
| 2.0
| 512MB
| Sony UK

| 000f
| B
| 2.0
| 512MB
| Egoman

| 0010
| B+
| 1.2
| 512MB
| Sony UK

| 0011
| CM1
| 1.0
| 512MB
| Sony UK

| 0012
| A+
| 1.1
| 256MB
| Sony UK

| 0013
| B+
| 1.2
| 512MB
| Embest

| 0014
| CM1
| 1.0
| 512MB
| Embest

| 0015
| A+
| 1.1
| 256MB/512MB
| Embest
|===

[[new-style-revision-codes]]
=== 新型修订代码

随着Raspberry Pi 2的推出，引入了新的修订代码。十六进制代码的每一位不是连续的，而是代表有关修订的一条信息：

----
NOQuuuWuFMMMCCCCPPPPTTTTTTTTRRRR
----

|===
| 部件 | 含义 | 选项

| N (bit 31)
| 过压
| 0: 允许过压

|
|
| 1: 不允许过压

| O (bit 30)
| OTP编程^1^
| 0: 允许 OTP 编程

|
|
| 1: 不允许 OTP 编程

| Q (bit 29)
| OTP 读取^1^
| 0: 允许 OTP 读取

|
|
| 1: 不允许 OTP 读取

| uuu (bits 26-28)
| 闲置
| 闲置

| W (bit 25)
| 保修位^2^
| 0: 保修完好无损

|
|
| 1: 保修因 xref:config_txt.adoc#overclocking-options[超频] 而失效

| u (bit 24)
| 闲置
| 闲置

| F (bit 23)
| 新标志
| 1: 新型修订

|
|
| 0: 旧式修订

| MMM (bits 20-22)
| 内存大小
| 0: 256MB

|
|
| 1: 512MB

|
|
| 2: 1GB

|
|
| 3: 2GB

|
|
| 4: 4GB

|
|
| 5: 8GB

| CCCC (bits 16-19)
| 制造者
| 0: Sony UK

|
|
| 1: Egoman

|
|
| 2: Embest

|
|
| 3: Sony Japan

|
|
| 4: Embest

|
|
| 5: Stadium

| PPPP (bits 12-15)
| 处理器
| 0: BCM2835

|
|
| 1: BCM2836

|
|
| 2: BCM2837

|
|
| 3: BCM2711

| TTTTTTTT (bits 4-11)
| 类型
| 0: A

|
|
| 1: B

|
|
| 2: A+

|
|
| 3: B+

|
|
| 4: 2B

|
|
| 5: Alpha (early prototype)

|
|
| 6: CM1

|
|
| 8: 3B

|
|
| 9: Zero

|
|
| a: CM3

|
|
| c: Zero W

|
|
| d: 3B+

|
|
| e: 3A+

|
|
| f: 仅限内部使用

|
|
| 10: CM3+

|
|
| 11: 4B

|
|
| 12: Zero 2 W

|
|
| 13: 400

|
|
| 14: CM4

|
|
| 15: CM4S

| RRRR (bits 0-3)
| 修订
| 0、1和2 等
|===

^1^ 有关 xref:raspberry-pi.adoc#otp-register-and-bit-definitions[OTP位编程]的信息。

^2^ 保修位永远不会在Raspberry Pi 4上设置。

[[new-style-revision-codes-in-use]]
=== 正在使用的新型修订代码

NOTE: 此列表并不详尽 - 可能有一些正在使用的代码不在此表中。有关使用修订代码识别主板的最佳实践，请参见下一节。

|===
| 代码 | 型号 | 修订 | RAM | 制造者

| 900021
| A+
| 1.1
| 512MB
| Sony UK

| 900032
| B+
| 1.2
| 512MB
| Sony UK

| 900092
| Zero
| 1.2
| 512MB
| Sony UK

| 900093
| Zero
| 1.3
| 512MB
| Sony UK

| 9000c1
| Zero W
| 1.1
| 512MB
| Sony UK

| 9020e0
| 3A+
| 1.0
| 512MB
| Sony UK

| 920092
| Zero
| 1.2
| 512MB
| Embest

| 920093
| Zero
| 1.3
| 512MB
| Embest

| 900061
| CM1
| 1.1
| 512MB
| Sony UK

| a01040
| 2B
| 1.0
| 1GB
| Sony UK

| a01041
| 2B
| 1.1
| 1GB
| Sony UK

| a02082
| 3B
| 1.2
| 1GB
| Sony UK

| a020a0
| CM3
| 1.0
| 1GB
| Sony UK

| a020d3
| 3B+
| 1.3
| 1GB
| Sony UK

| a02042
| 2B (with BCM2837)
| 1.2
| 1GB
| Sony UK

| a21041
| 2B
| 1.1
| 1GB
| Embest

| a22042
| 2B (with BCM2837)
| 1.2
| 1GB
| Embest

| a22082
| 3B
| 1.2
| 1GB
| Embest

| a220a0
| CM3
| 1.0
| 1GB
| Embest

| a32082
| 3B
| 1.2
| 1GB
| Sony Japan

| a52082
| 3B
| 1.2
| 1GB
| Stadium

| a22083
| 3B
| 1.3
| 1GB
| Embest

| a02100
| CM3+
| 1.0
| 1GB
| Sony UK

| a03111
| 4B
| 1.1
| 1GB
| Sony UK

| b03111
| 4B
| 1.1
| 2GB
| Sony UK

| b03112
| 4B
| 1.2
| 2GB
| Sony UK

| b03114
| 4B
| 1.4
| 2GB
| Sony UK

| b03115
| 4B
| 1.5
| 2GB
| Sony UK

| c03111
| 4B
| 1.1
| 4GB
| Sony UK

| c03112
| 4B
| 1.2
| 4GB
| Sony UK

| c03114
| 4B
| 1.4
| 4GB
| Sony UK

| c03115
| 4B
| 1.5
| 4GB
| Sony UK

| d03114
| 4B
| 1.4
| 8GB
| Sony UK

| d03115
| 4B
| 1.5
| 8GB
| Sony UK

| c03130
| Pi 400
| 1.0
| 4GB
| Sony UK

| a03140
| CM4
| 1.0
| 1GB
| Sony UK

| b03140
| CM4
| 1.0
| 2GB
| Sony UK

| c03140
| CM4
| 1.0
| 4GB
| Sony UK

| d03140
| CM4
| 1.0
| 8GB
| Sony UK

| 902120
| Zero 2 W
| 1.0
| 512MB
| Sony UK
|===

[[using-revision-codes-for-board-identification]]
=== 使用修订代码进行电路板识别

通过命令行我们可以使用以下命令来获取电路板的修订代码：

[source, bash]
----
$cat /proc/cpuinfo | grep Revision
Revision      : c03111
----

在上面的示例中，我们有1个十六进制版本代码 `c03111`。将其转换为二进制，我们得到 `0 0 0 000 0 0 1 100 0000 0011 00010001 0001`。根据上表，通过插入空格以显示修订代码各部分之间的边界。

从最低位开始，底部四位 (0-3) 是主板的修订号，因此该板的修订号为 1。接下来的8位 (4-11) 是主板类型，本例中为二进制 `00010001`，十六进制 `11`，因此这是一个Raspberry Pi 4B。使用相同的操作，我们可以确定处理器是BCM2711，主板是由Sony UK制造的，并且具有4GB的RAM。

[[getting-the-revision-code-in-your-program]]
==== 获取程序中的修订代码

由于编程语言太多无法展示所有语言的示例，但是这里有2个 `C` 语言和 `Python`的简单例子。这2个示例都使用一个系统调用来运行一个bash命令，该命令获取 `cpuinfo` 并将结果通过管道传递给 `awk` ，以恢复所需的修订代码。然后，他们使用位操作从代码中提取 `New`、 `Model`、 和 `Memory` 字段。


[source, c, linenums]
----
#include <stdio.h>
#include <stdlib.h>

int main( int argc, char *argv[] )
{
  FILE *fp;
  char revcode[32];

  fp = popen("cat /proc/cpuinfo | awk '/Revision/ {print $3}'", "r");
  if (fp == NULL)
    exit(1);
  fgets(revcode, sizeof(revcode), fp);
  pclose(fp);

  int code = strtol(revcode, NULL, 16);
  int new = (code >> 23) & 0x1;
  int model = (code >> 4) & 0xff;
  int mem = (code >> 20) & 0x7;

  if (new && model == 0x11 && mem >= 3)  // Note, 3 in the mem field is 2GB
     printf("We are a 4B with at least 2GB of RAM!\n" );

  return 0;
}
----

在 Python 中也是如此：

[source, python, linenums]
----
import subprocess

cmd = "cat /proc/cpuinfo | awk '/Revision/ {print $3}'"
revcode = subprocess.check_output(cmd, shell=True)

code = int(revcode, 16)  
new = (code >> 23) & 0x1
model = (code >> 4) & 0xff
mem = (code >> 20) & 0x7

if new and model == 0x11 and mem >= 3 : # Note, 3 in the mem field is 2GB
    print("We are a 4B with at least 2GB RAM!")
----

[[best-practice-for-revision-code-usage]]
==== 修订代码使用的最佳实践

Raspberry Pi 建议不要将修订代码作为一个整体 (`c03111`) 使用，以避免在创建新的板修订版时出现问题。例如，可以考虑在程序中列出受支持的修订代码，并将检测到的代码与列表进行比较，以确定是否允许程序运行。但是当新的主板版本出现或生产地点发生变化时时，则这种机制就会被打破，每个修订版都会创建一个不在程序列表中的新修订代码。你的程序现在将拒绝无法识别的代码，并且可能会中止，即使相同板类型的修订始终向后兼容。你需要发布程序的新版本，并将特定修订版添加到列表中，这可能会造成维护负担。

同样，使用修订代码来指示程序支持的模型可能会产生问题。如果你的程序只计划在具有 2GB 或更多 RAM 的设备上运行，则一种简单的方法是查看具有 2GB 或更多 RAM 的型号的修订代码列表，并将该列表构建到你的程序中。但是一旦发布新的主板修订版，或者如果主板在不同的地点制造，这种情况就会中断。

更好的机制是仅使用板类型字段（3A、4B 等）来确定程序支持的模型;或者可能只是内存量字段。所以将支持任何Raspberry Pi 4B，无论其主板版本代码如何，因为这始终有效。或者你可能希望将程序限制为具有 2GB 或更多 RAM 的设备。只需查看这两个字段即可确定是否允许程序运行。

上一节中的示例使用建议的方法。他们从修订代码中提取主板类型和内存大小，并使用它们来确定其是否是具有 2GB 或更多 RAM 的 Raspberry Pi 4B。

NOTE: 在检查任何其他字段之前，你应该始终检查位 23（即 'New' 标志） ，以确保修订代码是新版本。