[[spi-overview]]
== 串行外设接口 (SPI)

Raspberry Pi计算机配备了较多的 https://en.wikipedia.org/wiki/Serial_Peripheral_Interface_Bus[SPI] 总线。SPI可用于连接各种外设 - 显示器、网络控制器（以太网，CAN总线）、UART等。这些外设需要由内核设备驱动程序支持，但 `spidev` API 允许用户空间驱动程序以多种语言编写。

[[spi-hardware]]
=== SPI 硬件

Raspberry Pi Zero 1、Raspberry Pi Zero 2和Raspberry Pi Zero 3分别包含3个SPI控制器：

* SPI0具有两个硬件芯片选择，其支持在所有Raspberry Pi的接头上使用;还具有一个仅支持在CM上使用的备用映射。
* SPI1具有3个硬件芯片选择，适用于除原始Raspberry Pi 1 Model A和Model B之外的所有Raspberry Pi型号。
* SPI2具有三个硬件芯片选择，仅适用于CM1、CM3和CM3+。

Raspberry Pi 4、Raspberry Pi 400和CM4分别具有4个额外的SPI总线：SPI3~SPI6，每个总线均具有2个硬件芯片选择。这些额外的 SPI 总线可通过一些 GPIO 引脚上的替代功能分配来适用 - 请参见 https://datasheets.raspberrypi.com/bcm2711/bcm2711-peripherals.pdf[BCM2711 ARM 外设] datasheet。

Chapter 10 in the https://datasheets.raspberrypi.com/bcm2835/bcm2835-peripherals.pdf[BCM2835 ARM 外设] datasheet 中的第10章介绍了主控制器，第 2.3 章介绍了辅助控制器。

[[pingpio-mappings]]
==== 引脚/GPIO 映射

[[spi0]]
===== SPI0

[cols="1,1,1,1"]
|===
| SPI 功能
| 引脚
| Broadcom 引脚名称
| Broadcom 引脚功能

| MOSI
| 19
| GPIO10
| SPI0_MOSI

| MISO
| 21
| GPIO09
| SPI0_MISO

| SCLK
| 23
| GPIO11
| SPI0_SCLK

| CE0
| 24
| GPIO08
| SPI0_CE0_N

| CE1
| 26
| GPIO07
| SPI0_CE1_N
|===

[[spi0-alternate-mapping-compute-modules-only-except-cm4]]
===== SPI0 备用映射（仅限处理器模块（CM）系列其中CM4除外）

[cols="1,1,1"]
|===
| SPI 功能
| Broadcom 引脚名称
| Broadcom 引脚功能

| MOSI
| GPIO38
| SPI0_MOSI

| MISO
| GPIO37
| SPI0_MISO

| SCLK
| GPIO39
| SPI0_SCLK

| CE0
| GPIO36
| SPI0_CE0_N

| CE1
| GPIO35
| SPI0_CE1_N
|===

[[spi1]]
===== SPI1

[cols="1,1,1,1"]
|===
| SPI 功能
| 针脚
| Broadcom 引脚名称
| Broadcom 引脚功能

| MOSI
| 38
| GPIO20
| SPI1_MOSI

| MISO
| 35
| GPIO19
| SPI1_MISO

| SCLK
| 40
| GPIO21
| SPI1_SCLK

| CE0
| 12
| GPIO18
| SPI1_CE0_N

| CE1
| 11
| GPIO17
| SPI1_CE1_N

| CE2
| 36
| GPIO16
| SPI1_CE2_N
|===

[[spi2-compute-modules-only-except-cm4]]
===== SPI2 (仅限处理器模块（CM）系列其中CM4除外)

[cols="1,1,1"]
|===
| SPI 功能
| Broadcom 引脚名称
| Broadcom 引脚功能

| MOSI
| GPIO41
| SPI2_MOSI

| MISO
| GPIO40
| SPI2_MISO

| SCLK
| GPIO42
| SPI2_SCLK

| CE0
| GPIO43
| SPI2_CE0_N

| CE1
| GPIO44
| SPI2_CE1_N

| CE2
| GPIO45
| SPI2_CE2_N
|===

[[spi3-bcm2711-only]]
===== SPI3 (仅限 BCM2711)

[cols="1,1,1,1"]
|===
| SPI 功能
| 引脚
| Broadcom 引脚名称
| Broadcom 引脚功能

| MOSI
| 03
| GPIO02
| SPI3_MOSI

| MISO
| 28
| GPIO01
| SPI3_MISO

| SCLK
| 05
| GPIO03
| SPI3_SCLK

| CE0
| 27
| GPIO00
| SPI3_CE0_N

| CE1
| 18
| GPIO24
| SPI3_CE1_N
|===

[[spi4-bcm2711-only]]
===== SPI4 (仅限BCM2711)

[cols="1,1,1,1"]
|===
| SPI 功能
| 引脚
| Broadcom 引脚名称
| Broadcom 引脚定义

| MOSI
| 31
| GPIO06
| SPI4_MOSI

| MISO
| 29
| GPIO05
| SPI4_MISO

| SCLK
| 26
| GPIO07
| SPI4_SCLK

| CE0 
| 07
| GPIO04
| SPI4_CE0_N

| CE1
| 22
| GPIO25
| SPI4_CE1_N
|===

[[spi5-bcm2711-only]]
===== SPI5 (仅限 BCM2711)

[cols="1,1,1,1"]
|===
| SPI 功能
| 引脚
| Broadcom 引脚名称
| Broadcom 引脚功能

| MOSI
| 08
| GPIO14
| SPI5_MOSI

| MISO
| 33
| GPIO13
| SPI5_MISO

| SCLK
| 10
| GPIO15
| SPI5_SCLK

| CE0
| 32
| GPIO12
| SPI5_CE0_N

| CE1
| 37
| GPIO26
| SPI5_CE1_N
|===

[[spi6-bcm2711-only]]
===== SPI6 (仅限 BCM2711)

[cols="1,1,1,1"]
|===
| SPI 功能
| 引脚
| Broadcom 引脚名称
| Broadcom 引脚功能

| MOSI
| 38
| GPIO20
| SPI6_MOSI

| MISO
| 35
| GPIO19
| SPI6_MISO

| SCLK
| 40
| GPIO21
| SPI6_SCLK

| CE0
| 12
| GPIO18
| SPI6_CE0_N

| CE1
| 13
| GPIO27
| SPI6_CE1_N
|===

[[master-modes]]
==== 主模式

信号名称缩写

----
SCLK - Serial CLocK
CE   - Chip Enable (often called Chip Select)
MOSI - Master Out Slave In
MISO - Master In Slave Out
MOMI - Master Out Master In
----

[[standard-mode]]
===== 标准模式

在标准SPI模式下，外设执行标准3线串行协议（SCLK、MOSI和MISO）。


[[bidirectional-mode]]
===== 双向模式

在双向SPI模式下，实现相同的SPI标准，仅适用单线传输数据（MOMI）而非标准模式下使用双线（MISO和MOSI）。在这种模式下，MOSI引脚用作MOMI引脚。

[[lossi-mode-low-speed-serial-interface]]
===== LoSSI 模式 (低速串口)

LoSSI 标准允许向外围设备 （LCD） 发出命令并在外围设备之间传输数据。LoSSI 命令和参数的长度为 8 位，但使用一个额外的来表示字节是命令还是参数/数据。该额外位对于数据设置为高电平，对于命令设置为低位。生成的 9 位值将序列化为输出。LoSSI通常与兼容LCD控制器的type C接口的 http://mipi.org/specifications/display-interface[MIPI DBI] 一起使用。

NOTE: 一些命令会触发SPI控制器的自动读取，因此该模式不能用作多用途的9位SPI。

[[transfer-modes]]
==== 传输模式

* Polled
* Interrupt
* DMA

[[speed]]
==== 速度

CLK寄存器的CDIV（时钟分频器）字段设置SPI时钟速度：

----
SCLK = Core Clock / CDIV
----

如果 CDIV 设置为 0，则除数为 65536。除数必须是 2 的倍数，奇数向下舍入。请注意，由于模拟电气问题（上升时间、驱动强度等），并非所有可能的时钟速率都可用。

有关详细信息，请参见 <<driver,Linux 驱动程序>> 部分。

[[chip-selects]]
==== 芯片选择

在 *DMA* 模式下运行时，与 CS 线路的自动断言和反断言相关的设置和保持时间如下：

* CS 线将在传输的第一个字节的 msb 之前至少3 个核心时钟周期被断言。
* CS 线将在最终时钟脉冲的后沿之后不早于 1 个核心时钟周期内取消断言。

[[software]]
=== SPI 软件

[[driver]]
==== Linux 驱动程序

默认的 Linux 驱动程序是 `spi-bcm2835`。

SPI0默认禁用。如果要启用SPIO，则使用 xref:configuration.adoc#raspi-config[raspi-config] 或者确保  `/boot/config.txt` 中的 `dtparam=spi=on` 行未被注释掉。默认情况下，它使用2条片选线，但使用 `dtoverlay=spi0-1cs` 将其减少到1条。 `dtoverlay=spi0-2cs` 也存在，不加任何参数等效于 `dtparam=spi=on`。

如果要启用 SPI1，则可以使用 1、2 或 3 条片选线，并在片选线下添加：

----
dtoverlay=spi1-1cs  #1 chip select
dtoverlay=spi1-2cs  #2 chip select
dtoverlay=spi1-3cs  #3 chip select
----

到 `/boot/config.txt` 文件。SPI2、SPI3、SPI4、SPI5 和 SPI6 也存在类似的覆盖。

由于某些限制，驱动程序不使用硬件芯片选择线，而是可以使用任意数量的GPIO作为软件/GPIO片选。所以你可以自由地选择任何备用GPIO作为CS线，并且这些SPI覆盖都包括该控制——有关详细信息，请参见 `/boot/overlays/README` ，或者运行(例如) `dtoverlay -h spi0-2cs` (`dtoverlay -a | grep spi` 可能有助于列出这些)。

[[speed-2]]
===== S速度

该驱动程序支持所有的速度，甚至是核心时钟的整数除数。尽管如上所述，由于 GPIO 和连接设备的限制，并非所有这些速度都支持数据传输。一般来说超过 50MHz 的速率不支持数据传输，也许会遇到不同的情况。

[[supported-mode-bits]]
===== 支持的模式位

----
SPI_CPOL    - Clock polarity
SPI_CPHA    - Clock phase
SPI_CS_HIGH - Chip Select active high
SPI_NO_CS   - 1 device per bus, no Chip Select
SPI_3WIRE   - Bidirectional mode, data in and out pin shared
----

 `spi-bcm2835` 内核模块支持双向或 "3线" 模式。请注意，在此模式下，spi_transfer结构的 tx 或 rx 字段必须是 NULL 指针，因为只能进行半双工通信。否则，数据传输会失败。spidev_test.c源代码未考虑这一点，因此在3线模式下根本无法工作。

[[supported-bits-per-word]]
===== 每字支持的位数

* 8 - 正常
* 9 - 使用 LoSSI 模式支持此功能。

[[transfer-modes-2]]
===== 传输模式

所有SPI总线都支持interrupt模式。SPI0 和 SPI3-6 也支持 DMA 传输。

[[spi-driver-latency]]
===== SPI 驱动程序延迟

此 https://forums.raspberrypi.com/viewtopic.php?f=44&t=19489[线程] 讨论延迟问题。

[[spidev]]
==== spidev

`spidev` 为各个 SPI CS 线路提供基于 ioctl 的用户空间接口。设备树用于指示CS线是由内核驱动程序模块驱动还是由spidev代表用户管理;不可能同时执行这两个操作。请注意，Raspberry Pi内核在使用设备树启用spidev方面更简单- 上行内核会打印有关此类使用的告警，最终可能会完全阻止它。

[[using-spidev-from-c]]
===== 使用C语言中的 spidev

Linux 文档中有一个环回测试程序可以用作起点。请参见 <<troubleshooting,Troubleshooting>> 部分。

[[using-spidev-from-python]]
===== 使用 Python 中的 spidev

有几个Python库提供了对 `spidev`的访问，包括 `spidev` (`pip install spidev` - 参见 https://pypi.org/project/spidev/) 和 `SPI-Py` (https://github.com/lthiery/SPI-Py) 。

[[using-spidev-from-a-shell-such-as-bash]]
===== 使用shell(例如bash)中的spidev

[,bash]
----
# Write binary 1, 2 and 3
echo -ne "\x01\x02\x03" > /dev/spidev0.0
----

[[other-spi-libraries]]
==== 其他SPI库

有些用户空间库通过直接操作硬件来提供 SPI 控制(不推荐这种做法)。

[[troubleshooting-spi-hardware]]
=== 故障排除

[[loopback-test]]
==== 环回测试

环回测试用于测试SPI发送和接收。在MOSI和MISO之间放置一根电线。换回测试不测试CE0和CE1。

[,bash]
----
wget https://raw.githubusercontent.com/raspberrypi/linux/rpi-3.10.y/Documentation/spi/spidev_test.c
gcc -o spidev_test spidev_test.c
./spidev_test -D /dev/spidev0.0
spi mode: 0
bits per word: 8
max speed: 500000 Hz (500 KHz)

FF FF FF FF FF FF
40 00 00 00 00 95
FF FF FF FF FF FF
FF FF FF FF FF FF
FF FF FF FF FF FF
DE AD BE EF BA AD
F0 0D
----

上面的一些内容是从 https://elinux.org/RPi_SPI[elinux SPI 页面] 复制而来的，该页面也借用了这里。两者均受CC-SA 许可证保护。
