[[universal-serial-bus-usb]]
== 通用串行总线 (USB)

一般来说，Linux 支持的每个设备都可以与 Raspberry Pi 一起使用，尽管 Raspberry Pi 4 之前的型号存在一些限制。

[[maximum-power-output]]
=== 最大供电输出

与所有计算机一样，Raspberry Pi上的USB端口提供有限的电量。USB 设备的问题通常是由电源问题引起的。要排除电源不足导致问题的可能性，请使用有源HUB将 USB 设备连接到Raspberry Pi。

|===
| 型号 | USB端口的最大供电输出

| Pi Zero, 1
| 每个端口500mA^1^

| Pi 2, 3, 4
| 所有端口总计1200 mA
|===

. 对于原始的Raspberry Pi 1 Model B，每个端口的限制为100mA。

[[raspberry-pi-4]]
=== Raspberry Pi 4

Raspberry Pi 4包含两个USB 3.0端口和两个USB 2.0端口，连接到VL805 USB控制器。4个端口上的 USB 2.0 线路均连接到VL805内的单个USB2.0 HUB：这将 USB 1.1 和 USB 2.0 设备的总可用带宽限制为单个 USB 2.0 端口的可用带宽。

在Raspberry Pi 4 上，以前型号上使用的 USB 控制器位于 USB Type C端口上，默认情况下处于禁用状态。

[[raspberry-pi-zero-1-2-and-3]]
=== Raspberry Pi Zero/ 1/ 2 / 3

Raspberry Pi 4 之前的型号上的 USB 控制器仅对某些设备提供基本级别的支持，这会带来更高的软件处理开销。它还仅支持一个根USB端口：来自连接设备的所有流量都通过这条单一总线传输，该总线的最高运行速度为480Mbps。

USB 2.0 规范定义了3种设备速度 - 低速、全速和高速。大多数鼠标和键盘都是低速的，大多数USB音频设备是全速的，大多数视频设备（网络摄像头或视频捕获）都是高速的。

通常，将多个高速USB设备连接到Raspberry Pi不会出现任何问题。

与低速和全速设备通信时产生的软件开销表明同时处于活动状态的低速和全速设备的数量受到限制。连接到Raspberry Pi的少量这些类型的设备不会引起任何问题。

[[known-usb-issues]]
=== 已知的USB问题

[[interoperability-with-usb-3-0-hubs]]
==== 与 USB 3.0 HUB的互操作性

USB 3.0 HUB在使用全速或低速设备（包括大多数鼠标和键盘）时存在问题。大多数USB 3.0 HUB硬件中的错误表示Raspberry Pi 4之前的型号无法与连接到USB 3.0 HUB的全速或低速设备通信。

USB 2.0 高速设备（包括 USB 2.0 HUB）在通过 USB 3.0 HUB连接时可正常运行。

避免将低速或全速设备连接到 USB 3.0 HUB。解决方法是将 USB 2.0 HUB插入 USB 3.0 HUB的下行端口并连接低速设备，或者在 Raspberry Pi 和 USB 3.0 HUB之间使用 USB 2.0 集线器，然后将低速设备插入 USB 2.0 HUB。

[[usb-1-1-webcams]]
==== USB 1.1 网络摄像头

旧的网络摄像头可能是全速设备。由于这些设备会传输大量数据并产生额外的软件开销，因此无法保证可靠的运行。解决方法是尝试以较低的分辨率使用相机。

[[esoteric-usb-sound-cards]]
==== 深奥的 USB 声卡

昂贵的发烧级声卡通常使用大量USB带宽：无法保证96kHz/192kHz DAC的可靠运行。解决方法是强制输出流为 CD 质量 (44.1kHz/48kHz 16-bit) 会将流带宽降低到可靠的水平。

[[single-tt-usb-hubs]]
==== 单个 TT USB HUB

USB 2.0 和USB 3.0 HUB具有一种与连接到其下行端口的全速或低速设备通信的机制，称为事务转换器 （TT）。该设备缓冲来自主机的高速请求，并以全速或低速将其传输到下行设备。USB 规范包含两种HUB配置：单TT（1个 TT 用于所有端口）和多 TT（每个端口一个 TT）。由于硬件限制，如果将太多全速或低速设备插入单个 TT HUB，则设备的行为可能不可靠。建议使用多TT HUB与多个全速和低速设备接口。解决方法是将全速和低速设备分散在Raspberry Pi USB端口和单个TT HUB之间。
