[[kernel]]
== 内核

The Raspberry Pi 内核存储在 GitHub 中，可以在 https://github.com/raspberrypi/linux[github.com/raspberrypi/linux] 查看;它遵循主分支 https://github.com/torvalds/linux[Linux内核]。主分支 Linux 内核在不断更新;我们获取首页提到的内核的长期版本，并将更改集成到 Raspberry Pi 内核中。然后我们创建一个“next”分支，其中包含内核的不稳定端口;经过广泛的测试和讨论，我们将其推送到主分支。

[[updating-your-kernel]]
=== 更新您的内核

如果您使用标准的the Raspberry Pi操作系统 xref:os.adoc#updating-and-upgrading-raspberry-pi-os[更新和升级过程]，这将自动更新内核到最新的稳定版本。这是推荐的过程。但是，在某些情况下，您可能希望更新到最新的“前沿”或测试内核。只有当Raspberry Pi工程师建议您这样做时，或者只有在这个最新的软件中才有特定的功能时，您才应该这样做。

[[getting-your-code-into-the-kernel]]
=== 将代码合并到内核

可能有很多原因致使您想放一些东西到内核里面：

* 你已经编写了一些特定于 Raspberry Pi 的代码，希望每个人都能从中受益
* 您已经为设备编写了通用 Linux 内核驱动程序，并希望每个人都使用它
* 您已经修复了一个通用内核错误
* 您已经修复了特定于the Raspberry Pi的内核错误

最初，您应该派生 https://github.com/raspberrypi/linux[Linux存储库]，并在您的构建系统上克隆它；这可以在Raspberry Pi上，也可以在用于交叉编译的Linux机器上。然后，您可以做出更改，测试它们，并将它们提交到您的分支中。
接下来，确定代码是否是特定于the Raspberry Pi：

* 对于特定于 Raspberry Pi 的更改或错误修复，请向内核提交拉取请求。
* 对于一般的 Linux 内核更改（即新驱动程序），需要先在上游提交这些更改。在上游提交并接受后，提交拉取请求，我们将收到它。
