[[building]]
== 构建内核

操作系统附带的默认编译器和链接器被配置为构建在该操作系统上运行的可执行文件——它们是本地工具——但事实并非如此。交叉编译器被配置为为运行构建过程的目标之外的目标构建代码，使用它被称为交叉编译。

the Raspberry Pi内核的交叉编译很有用，原因有两个：

* 它允许使用 64 位操作系统构建 32 位内核，反之亦然，并且
* 即使是一台普通的笔记本电脑也可以比the Raspberry Pi本身更快地交叉编译the Raspberry Pi内核.

以下说明分为本机构建和交叉编译;选择适合您情况的部分 - 尽管两者之间有许多常见的步骤，但也存在一些重要差异。

=== 在本地构建内核

在Raspberry Pi上，首先安装最新版本的 https://www.raspberrypi.com/software/operating-systems/#raspberry-pi-os-32-bit[Raspberry Pi OS]。然后启动您的the Raspberry Pi，登录并确保您已连接到互联网以允许您访问源代码。

首先安装 Git 和构建依赖项

[,bash]
----
sudo apt install git bc bison flex libssl-dev make
----

接下来获取源，这将需要一些时间：

[,bash]
----
git clone --depth=1 https://github.com/raspberrypi/linux
----

[[choosing_sources]]
==== 选择来源

上面的git clone命令将下载当前活动分支（我们正在构建 Raspberry Pi OS 映像的分支），没有任何历史记录。省略 `--depth=1` 将下载整个存储库，包括所有分支的完整历史记录，但这需要更长的时间并占用更多的存储空间。

要下载其他分支（同样没有历史记录），请使用以下 `--branch` 选项：

[,bash]
----
git clone --depth=1 --branch <branch> https://github.com/raspberrypi/linux
----

其中 `<branch>` 是您要下载的分支的名称。

有关可用分支的信息，请参阅原始 https://github.com/raspberrypi/linux[GitHub 存储库]。

[[kernel-configuration]]
==== 内核配置

配置内核;除了默认配置外，您可能还希望 xref:linux_kernel.adoc#configuring-the-kernel[更详细地配置内核] 或 xref:linux_kernel.adoc#patching-the-kernel[应用来自其他来源的补丁]，以添加或删除所需的功能。

[[default_configuration]]
===== 应用默认配置

首先，通过运行以下命令来准备默认配置，具体取决于您的the Raspberry Pi型号：

对于the Raspberry Pi 1、零和零W 以及the Raspberry Pi计算模块 1 默认（仅限 32 位）构建配置

[,bash]
----
cd linux
KERNEL=kernel
make bcmrpi_defconfig
----

适用于the Raspberry Pi 2、3、3+ 和零2W，以及the Raspberry Pi计算模块 3 和 3+ 默认 32 位构建配置

[,bash]
----
cd linux
KERNEL=kernel7
make bcm2709_defconfig
----

对于the Raspberry Pi 4 和 400，以及the Raspberry Pi计算模块 4 默认的 32 位构建配置

[,bash]
----
cd linux
KERNEL=kernel7l
make bcm2711_defconfig
----

适用于the Raspberry Pi 3、3+、4、400 和零2W 以及the Raspberry Pi计算模块 3、3+ 和 4 默认 64 位构建配置
[,bash]
----
cd linux
KERNEL=kernel8
make bcm2711_defconfig
----

[[customising-the-kernel-version-using-localversion]]
===== 自定义内核版本 `LOCALVERSION`

除了内核配置更改之外，您可能还希望调整 `LOCALVERSION` 以确保新内核不会收到与上游内核相同的版本字符串。这既澄清了您在 `uname` 的输出中运行自己的内核，又确保 `/lib/modules` 中的现有模块不会被覆盖。

为此，请更改 `.config` 中的以下行：

----
CONFIG_LOCALVERSION="-v7l-MY_CUSTOM_KERNEL"
----

您还可以以图形方式更改该设置，如 xref:linux_kernel.adoc#configuring-the-kernel[内核配置说明]中所示。它位于 "常规设置"\=>"本地版本 - 附加到内核版本"中。

[[building-the-kernel]]
==== 构建内核

构建并安装内核、模块和DTB文件;此步骤可能需要 *很长* 时间，具体取决于所使用的the Raspberry Pi模型。 对于 32 位内核:

[,bash]
----
make -j4 zImage modules dtbs
sudo make modules_install
sudo cp arch/arm/boot/dts/*.dtb /boot/
sudo cp arch/arm/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm/boot/zImage /boot/$KERNEL.img
----

对于 64 位内核:

[,bash]
----
make -j4 Image.gz modules dtbs
sudo make modules_install
sudo cp arch/arm64/boot/dts/broadcom/*.dtb /boot/
sudo cp arch/arm64/boot/dts/overlays/*.dtb* /boot/overlays/
sudo cp arch/arm64/boot/dts/overlays/README /boot/overlays/
sudo cp arch/arm64/boot/Image.gz /boot/$KERNEL.img
----

NOTE: 在Raspberry Pi 2/3/4上，该 `-j4` 标志将工作分配给所有四个内核，大大加快了编译速度。

如果你现在重启，你的Raspberry Pi应该运行你新编译的内核！

[[cross-compiling-the-kernel]]
=== 交叉编译内核

首先，您需要一个合适的Linux交叉编译主机。我们倾向于使用Ubuntu由于Raspberry Pi OS也是Debian发行版，这意味着许多方面都是相似的，比如命令行。

您可以在Windows上使用VirtualBox(或VMWare)来完成此操作，也可以将其直接安装到您的计算机上。作为参考，你可以遵循 http://www.wikihow.com/Install-Ubuntu-on-VirtualBox[Wikihow] 上的在线说明。

[[install-required-dependencies-and-toolchain]]
==== 安装所需的依赖项和工具链

要构建用于交叉编译的源代码，请执行以下命令，确保您的计算机上有所需的依赖项:

[,bash]
----
sudo apt install git bc bison flex libssl-dev make libc6-dev libncurses5-dev
----

如果您发现您需要其他东西，请提交一个拉请求来更改文档。

[[install-the-32-bit-toolchain-for-a-32-bit-kernel]]
===== 为32位内核安装32位工具链

[,bash]
----
sudo apt install crossbuild-essential-armhf
----

[[install-the-64-bit-toolchain-for-a-64-bit-kernel]]
===== 为64位内核安装64位工具链

[,bash]
----
sudo apt install crossbuild-essential-arm64
----

[[get-the-kernel-sources]]
==== 获取内核源代码

要下载当前分支的最小源代码树，请运行:

[,bash]
----
git clone --depth=1 https://github.com/raspberrypi/linux
----

有关如何选择不同分支的说明，请参见上面的 <<choosing_sources,*选择源*>>。

[[build-sources]]
==== 编译源代码

输入以下命令来构建源和设备树文件:

[[32-bit-configs]]
===== 32-位 配置

对于Raspberry Pi 1、零和零W以及Raspberry Pi计算模块1:

[,bash]
----
cd linux
KERNEL=kernel
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcmrpi_defconfig
----

对于Raspberry Pi 2、3、3+和Zero 2 W，以及Raspberry Pi计算模块3和3+:

[,bash]
----
cd linux
KERNEL=kernel7
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2709_defconfig
----

对于Raspberry Pi 4和400以及Raspberry Pi计算模块4:

[,bash]
----
cd linux
KERNEL=kernel7l
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- bcm2711_defconfig
----

[[64-bit-configs]]
===== 64-位 配置

对于Raspberry Pi 3、3+、4、400和Zero 2 W，以及Raspberry Pi计算模块3、3+和4:

[,bash]
----
cd linux
KERNEL=kernel8
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- bcm2711_defconfig
----

[[build-with-configs]]
===== 配置构建

NOTE: 为了在多处理器系统上加速编译，并在单处理器系统上获得一些改进，可以使用 `-j n` ，其中n是处理器的数量* 1.5。您可以使用 `nproc` 命令来查看您有多少个处理器。或者，请随意试验，看看什么有效！

[[for-all-32-bit-builds]]
====== 对于所有32位版本

[,bash]
----
make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- zImage modules dtbs
----

[[for-all-64-bit-builds]]
====== 对于所有64位版本

NOTE: 请注意32位和64位图像目标之间的差异。

[,bash]
----
make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- Image modules dtbs
----

[[install-directly-onto-the-sd-card]]
==== 直接安装到SD卡上

构建好内核后，您需要将它复制到您的Raspberry Pi上并安装模块；最好直接使用SD读卡器。

首先，在插入SD卡前后使用 `lsblk` 进行识别。您应该会得到类似这样的结果:

----
sdb
   sdb1
   sdb2
----

其中 `sdb1` 是 `FAT` 文件系统(引导)分区， `sdb2` 是 `ext4` 文件系统(根)分区。

首先安装它们，根据需要调整分区号:

[,bash]
----
mkdir mnt
mkdir mnt/fat32
mkdir mnt/ext4
sudo mount /dev/sdb1 mnt/fat32
sudo mount /dev/sdb2 mnt/ext4
----

NOTE: 您应该根据您的设置适当调整驱动器号，例如，如果您的SD卡显示为 `/dev/sdc` ，而不是 `/dev/sdb` 。

接下来，将内核模块安装到 SD 卡上：

[[for-32-bit]]
===== 对于 32-位

[,bash]
----
sudo env PATH=$PATH make ARCH=arm CROSS_COMPILE=arm-linux-gnueabihf- INSTALL_MOD_PATH=mnt/ext4 modules_install
----

[[for-64-bit]]
===== 对于 64-位

[,bash]
----
sudo env PATH=$PATH make ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- INSTALL_MOD_PATH=mnt/ext4 modules_install
----

最后，将内核和设备树 blob 复制到 SD 卡上，确保备份旧内核：

[[for-32-bit-2]]
===== 对于 32-位

[,bash]
----
sudo cp mnt/fat32/$KERNEL.img mnt/fat32/$KERNEL-backup.img
sudo cp arch/arm/boot/zImage mnt/fat32/$KERNEL.img
sudo cp arch/arm/boot/dts/*.dtb mnt/fat32/
sudo cp arch/arm/boot/dts/overlays/*.dtb* mnt/fat32/overlays/
sudo cp arch/arm/boot/dts/overlays/README mnt/fat32/overlays/
sudo umount mnt/fat32
sudo umount mnt/ext4
----

[[for-64-bit-2]]
===== 对于 64-位

[,bash]
----
sudo cp mnt/fat32/$KERNEL.img mnt/fat32/$KERNEL-backup.img
sudo cp arch/arm64/boot/Image mnt/fat32/$KERNEL.img
sudo cp arch/arm64/boot/dts/broadcom/*.dtb mnt/fat32/
sudo cp arch/arm64/boot/dts/overlays/*.dtb* mnt/fat32/overlays/
sudo cp arch/arm64/boot/dts/overlays/README mnt/fat32/overlays/
sudo umount mnt/fat32
sudo umount mnt/ext4
----

另一种选择是将内核复制到同一位置，但使用不同的文件名 - 例如 `kernel-myconfig.img` - 而不是覆盖 `kernel.img` 文件。然后，您可以编辑该 `config.txt` 文件以选择the Raspberry Pi将启动的内核：

----
kernel=kernel-myconfig.img
----

这样做的好处是，将自定义内核与系统管理的库存内核映像和任何自动更新工具分开，并允许您在内核无法引导时轻松恢复到库存内核。.

最后，将卡插入the Raspberry Pi并启动它！
