[[patching-the-kernel]]
== 修补内核

在 xref:linux_kernel.adoc#building[构建]自定义内核时，您可能希望将补丁或补丁集合（"补丁集"）应用于 Linux 内核。

补丁集通常作为临时措施提供较新的硬件，在补丁应用于上游 Linux 内核（"主线"）之前，然后向下传播到 Raspberry Pi 内核源。但是，存在用于其他目的的补丁集，例如启用完全抢占式内核以供实时使用。

[[version-identification]]
=== 版本标识

在下载和应用补丁时检查您拥有的内核版本非常重要。在内核源目录中，运行 `head Makefile -n 3` 将显示源与以下版本相关的版本：

[source]
----
VERSION = 3
PATCHLEVEL = 10
SUBLEVEL = 25
----

在本例中，源码适用于 3.10.25 内核。您可以使用该 `uname -r` 命令查看您在系统上运行的版本。In this instance, the sources are for a 3.10.25 kernel. You can see what version you're running on your system with the `uname -r` command.

[[applying-patches]]
=== 应用补丁

应用修补程序的方式取决于修补程序可用的格式。大多数修补程序都是单个文件，并与 `patch` 实用程序一起应用。例如，让我们下载并使用实时内核补丁来修补我们的示例内核版本：

[,bash]
----
 wget https://www.kernel.org/pub/linux/kernel/projects/rt/3.10/older/patch-3.10.25-rt23.patch.gz
 gunzip patch-3.10.25-rt23.patch.gz
 cat patch-3.10.25-rt23.patch | patch -p1
----

在我们的例子中，我们简单地下载文件，解压缩它，然后使用 `cat` 工具和Unix管道将它传递给 `patch` 。

某些修补程序集以邮箱格式修补程序集的形式提供，排列为修补程序文件的文件夹。我们可以使用 Git 将这些补丁应用于我们的内核，但首先我们必须配置 Git 以在进行这些更改时让它知道我们是谁：

[,bash]
----
 git config --global user.name "Your name"
 git config --global user.email "your email in here"
----

完成此操作后，我们可以应用补丁:

[,bash]
----
 git am -3 /path/to/patches/*
----

如有疑问，请咨询补丁的分销商，他们应该告诉您如何应用它们。某些补丁集需要特定的提交才能进行修补;按照修补程序分发服务器提供的详细信息进行操作。
