== 有用的实用程序

有几个有用的命令行

=== tvservice

`tvservice` 是一个命令行应用程序，用于获取和设置有关显示器的信息，主要针对HDMI视频和音频。

键入 `tvservice` 本身将显示可用命令行选项的列表。

==== -p, --preferred

使用首选设置打开 HDMI 输出。

==== -o, --off

关闭显示器输出。

NOTE: 使用此命令关闭输出电源也会破坏与显示器关联的任何帧缓冲器/dispmanx 层。这些不会在随后开机时重新建立，因此会导致空白屏幕。

更好的选择是使用 xref:os.adoc#vcgencmd[vcgencmd display_power] 选项，因为这将保留任何帧缓冲，因此当显示器重新打开电源时，将返回到之前的开机状态。

==== -e, --explicit="Group Mode Drive"

使用指定的设置打开HDMI

组可以是 `CEA`, `DMT`, `CEA_3D_SBS`, `CEA_3D_TB`, `CEA_3D_FP`, `CEA_3D_FS` 之一。
模式是从 `-m, --modes` 选项返回的模式之一。
驱动器可以是 `HDMI`, `DVI` 之一。


==== -t, --ntsc

在HDMI模式下使用59.94Hz（NTSC频率）而不是60Hz。

==== -c, --sdtvon="Mode Aspect [P]"

以指定 `PAL` 或 `NTSC` 模式打开标清电视（复合输出）的电源,以及指定的宽高比 `4:3`, `14:9`, `16:9`。可选 `P` 参数可用于指定渐进式模式。

==== -m, --modes=Group

其中组是 `CEA` 或 `DMT`.

显示指定组中可用的显示模式列表。

==== -M, --monitor

监控任何 HDMI 事件，例如拔出或连接。

==== -s, --status

显示显示模式的当前设置，包括模式、分辨率和频率。

==== -a, --audio

显示音频模式的当前设置，包括通道、采样率和样本大小。

==== -d, --dumpid=filename

将当前 EDID 保存到指定的文件名。然后，您可以使用 `edidparser <filename>` 显示成可读的形式。

==== -j, --json

与 `--modes` 选项结合使用时，以 JSON 格式显示模式信息。

==== -n, --name

从 EDID 数据中提取显示名称并显示它。

==== -l, --list

列出所有连接的显示器及其显示 ID。

==== -v, --device=display

指定要使用的设备的 ID;有关可用 ID，请参阅 `--list` 的输出。

=== vcgencmd

 `vcgencmd` 工具用于从Raspberry Pi上的VideoCore GPU输出信息。您可以在 https://github.com/raspberrypi/userland/tree/master/host_applications/linux/apps/gencmd[Github].上找到 `vcgencmd` 实用程序的源代码。
要获取支持的所有 `vcgencmd` 命令的列表，请使用 `vcgencmd commands`下面列出了一些有用的命令及其必需的参数。

==== vcos

`vcos` 命令有两个有用的子命令：

* `version` 在VideoCore上显示固件的构建日期和版本
* `log status` 显示各种VideoCore固件区域的错误日志状态

==== version

显示 VideoCore 固件的构建日期和版本。

==== get_camera

显示Raspberry Pi相机的启用和检测状态： `1` 表示是， `0` 表示否。虽然除缩减版本外的所有固件都支持相机，但需要使用 xref:configuration.adoc#raspi-config[raspi-config]. 启用此支持。

==== get_throttled

返回系统的受限制状态。这是一个位模式 - a正在设置的位表示以下含义：

[cols="^,,"]
|===
| 位 | 十六进制值 | 意义

| 0
| 0x1
| 检测到欠压

| 1
| 0x2
| Arm频率上限

| 2
| 0x4
| 当前已限制

| 3
| 0x8
| 软件温度限制激活

| 16
| 0x10000
| 检测到低电压

| 17
| 0x20000
| 检测到arm频率达到上限

| 18
| 0x40000
| 限制

| 19
| 0x80000
| 软件温度限制中
|===

==== measure_temp

返回由其内部温度传感器测量的 SoC 温度; 在Raspberry Pi 4 上， `measure_temp pmic` 返回 PMIC 的温度。

==== measure_clock [clock]

这将返回指定时钟的当前频率。选项包括：

[cols="^,"]
|===
| clock | 描述

| arm
| ARM 核心

| core
| GPU 核心

| h264
| H.264 block

| isp
| 图像传感器管道

| v3d
| 3D 块

| uart
| UART

| pwm
| PWM 模块（模拟音频输出）

| emmc
| SD卡接口

| pixel
| 像素

| vec
| 模拟视频编码器

| hdmi
| HDMI

| dpi
| 显示并行接口
|===

如 `vcgencmd measure_clock arm`

==== measure_volts [block]

显示特定模块使用的当前电压。

[cols="^,"]
|===
| block | 描述

| core
| VC4 内核电压

| sdram_c
| SDRAM 核心电压

| sdram_i
| SDRAM I/O 电压

| sdram_p
| SDRAM物理电压
|===

==== otp_dump

显示 SoC 内 OTP（一次性可编程）存储器的内容。这些是 32 位值，索引范围为 8 到 64。有关更多详细信息，请参阅 xref:raspberry-pi.adoc#otp-register-and-bit-definitions[OTP 页面]。

[[getconfig]]
==== get_config [configuration item|int|str]

显示指定配置设置的值：或者，指定 `int`（整数）或 `str`（字符串）以查看给定类型的所有配置项。例如：

----
vcgencmd get_config total_mem
----

返回设备上的总内存（以 MB 为单位）。

==== get_mem type

报告 ARM 和 GPU 可寻址的内存量。`vcgencmd get_mem arm` 显示 ARM 可寻址内存的使用量; `vcgencmd get_mem gpu` 以显示 GPU 可寻址内存的使用量。请注意，在内存超过 1GB 的设备上，`arm` 参数将始终返回 1GB 减去 `gpu` 内存值，因为 GPU 固件仅知道前 1GB 内存。要获取设备上总内存的准确报告，请参阅配置项 `total_mem` 的 <<getconfig,`get_config`>> 部分。

===== codec_enabled [type]

报告是否启用了指定的编解码器类型。可能的类型选项是AGIF，FLAC，H263，H264，MJPA，MJPB，MJPG，*MPG2*，MPG4，MVC0，PCM，THRA，VORB，VP6，VP8，WMV9，WVC1。突出显示的那些目前需要付费许可证（有关更多信息，请参阅 xref:config_txt.adoc#licence-key-and-codec-options[config.txt部分] ），但在 Raspberry Pi 4 和 400 上除外，在这些硬件编解码器中，这些硬件编解码器优先于软件解码被禁用，软件解码不需要许可证。请注意，由于Raspberry Pi 4和400上的H.265硬件块不是VideoCore GPU的一部分，因此无法通过此命令访问其状态。

===== get_lcd_info

显示任何附加显示器的分辨率和颜色深度。

===== mem_oom

显示有关 VideoCore 内存空间中发生的任何 OOM（内存不足）事件的统计信息。

===== mem_reloc_stats

显示来自视频核心上可重定位内存分配器的统计信息。

===== read_ring_osc

返回环形振荡器的当前速度电压和温度。

===== hdmi_timings

显示当前的 HDMI 设置计时。有关返回值的详细信息，请参阅 xref:config_txt.adoc#video-options[视频配置]。

===== dispmanx_list

转储当前正在显示的所有 dispmanx 项目的列表。

===== display_power [0 | 1 | -1] [display]

显示当前显示器电源状态，或设置显示电源状态。 `vcgencmd display_power 0` 将关闭当前显示器的电源。`vcgencmd display_power 1` 将打开显示器的电源。如果未设置任何参数，则将显示当前电源状态。最后一个参数是可选的显示 ID，由tvservice -l返回或从下表返回，它允许打开或关闭特定显示器。请注意，对于 7 英寸 Raspberry Pi 触摸显示屏，这只是打开和关闭背光。触摸功能继续正常运行。

`vcgencmd display_power 0 7` 将关闭电源以显示 ID 7，即Raspberry Pi 4上的 HDMI 1。

|===
| Display | ID

| 主LCD
| 0

| 辅助LCD
| 1

| HDMI 0
| 2

| 复合
| 3

| HDMI 1
| 7
|===

To determine if a specific display ID is on or off, use -1 as the first parameter.

`vcgencmd display_power -1 7` 将会返回0 如果显示ID7 处于关闭状态;如果显示 ID 7 打开，则返回 1;如果显示 ID 7 处于未知状态（例如未检测到），则返回 -1。

=== vcdbg

`vcdbg` 是一个应用程序，用于帮助从在ARM上运行的Linux调试VideoCore GPU。它需要以根用户身份运行。此应用程序主要用于树莓派工程师，尽管有一些命令一般用户可能会发现有用。

`sudo vcdbg help` 将给出可用命令的列表。

NOTE: 仅列出了最终用户使用的选项。

==== version

显示来自视频核心的各种版本信息项。

==== log

从指定的子系统转储日志。可能的选项包括：

|===
| log | 描述

| msg
| 打印出消息日志

| assert
| 打印出断言日志

| ex
| 打印出异常日志

| info
| 从日志记录标头中打印出信息

| level
| 设置指定类别的 VCOS 日志记录级别： n\|e\|w\|i\|t

| list
| 列出 VCOS 日志记录级别
|===

例如，要打印出消息日志的当前内容：

`vcdbg log msg`

==== malloc

列出 VideoCore 堆中当前的所有内存分配。

==== pools

列出池分配器的当前状态

==== reloc

不带任何其他参数，列出可重定位分配器的当前状态。 `sudo vcdbg reloc small` 
用于列出小分配。
使用 `sudo vcdbg reloc stats` 命令列出可重定位分配器的统计信息。

==== hist

与任务历史记录相关的命令。

用 `sudo vcdbg hist gnuplot` 将 gnuplot 格式的任务历史记录转储到 task.gpt 和 task.dat
