[[network-boot-your-raspberry-pi]]
== 网络启动 Raspberry Pi

您可以设置DHCP / TFTP服务器，该服务器将允许您从网络启动Raspberry Pi 3或Raspberry Pi 4。

这些说明假定您有一个现有的家庭网络，并且您希望将Raspberry Pi用于 *服务器*。 您还需要一个额外的Raspberry Pi 3 或 Raspberry Pi 4 作为要启动的 *客户端* 。只需要一个 SD 卡，因为在初始客户端配置后，客户端将从服务器引导。

NOTE: 由于可用的网络设备和路由器种类繁多，我们无法保证网络启动适用于任何设备。我们收到报告称，如果无法使网络引导正常工作，则在网络上禁用 STP 帧可能会有所帮助。

[[client-configuration]]
=== 客户端配置

[[raspberry-pi-3-model-b]]
==== Raspberry Pi 3 Model B

NOTE: 本节仅适用于Raspberry Pi 3 Model B，因为网络启动在出厂时已在Raspberry Pi 3 Model B+ 上启用。

在Raspberry Pi 3 Model B网络启动之前，需要从SD卡启动，并带有配置选项以启用USB启动模式。这将在Raspberry Pi SoC 中的 OTP（一次性可编程）内存中设置一个位，以启用网络启动。完成此操作后，Raspberry Pi Model 3B将尝试从USB启动，如果无法从SD卡启动，则从网络启动。

以通常的方式在SD卡上安装Raspberry Pi OS Lite或带桌面的Raspberry Pi OS。接下来，使用以下命令启用 USB 启动模式：

[,bash]
----
echo program_usb_boot_mode=1 | sudo tee -a /boot/config.txt
----

这会将 `program_usb_boot_mode=1` 添加到 `/boot/config.txt`的末尾。使用 `sudo reboot`重新启动Raspberry Pi。一旦客户端Raspberry Pi重新启动，检查OTP是否已被编程为:

[,bash]
----
vcgencmd otp_dump | grep 17:
17:3020000a
----

确保 `0x3020000a` 输出正确。

客户端配置已经基本完成。最后要做的是从 `config.txt` 中删除 `program_usb_boot_mode` 行。最后，用 `sudo poweroff` 关闭客户端Raspberry Pi。

[[raspberry-pi-4-model-b]]
==== Raspberry Pi 4 Model B

可以使用 `raspi-config` 工具在Raspberry Pi 4上启用网络引导。首先，运行 `raspi-config` ，如下所示:

[,bash]
----
sudo raspi-config
----

在 `raspi-config` 中选择 `Advanced Options`, 再选择 `Boot Order`, 最后选择 `Network Boot`。然后，您必须重新启动设备，以便将对启动顺序的更改编程到启动加载程序EEPROM中。一旦Raspberry Pi重新启动，检查启动顺序现在是`0xf21`:

[,bash]
----
vcgencmd bootloader_config
----

有关配置Raspberry Pi 4 启动加载程序的更多详细信息，请参见 xref:raspberry-pi.adoc#raspberry-pi-4-bootloader-configuration[Raspberry Pi 4 启动加载程序配置].

[[ethernet-mac-address]]
=== 以太网MAC地址

在配置网络启动之前，请记下序列号和 mac 地址，以便 TFTP/DHCP 服务器可以识别主板。

在Raspberry Pi 4 上，MAC 地址在制造时进行编程，MAC 地址和序列号之间没有链接。MAC 地址和序列号都显示在启动加载程序 xref:raspberry-pi.adoc#boot-diagnostics-on-the-raspberry-pi-4[HDMI 诊断] 屏幕上。

要查找以太网 MAC 地址：

[,bash]
----
ethtool -P eth0
----

要查找序列号：

[,bash]
----
grep Serial /proc/cpuinfo | cut -d ' ' -f 2 | cut -c 8-16
----

[[server-configuration]]
=== 服务器配置

将 SD 卡插入服务器Raspberry Pi，然后启动服务器。客户端 Raspberry Pi 需要一个根文件系统来引导：我们将使用服务器的根文件系统的副本并将其放在  `/nfs/client1` 中:

[,bash]
----
sudo mkdir -p /nfs/client1
sudo apt install rsync
sudo rsync -xa --progress --exclude /nfs / /nfs/client1
----

通过对客户机文件系统进行 chrooting 操作，在客户机文件系统上重新生成 SSH 主机密钥：

[,bash]
----
cd /nfs/client1
sudo mount --bind /dev dev
sudo mount --bind /sys sys
sudo mount --bind /proc proc
sudo chroot .
rm /etc/ssh/ssh_host_*
dpkg-reconfigure openssh-server
exit
sudo umount dev sys proc
----

查找本地网络的设置。您需要找到路由器（或网关）的地址，这可以通过以下方式完成：

[,bash]
----
ip route | awk '/default/ {print $3}'
----

然后运行：

[,bash]
----
ip -4 addr show dev eth0 | grep inet
----

这应该给出如下输出：

[,bash]
----
inet 10.42.0.211/24 brd 10.42.0.255 scope global eth0
----

第一个地址是网络上服务器Raspberry Pi的 IP 地址，斜杠后面的部分是网络大小。您的极有可能是 `/24`。还要注意网络的 `brd` (广播) 地址。 记下上一个命令的输出，该命令将包含Raspberry Pi的 IP 地址和网络的广播地址。

最后，记下 DNS 服务器的地址，该地址与网关的地址相同。您可以通过以下方式找到它：

[,bash]
----
cat /etc/resolv.conf
----

通过网络在服务器Raspberry Pi上配置静态网络地址，该网络用作 `systemd` 网络处理程序和DHCP服务器。

为此，您需要创建一个 `10-eth0.netdev` 和一个 `11-eth0.network` ，如下所示:

[,bash]
----
sudo nano /etc/systemd/network/10-eth0.netdev
----

添加以下行：

----
[Match]
Name=eth0

[Network]
DHCP=no
----

然后创建一个网络文件：

[,bash]
----
sudo nano /etc/systemd/network/11-eth0.network
----

添加以下内容：

----
[Match]
Name=eth0

[Network]
Address=10.42.0.211/24
DNS=10.42.0.1

[Route]
Gateway=10.42.0.1
----

此时，您将没有有效的DNS，因此您需要将之前记下的服务器添加到 `systemd/resolved.conf`中。在本例中，网关地址是 10.42.0.1。

[,bash]
----
sudo nano /etc/systemd/resolved.conf
----

取消注释 DNS 行并在此处添加 DNS IP 地址。此外，如果您有回退 DNS 服务器，请将其也添加到该服务器。

[,bash]
----
[Resolve]
DNS=10.42.0.1
#FallbackDNS=
----

启用 `systemd-networkd` 并重新启动以使更改生效：

[,bash]
----
sudo systemctl enable systemd-networkd
sudo reboot
----

现在开始 `tcpdump` ，以便您可以从客户端Raspberry Pi搜索DHCP数据包：

[,bash]
----
sudo apt install tcpdump dnsmasq
sudo systemctl enable dnsmasq
sudo tcpdump -i eth0 port bootpc
----

将客户端Raspberry Pi连接到您的网络并打开电源。检查客户端上的 LED 是否在大约 10 秒后亮起，然后您应该从客户端收到一个数据包 "DHCP/BOOTP, 来自 ..."

----
IP 0.0.0.0.bootpc > 255.255.255.255.bootps: BOOTP/DHCP, Request from b8:27:eb...
----

现在，您需要修改 `dnsmasq` 配置，使DHCP能够回复设备。按 +++<kbd>+++CTRL + C+++</kbd>+++ 退出 `tcpdump` 程序，然后输入以下内容:

[,bash]
----
echo | sudo tee /etc/dnsmasq.conf
sudo nano /etc/dnsmasq.conf
----

然后将 `dnsmasq.conf` 的内容替换为：

----
# Note: comment out port if you want DNS services for systems on the network.
port=0
dhcp-range=10.42.0.255,proxy
log-dhcp
enable-tftp
tftp-root=/tftpboot
pxe-service=0,"Raspberry Pi Boot"
----

在 `dhcp-range` 线路的第一个地址所在的地方，使用您之前记下的广播地址。

现在创建一个`/tftpboot` 目录:

[,bash]
----
sudo mkdir /tftpboot
sudo chmod 777 /tftpboot
sudo systemctl enable dnsmasq.service
sudo systemctl restart dnsmasq.service
----

现在监视 `dnsmasq` 日志:

[,bash]
----
tail -F /var/log/daemon.log
----

您应该看到如下所示的内容：

----
raspberrypi dnsmasq-tftp[1903]: file /tftpboot/bootcode.bin not found
----

接下来，您需要将引导文件夹的内容复制到 `/tftpboot` 目录中。

首先，按下 +++<kbd>+++CTRL + C+++</kbd>+++ 退出监视状态。然后输入以下内容：

[,bash]
----
cp -r /boot/* /tftpboot
----

由于 tftp 位置已更改，请重新启动 `dnsmasq`:

[,bash]
----
sudo systemctl restart dnsmasq
----

[[set-up-nfs-root]]
==== 设置 NFS 根目录

现在，这应该允许您的 Raspberry Pi 客户端尝试启动，直到它尝试加载根文件系统（它没有）。

此时，导出之前创建的文件系统 `/nfs/client1` 和 TFTP 启动导文件夹。

[,bash]
----
sudo apt install nfs-kernel-server
echo "/nfs/client1 *(rw,sync,no_subtree_check,no_root_squash)" | sudo tee -a /etc/exports
echo "/tftpboot *(rw,sync,no_subtree_check,no_root_squash)" | sudo tee -a /etc/exports
----

重新启动 RPC-Bind 和 NFS 服务器，以便让它们检测新文件。

[,bash]
----
sudo systemctl enable rpcbind
sudo systemctl restart rpcbind
sudo systemctl enable nfs-kernel-server
sudo systemctl restart nfs-kernel-server
----

编辑 `/tftpboot/cmdline.txt` 和 `root=` onwards，并将其替换为：

----
root=/dev/nfs nfsroot=10.42.0.211:/nfs/client1,vers=4.1,proto=tcp rw ip=dhcp rootwait
----

您应该将此处的 IP 地址替换为您记下的 IP 地址。同时删除以 init= 开头的命令行的任何部分。

最后，编辑 `/nfs/client1/etc/fstab` 并删除 `/dev/mmcblk0p1` 和 `p2` 行 (仅留下 `proc` )。然后, 将启动分区添加回:

[,bash]
----
echo "10.42.0.211:/tftpboot /boot nfs defaults,vers=4.1,proto=tcp 0 0" | sudo tee -a /nfs/client1/etc/fstab
----

祝你好运！如果第一次尝试时无法启动，请继续尝试。Raspberry Pi可能需要一分钟左右才能启动，所以请耐心等待。

[[using-pxetools]]
=== 使用 `pxetools`

我们已经创建了一个Python脚本，用于在内部快速设置将进行网络启动的Raspberry Pi。

该脚本带有一个序列号（可以在 `cat /proc/cpuinfo` 中找到） 、一个所有者名称和Raspberry Pi的名称。 它从Raspberry Pi操作系统映像为该Raspberry Pi创建一个根文件系统。还有一个 `--list` 选项可以打印出Raspberry Pi的IP地址，还有一个 `--remove` 选项。

NOTE: 以下说明描述了如何从新的Raspberry Pi操作系统精简版映像开始设置脚本所需的环境。最好安装硬盘或闪存驱动器/nfs，这样您的 SD 卡就不会向多个Raspberry Pi提供文件系统。这是留给读者的练习。

----
sudo apt update
sudo apt full-upgrade -y
sudo reboot

wget https://datasheets.raspberrypi.com/soft/prepare_pxetools.sh
bash prepare_pxetools
----

当系统提示保存 `iptables`规则时，请说 `no`。

 `prepare_pxetools` 脚本应该准备好使用 `pxetools` 所需的一切。

我们发现，在第一次使用  `pxetools` 之后，我们需要重新启动 `nfs` 服务器。使用以下工具执行此操作:

----
sudo systemctl restart nfs-kernel-server
----

然后插入你的 Raspberry Pi，它应该会启动。
