[[introduction-to-remote-access]]
== 远程访问简介

有时，您需要在不连接显示器的情况下访问Raspberry Pi。也许Raspberry Pi被嵌入到类似机器人的东西中，或者您可能想从其他地方查看它的一些信息。或者你根本没有备用显示器！

您可以从另一台机器连接到Raspberry Pi。但为了做到这一点，你需要知道它的IP地址。

任何连接到局域网的设备都会被分配一个IP地址。为了使用 xref:remote-access.adoc#ssh[SSH] 或 xref:remote-access.adoc#vnc[VNC]从另一台机器连接到您的Raspberry Pi，您需要知道Raspberry Pi的IP地址。如果您连接了显示器，这很容易，并且有许多方法可以从网络上的另一台机器远程找到它。

[[ip-address]]
=== 如何查找IP地址

使用以下方法之一可以在不连接到屏幕的情况下找到Raspberry Pi的 IP 地址：

NOTE: 如果您将显示器与Raspberry Pi一起使用，并且如果您启动到命令行而不是桌面，则您的 IP 地址应显示在登录提示之前的最后几条消息中。否则，打开终端窗口并输入 `hostname -I` 将显示您的Raspberry Pi的 IP 地址。

[[router-devices-list]]
==== 路由器设备列表

在Web浏览器中导航到路由器的IP地址，例如 `+http://192.168.1.1+`，该地址通常印在路由器的标签上;这将带您进入控制面板。然后使用您的凭据登录，该凭据通常也打印在路由器上或在随附的文件中发送给您。浏览到已连接设备或类似设备的列表（所有路由器都不同），您应该会看到一些您识别的设备。某些设备被检测为 PC、平板电脑、手机、打印机等。所以你应该认出一些并排除它们，以确定哪个是你的Raspberry Pi。另请注意连接类型;如果您的Raspberry Pi是用电线连接的，那么可供选择的设备应该更少。

[[resolving-raspberrypi-local-with-mdns]]
==== 使用mDNS进行解析 `raspberrypi.local` 

在Raspberry Pi操作系统上，Avahi服务支持即时可用的多播DNS。

如果您的设备支持 mDNS，您可以使用其主机名和 `.local` 后缀。
Raspberry Pi操作系统安装的默认主机名是 `raspberrypi`, 因此默认情况下，任何运行Raspberry Pi操作系统的Raspberry Pi都会响应：
[,bash]
----
ping raspberrypi.local
----

如果Raspberry Pi可访问， `ping` 将显示其 IP 地址：

----
PING raspberrypi.local (192.168.1.131): 56 data bytes
64 bytes from 192.168.1.131: icmp_seq=0 ttl=255 time=2.618 ms
----

如果您更改Raspberry Pi的系统主机名 (例如，通过编辑 `/etc/hostname`), Avahi 也会更改 `.local` 的 mDNS 地址。

如果您不记得Raspberry Pi的主机名，但安装了Avahi的系统，则可以使用 https://linux.die.net/man/1/avahi-browse[`avahi-browse`] 命令浏览LAN上的所有主机和服务。

[[nmap-command]]
==== nmap 命令

 `nmap` 命令（Network Mapper）是一个免费的开源网络发现工具，可用于Linux、macOS和Windows。

* 在 *Linux* 上安装, 请安装 `nmap` 软件包，例如 `apt install nmap`。
* 在 *macOS* 或 *Windows* 上安装, 参见 http://nmap.org/download.html[nmap.org 下载页面]。

要使用 `nmap` 扫描网络上的设备，您需要知道您所连接的子网。首先找到你自己的IP地址，换句话说就是你用来找到你的Raspberry Pi的IP地址的那台电脑的IP地址:

* 在 *Linux* 上，在终端窗口中输入 `hostname -I` 
* 在 *macOS* 上, 选择您的活动网络连接，以查看IP地址 `系统首选项` 网络
* 在 *Windows* 上, 转到控制面板，然后在下 `网络和共享中心` 下单击 `查看网络连接` ，选择你的网络连接并单击 `查看连接状态` 来查看IP地址。

现在您有了计算机的IP地址，您将扫描整个子网寻找其它设备。例如，如果您的IP地址是 `192.168.1.5`, ，其他设备将位于 `192.168.1.2`、 `192.168.1.3`、 `192.168.1.4`等地址。 此子网范围是 `192.168.1.0/24` (包括 `192.168.1.0` 到 `192.168.1.255`)。

现在，在整个子网范围内使用带有 `-sn` 标志的 `nmap` 命令(ping scan)。这可能需要几秒钟时间:

[,bash]
----
nmap -sn 192.168.1.0/24
----

Ping scan just pings all the IP addresses to see if they respond. For each device that responds to the ping, the output shows the hostname and IP address like so:

----
Starting Nmap 6.40 ( http://nmap.org ) at 2014-03-10 12:46 GMT
Nmap scan report for hpprinter (192.168.1.2)
Host is up (0.00044s latency).
Nmap scan report for Gordons-MBP (192.168.1.4)
Host is up (0.0010s latency).
Nmap scan report for ubuntu (192.168.1.5)
Host is up (0.0010s latency).
Nmap scan report for raspberrypi (192.168.1.8)
Host is up (0.0030s latency).
Nmap done: 256 IP addresses (4 hosts up) scanned in 2.41 seconds
----

在这里，您可以看到主机名为 `raspberrypi` 的设备的IP地址为 `192.168.1.8`。注意，要查看主机名，您必须通过将 `sudo` 添加到命令前面来以root用户身份运行nmap。

[[getting-ipv6-addresses-by-pinging-from-a-second-device]]
==== 通过从第2台设备pinging来获取IPV6地址

首先找到你自己的IP地址，换句话说，就是你用来通过 `hostname -I` 找到你的Raspberry Pi的IP地址的计算机的IP地址。

`fd00::ba27:ebff:feb6:f293 2001:db8:494:9d01:ba27:ebff:feb6:f293`

该示例显示了两个IP地址。第一个是所谓的唯一本地单播地址(`fc00::/7`)。第二个是全局单播地址(`2000::/3`)。根据您的网络(路由器)配置，也可能只看到其中一个。这两个地址对于到达局域网内的Raspberry Pi都是有效的。 `2000::/3` 之外的地址可以在全球范围内访问，前提是您的路由器的防火墙已打开。

现在使用第一步中的一个IP ping所有本地节点:

----
ping -c 2 -I 2001:db8:494:9d01:ba27:ebff:feb6:f293  ff02::1
ping -c 2 -I 2001:db8:494:9d01:ba27:ebff:feb6:f293  ff02::1%eth0
----

`-c 2` 代表发送两个回应请求

`-I` 用IP地址，它设置了接口和echo请求的源地址，有必要选择接口的IP地址，
`eth0` 是不够的-答案应该是本地链路地址(`fe80::/10`)，我们需要全局或本地单播地址。

`ff02::1` 是链路上所有节点的众所周知的多播地址，因此它的行为类似于本地广播，通常在 `/etc/hosts` 中定义，因此您也可以使用名称 (`ip6-allnodes` 或 `ipv6-allnodes`) 来代替文字地址。

一些较新的系统希望多播地址后面有接口ID。

----
ping -c 2 -I 2001:db8:494:9d01:ba27:ebff:feb6:f293 ip6-allnodes
PING ip6-allnodes(ip6-allnodes (ff02::1)) from 2001:db8:494:9d01:ba27:ebff:feb6:f293 : 56 data bytes
64 bytes from 2001:db8:494:9d01:ba27:ebff:feb6:f293: icmp_seq=1 ttl=64 time=0.597 ms
64 bytes from witz.fritz.box (2001:db8:494:9d01:728b:cdff:fe7d:a2e): icmp_seq=1 ttl=255 time=1.05 ms (DUP!)
64 bytes from raspberrypi4.fritz.box (2001:db8:494:9d01:dea6:32ff:fe23:6be1): icmp_seq=1 ttl=64 time=1.05 ms (DUP!)
64 bytes from 2001:db8:494:9d01:da37:beff:fefd:f09d (2001:db8:494:9d01:da37:beff:fefd:f09d): icmp_seq=1 ttl=255 time=1.05 ms (DUP!)
64 bytes from fusion.fritz.box (2001:db8:494:9d01:1e6f:65ff:fec9:8746): icmp_seq=1 ttl=255 time=2.12 ms (DUP!)
64 bytes from fritz.box (2001:db8:494:9d01:464e:6dff:fe72:8a08): icmp_seq=1 ttl=64 time=2.62 ms (DUP!)
64 bytes from raspberrypi.fritz.box (2001:db8:494:9d01:ba27:ebff:feb6:f293): icmp_seq=2 ttl=64 time=0.480 ms

--- ip6-allnodes ping statistics ---
2 packets transmitted, 2 received, +5 duplicates, 0% packet loss, time 1001ms
rtt min/avg/max/mdev = 0.480/1.283/2.623/0.735 ms
----

这将导致您的(W)LAN链路上所有节点的回复，以及相关的DNS名称。

排除您自己的IP( 这里是 `2001:db8:494:9d01:ba27:ebff:feb6:f293` ),
然后检查其他IP，尝试通过SSH连接它们。

----
ssh pi@2001:db8:494:9d01:dea6:32ff:fe23:6be1
The authenticity of host '2001:db8:494:9d01:dea6:32ff:fe23:6be1 (2001:db8:494:9d01:dea6:32ff:fe23:6be1)' can't be established.
ECDSA key fingerprint is SHA256:DAW68oen42TdWDyrOycDZ1+y5ZV5D81kaVoi5FnpvoM.
Are you sure you want to continue connecting (yes/no)? yes
Warning: Permanently added '2001:db8:494:9d01:dea6:32ff:fe23:6be1' (ECDSA) to the list of known hosts.
pi@2001:db8:494:9d01:dea6:32ff:fe23:6be1's password:
Linux raspberrypi4 4.19.75-v7l+ #1270 SMP Tue Sep 24 18:51:41 BST 2019 armv7l

...

pi@raspberrypi4:~ $
----

[[getting-the-ip-address-of-a-raspberry-pi-using-your-smartphone]]
==== 通过你的智能手机获取Raspberry Pi的IP地址

Fing应用程序是一款免费的智能手机网络扫描仪。 在 https://play.google.com/store/apps/details?id=com.overlook.android.fing[Android] 和 https://itunes.apple.com/gb/app/fing-network-scanner/id430921107?mt=8[iOS] 系统中均可以使用。

您的手机和您的Raspberry Pi必须在同一个网络上，因此请将您的手机连接到正确的无线网络。

打开Fing应用程序时，触摸屏幕右上角的刷新按钮。几秒钟后，您将获得一个列表，其中包含连接到您网络的所有设备。向下滚动到制造商为 "Raspberry Pi" 的条目。您将在条目的左下角看到IP地址，在右下角看到MAC地址。
