[[samba-smbcifs]]
== Samba (SMB/CIFS)

Samba 是 SMB/CIFS 网络协议的实现，Microsoft Windows 设备使用它来提供对文件、打印机和串行端口的共享访问。

您可以使用Samba挂载从Windows计算机共享的文件夹，使其显示在Raspberry Pi上，或者从Raspberry Pi共享文件夹，以便Windows机器可以访问它。

[[installing-samba-support]]
=== 安装 Samba 支持

默认情况下，Raspberry Pi OS不包括CIFS / Samba支持，但可以添加。以下命令将安装使用 Samba 作为服务器或客户端所需的所有组件。

[,bash]
----
sudo apt update
sudo apt install samba samba-common-bin smbclient cifs-utils
----

[[mount-a-folder-shared-from-windows]]
=== 挂载从窗口共享的文件夹

首先，您需要在Windows设备上共享一个文件夹。这是一个相当复杂的过程！

[[turn-on-sharing]]
==== 开启共享

. 打开网络和共享中心，方法是右键单击系统菜单并选择它
. 单击 *Change advanced sharing settings*
. 选择 *Turn on network discovery*
. 选择 *Turn on file and printer sharing*
. 保存更改

[[share-the-folder]]
==== 共享文件夹

您可以共享所需的任何文件夹，但对于此示例，只需创建一个名为 `share`的文件夹。

. 在桌面上创建文件夹 `share` 。
. 右键单击此文件夹然后选择 *Properties*.
. 单击 *Sharing* 页签, 然后选择 *Advanced Sharing* 按键
. 选择 *Share this folder*; 默认情况下，共享名称是文件夹的名称
. 单击 *Permissions* 按键
. 6. 对于此示例，请选择 *Everyone* 和 *Full Control* (如果需要，可以将访问权限限制为特定用户); 完成后单击 *OK* w, 然后再次单击 *OK* 以离开 *Advanced Sharing* 页面
. 单击 *Security* 页签, 因为我们现在需要配置相同的权限
. 选择与 *Permissions* 页签相同的设置, 并在必要时添加所选用户
. 单击 *OK*

该文件夹现在应该已共享。

[[windows-10-sharing-wizard]]
==== Windows 10 共享向导

在 Windows 10 上，有一个共享向导可以帮助完成其中一些步骤。

. 从“开始”栏运行“计算机管理”应用程序
. 选择 *共享文件夹* 文件夹, 然后选择 *共享*
. 右键单击并选择 *新建共享*, 这将启动共享向导;单击 *下一步*
. 选择要共享的文件夹，然后单击 *下一步*
. 单击 *下一步* 以使用所有共享默认值
. 选择 *自定义* 并设置所需的权限，然后选择 *OK*, 最后单击 *Finish*

[[mount-the-folder-on-the-raspberry-pi]]
==== 将文件夹挂载在 Raspberry Pi上

在 Linux 中 *挂载* 是将文件夹附加到某个位置的过程，因此首先我们需要该位置。

[,bash]
----
mkdir windowshare
----

现在，我们需要将远程文件夹挂载到该位置。远程文件夹是 Windows PC 的主机名或 IP 地址，以及共享时使用的共享名称。我们还需要提供将用于访问远程计算机的 Windows 用户名。

[,bash]
----
sudo mount.cifs //<hostname or IP address>/share /home/pi/windowshare -o user=<name>
----

您现在应该能够在Raspberry Pi上查看Windows共享的内容。

[,bash]
----
cd windowshare
ls
----

[[host-is-down-error]]
==== "主机已关闭" 错误

此错误是由两种因素共同导致的：SMB 协议版本不匹配，以及 Linux 上的 CIFS 客户端返回误导性错误消息。为了解决这个问题，需要将版本条目添加到 mount 命令中。默认情况下，Raspberry Pi OS 将仅使用与 Windows 7 及更高版本兼容的 2.1 及更高版本。较旧的设备（包括某些 NAS）可能需要版本 1.0：

----
sudo mount.cifs //IP/share /mnt/point -o user=<uname>,vers=1.0
----

您可能需要尝试不同的版本以与服务器版本匹配。可能的值为：

|===
| 版本 | 描述

| 1.0
| 经典 CIFS/SMBv1 协议

| 2.0
| SMBv2.002 协议。Windows Vista Service Pack 1 和 Windows Server 2008

| 2.1
| SMBv2.1 协议。 Microsoft Windows 7 和 Windows Server 2008R2

| 3.0
| SMBv3.0 协议。  Microsoft Windows 8 和 Windows Server 2012

| 3.02
| SMBv3.0.2 协议。 Microsoft Windows 8.1 和 Windows Server 2012R2

| 3.11
| SMBv3.1.1 协议。 Microsoft Windows 10 和 Windows Server 2016

| 3
| SMBv3.0 协议版本及以上
|===

[[sharing-a-folder-from-your-raspberry-pi]]
=== 为Raspberry Pi共享文件夹

首先，创建一个共享文件夹。本示例在当前用户的 `home` 文件夹中创建一个名为 `shared`的文件夹，并假设当前用户是pi。

[,bash]
----
cd ~
mkdir shared
chmod 0740 shared
----

现在我们需要告诉Samba有一个 `pi` 用户在访问那个文件夹。当被询问时，输入 `pi` 用户的密码 - 这可以是默认密码，但这是众所周知的，为了更好的安全性应该更改。

[,bash]
----
sudo smbpasswd -a pi
----

现在我们需要告诉 Samba 使用 Samba 配置文件共享此文件夹。

[,bash]
----
sudo nano /etc/samba/smb.conf
----

在文件末尾，添加以下内容以共享文件夹，并授予远程用户读/写权限：

----
[share]
    path = /home/pi/shared
    read only = no
    public = yes
    writable = yes
----

在同一文件中，找到该 `workgroup` 行，如有必要，将其更改为本地 Windows 网络的工作组的名称。

[,bash]
----
workgroup = <your workgroup name here>
----

这应该足以共享文件夹。在您的 Windows 设备上，当您浏览网络时，应该会出现该文件夹，并且您应该能够连接到它。
