[[secure-shell-from-linux-or-mac-os]]
== 来自 Linux 或 Mac OS的安全Shell

您可以使用SSH从Linux桌面、另一个Raspberry Pi或Apple Mac连接到您的Raspberry Pi，而无需安装其他软件。

在您的电脑上打开一个终端窗口，将 `<IP>` 替换为您尝试连接的Raspberry Pi的IP地址

----
ssh pi@<IP>
----

当连接正常时，您会看到一个安全/真实性警告。输入 `yes` 继续。您只会在第一次连接时看到此告警。

NOTE: 如果您收到 `连接超时错误` ，很可能您输入了错误的Raspberry Pi IP地址。

WARNING: 如果您的Raspberry Pi获取了您的电脑之前连接过的设备的IP地址(即使这是在另一个网络上)，您可能会收到警告，并被要求从已知设备列表中清除该记录。遵循这个指令并再次尝试ssh命令应该会成功。

接下来将提示您输入 `pi` 登录的密码: Raspberry Pi操作系统上的默认密码是 `raspberry` 。

出于安全原因，强烈建议在Raspberry Pi上更改默认密码(另外，如果密码为空，则不能通过ssh登录)。您现在应该能够看到Raspberry Pi提示符，它与Raspberry Pi上的提示符完全相同。

如果您已经在Raspberry Pi上设置了另一个用户，您可以用同样的方式连接到它，用您自己的用户名替换用户名，例如 `eben@192.168.1.5` 。

----
pi@raspberrypi ~ $
----

您现在远程连接到Raspberry Pi，并且可以执行命令。

[discrete]
=== 转发 X11

您还可以通过SSH转发X会话，以允许使用图形应用程序，方法是使用 `-Y` 标志:

[,bash]
----
ssh -Y pi@192.168.1.5
----

NOTE: 默认情况下， https://support.apple.com/en-gb/HT201341[macOS]上不再安装X11， 因此你必须 https://www.xquartz.org/[下载] 并安装它。

现在您像以前一样在命令行上，但是您能够打开图形窗口。例如，输入:

[,bash]
----
geany &
----

将在本地桌面的窗口中打开Geany编辑器。

