[[passwordless-ssh-access]]
== 无密码 SSH访问

可以将您的Raspberry Pi配置为允许从另一台计算机访问，而无需在每次连接时提供密码。为此，您需要使用SSH密钥而不是密码。要生成SSH密钥:

[[checking-for-existing-ssh-keys]]
=== 检查现有的 SSH 密钥

首先，检查您用来连接Raspberry Pi的计算机上是否已经有密钥:

[,bash]
----
ls ~/.ssh
----

如果您看到名为 `id_rsa.pub` 或 `id_dsa.pub` 的文件，那么您已经设置了密钥，因此您可以跳过下面的 '生成新的SSH密钥' 操作步骤。

[[generate-new-ssh-keys]]
=== 生成新的SSH密钥

要生成新的SSH密钥，请输入以下命令:

[,bash]
----
ssh-keygen
----

输入该命令后，将询问您保存密钥的位置。我们建议将其保存在默认位置 (`~/.ssh/id_rsa`) 。

您还将被要求输入一个密码，这是可选的。密码短语用于加密私有SSH密钥，这样，如果其他人复制了密钥，他们就无法冒充您来获得访问权限。如果您选择使用密码，请在此处键入并按 `Enter`键，然后在出现提示时再次键入。如果没有密码，请将该字段留空。

现在看看你的 `.ssh` 目录:

[,bash]
----
ls ~/.ssh
----

您应该会看到文件 `id_rsa` 和 `id_rsa.pub`:

----
authorized_keys  id_rsa  id_rsa.pub  known_hosts
----

 `id_rsa` 文件是您的私钥。把这个保存在你的电脑上。

 `id_rsa.pub` 文件是您的公钥。这是您与所连接的机器共享的内容:在本例中是您的Raspberry Pi。当您尝试连接的机器匹配您的公钥和私钥时，它将允许您连接。

看一看您的公钥，看看它是什么样子的:

[,bash]
----
cat ~/.ssh/id_rsa.pub
----

它应该采用以下形式:

[,bash]
----
ssh-rsa <REALLY LONG STRING OF RANDOM CHARACTERS> user@host
----

[[copy-your-public-key-to-your-raspberry-pi]]
=== 将你的密钥复制到 Raspberry Pi上

使用您将要连接的计算机，通过SSH将公钥附加到Raspberry Pi上的 `authorized_keys` 文件:

[,bash]
----
ssh-copy-id <USERNAME>@<IP-ADDRESS>
----

NOTE: 在此步骤中，您需要使用您的密码进行身份验证。

或者，如果您的系统上没有 `ssh-copy-id` ，您可以通过ssh手动复制文件:

[,bash]
----
cat ~/.ssh/id_rsa.pub | ssh <USERNAME>@<IP-ADDRESS> 'mkdir -p ~/.ssh && cat >> ~/.ssh/authorized_keys'
----

如果您看到消息 `ssh: 连接到主机 <IP-地址> 端口22: 连接被拒绝，并且您知道 `IP-地址` 是正确的, 那么您可能没有在您的Raspberry Pi上启用SSH。 在Raspberry Pi的终端窗口中运行 `sudo raspi-config` ，启用SSH，然后再次尝试复制文件。

现在尝试 `ssh <USER>@<IP-ADDRESS>` ，您应该可以在没有密码提示的情况下连接。

如果您看到消息 "Agent admitted failure to sign using the key" ，则将您的RSA或DSA身份添加到身份认证代理 `ssh-agent` ，然后执行以下命令:

[,bash]
----
ssh-add
----

NOTE: 您还可以使用 xref:remote-access.adoc#using-secure-copy[`scp`] (安全复制) 命令通过SSH发送文件。

[[adjust-directory-permissions]]
=== 调整目录权限

如果您在完成上述步骤后仍无法建立连接，则您的目录权限可能有问题。首先，您需要检查日志中是否有错误:

[,bash]
----
tail -f /var/log/secure
# might return:
Nov 23 12:31:26 raspberrypi sshd[9146]: Authentication refused: bad ownership or modes for directory /home/pi
----

如果日志显示 `认证被拒绝: 目录 /home/pi` 的所有权或模式不正确，则您的主目录存在权限问题。SSH需要
主目录和 `~/.ssh` 目录没有组的写访问权限。你可以使用 `chmod`调整权限。


[,bash]
----
chmod g-w $HOME
chmod 700 $HOME/.ssh
chmod 600 $HOME/.ssh/authorized_keys
----

现在只有用户自己可以访问 `.ssh` 和 `.ssh/authorized_keys` ，其中存储了远程机器的公钥。

[discrete]
=== 将密码存储在macOS密钥串中

如果您使用的是macOS，并且在验证您的新密钥允许您连接后，您可以选择将密钥的密码储存在macOS密钥串中。这允许您无需输入密码即可连接到您的Raspberry Pi。

运行以下命令将其储存在密钥串中:

[,bash]
----
ssh-add -K ~/.ssh/id_rsa
----

[NOTE]
====
从macOS Monterey开始 `-K` 标志已被弃用，并被 `--apple-use-keychain` 标志所取代。
====
