[[ssh]]
== 设置SSH 服务器

您可以使用安全shell(SSH)协议从同一网络上的另一台计算机或设备远程访问Raspberry Pi的命令行。

您只能访问命令行，而不能访问整个桌面环境。如需完整的远程桌面，请参见 xref:remote-access.adoc#vnc[VNC]。

[[set-up-your-local-network]]
=== 设置本地网络

确定您的Raspberry Pi已正确设置和连接。如果您使用无线网络，可以通过桌面用户界面或从命令行使用来启用。如果您不使用无线连接，请将您的Raspberry Pi直接插入路由器。

NOTE: 您需要记下您的Raspberry Pi的IP地址，以便以后连接到它。使用 `ifconfig` 命令将显示有关当前网络状态的信息，包括IP地址，或者您可以使用 `hostname -I` 来显示与设备相关联的IP地址。

[[enabling-the-server]]
=== 启用服务器Server

Raspberry Pi OS默认禁用SSH服务器。可以从桌面手动启用它:

. 从 `Preferences` 菜单启动 `Raspberry Pi Configuration` 
. 导航至 `Interfaces` 选项卡
. 选择 `Enabled` 旁边的 `SSH`
. 单击 `OK`

或者，您可以使用 xref:configuration.adoc#raspi-config[raspi-config] 应用程序从终端启用它，

. 在终端窗口输入 `sudo raspi-config` 
. 选择 `Interfacing Options`
. 导航并选择 `SSH`
. 选择 `Yes`
. 选择 `Ok`
. 选择 `Finish`

NOTE: 对于无头设置，可以通过将名为 `ssh`的文件(没有任何扩展名)放在SD卡的启动分区上来启动SSH。 当Raspberry Pi启动时，它会寻找 `ssh` 文件。 如果找到了，SSH将被启用，文件将被删除。文件的内容无关紧要；它可以包含文本，也可以什么都不包含。

NOTE: 对于除 `ssh` 外的无头设置，你还需要一个 `userconf.txt` 文件, 其中包含一个字符串 `username:encryptedpassword`。 请参考Raspberry Pi的无头设置的讨论中关于 xref:configuration.adoc#configuring-a-user[配置用户r] 的部分。

WARNING: 当在可能连接到互联网的Raspberry Pi上启用SSH时，您应该确保您的密码不会被轻易破解。
