[[vnc]]
== 虚拟网络计算 (VNC)
:experimental:

有时直接在Raspberry Pi上工作并不方便。也许您想通过遥控器从另一台设备对其进行处理。

VNC 是一种图形桌面共享系统，允许您从另一台计算机或移动设备（运行 VNC 查看器）远程控制一台计算机（运行 VNC 服务器）的桌面界面。VNC 查看器将键盘和鼠标或触摸事件传输到 VNC 服务器，并接收屏幕更新作为回报。

您将在计算机或移动设备的窗口中看到Raspberry Pi的桌面。您将能够控制它，就像您在处理Raspberry Pi本身一样。

RealVNC 的 VNC Connect 包含在 Raspberry Pi OS 中。它由VNC服务器和VNC Viewer组成，VNC服务器允许您远程控制Raspberry Pi，后者允许您根据需要从Raspberry Pi远程控制台式计算机。

您必须先启用 VNC 服务器，然后才能使用它。默认情况下，VNC 服务器可让您远程访问在 Raspberry Pi 上运行的图形桌面，就像您坐在它前面一样。

但是，您也可以使用 VNC 服务器来获取对 Raspberry Pi 的图形远程访问，如果它是无头的或未运行图形桌面。有关此内容的更多信息，请参阅下面的 *创建虚拟桌面*。

[[installing-vnc-on-raspberry-pi]]
=== 在 Raspberry Pi上安装VNC

VNC已经安装在完整的Raspberry Pi操作系统映像上，可以通过其他版本的首选项菜单中的 `推荐软件` 进行安装。

如果您不使用桌面，则可以从命令行安装它，如下所示：

[,bash]
----
sudo apt update
sudo apt install realvnc-vnc-server realvnc-vnc-viewer
----

[[enabling-the-vnc-server]]
=== 启用 VNC 服务器

您可以通过图形方式或在命令行中执行此操作。

[[enabling-vnc-server-graphically]]
==== 以图形方式启用 VNC 服务器

* 在Raspberry Pi上，启动到图形桌面。
* 选择 menu:Menu[Preferences > Raspberry Pi Configuration > Interfaces].
* 确保已 *启用*  *VNC*。

[[enabling-vnc-server-at-the-command-line]]
==== 以命令行方式启用VNC服务器

您可以使用 xref:configuration.adoc#raspi-config[raspi-config]在命令行启用 VNC 服务器：

[,bash]
----
sudo raspi-config
----

现在，通过执行以下操作启用 VNC 服务器：

* 导航至 *Interfacing Options*。
* 向下滚动并选择 menu:VNC[Yes]。

[[connecting-to-your-raspberry-pi]]
=== 连接到 Raspberry Pi

有两种方法可以连接到Raspberry Pi。您可以使用其中之一或两者，具体取决于最适合您的方法。

[[establishing-a-direct-connection]]
==== 建立直接连接

直接连接既快速又简单，前提是您加入与Raspberry Pi相同的专用本地网络。例如，这可能是家中、学校或办公室中的有线或无线网络。

* 在Raspberry Pi (使用终端窗口或通过SSH)， 使用e xref:remote-access.adoc#ip-address[这些说明] 或运行 `ifconfig` 以发现你的私有IP地址。
* 在您将用于控制的设备上，下载 VNC 查看器。 为了获得最佳效果，请使用RealVNC的 https://www.realvnc.com/download/viewer/[兼容性应用程序] 。
* 在VNC查看器中输入Raspberry Pi的私有IP地址：

[[establishing-a-cloud-connection]]
==== 建立云连接

您有权免费使用RealVNC的云服务，前提是远程访问仅用于教育或非商业目的。

云连接方便且端到端加密。强烈建议使用它们通过互联网连接到Raspberry Pi。没有防火墙或路由器重新配置，您不需要知道Raspberry Pi的 IP 地址，也不需要提供静态地址。

* 注册一个 https://www.realvnc.com/raspberrypi/#sign-up[RealVNC 账户] : 它是免费的，只需要几秒钟。
* 在Raspberry Pi上使用新的 RealVNC 帐户凭据登录 VNC 服务器：
* 在您将用于控制的设备上，下载 VNC 查看器。您 *必须* 使用RealVNC的 https://www.realvnc.com/download/viewer/[兼容性应用程序] 。
* 使用相同的 RealVNC 帐户凭据登录 VNC 查看器，然后点击或单击以连接到您的Raspberry Pi：

[[authenticating-to-vnc-server]]
==== 向 VNC 服务器进行身份验证

要完成直接连接或云连接，您必须向 VNC 服务器进行身份验证。

如果您从 RealVNC https://www.realvnc.com/download/viewer/[兼容的VNC Viewer 应用程序] 进行连接，请输入您通常用于登录 Raspberry Pi 上的用户帐户的用户名和密码。默认情况下，这些凭据是 `pi` 和 `raspberry`。

如果您从非 RealVNC Viewer 应用程序进行连接，则首先需要降级 VNC 服务器的身份验证方案，指定 VNC Server 独有的密码，然后输入该密码。

* 	如果您在Raspberry Pi前面并且可以看到其屏幕，请打开Raspberry Pi上的 VNC 服务器对话框，选择 menu:Menu[Options > Security], 再从 *Authentication* 下拉列表中选择 *VNC password* 。
* *或者* 如果您要从命令行远程配置Raspberry Pi，则要对服务模式（Raspberry Pi的默认配置）进行更改：
 ** 打开 `/root/.vnc/config.d/vncserver-x11` 配置文件。
 ** 替换 `Authentication=SystemAuth` 为 `Authentication=VncAuth` 并保存文件。
 ** 在命令行中运行 `sudo vncpasswd -service`。这将提示您设置密码，并将其插入到以服务模式运行的VNC服务器的正确配置文件中。
 ** 重启 VNC 服务器。

[[using-directly-rendered-applications]]
=== 使用直接呈现的应用程序

您可以远程访问使用直接渲染叠加的应用程序，例如：文本控制台、Raspberry Pi相机模块等。

要启用此功能，请执行以下操作：

* 在Raspberry Pi上, 打开 VNC 服务器对话框。
* 导航至 menu:Menu[Options > Troubleshooting] 并选择 *Enable experimental direct capture mode*.
* 在您将用于控制的设备上，运行 VNC 查看器并连接。
+
NOTE: 必须重新启动现有连接才能使这些更改生效。

请注意，直接屏幕捕获是一项实验性功能。 如果您从台式计算机进行连接，并且鼠标移动似乎不稳定，请尝试按 *F8* 打开 VNC 查看器快捷菜单并选择 *Relative Pointer Motion*。

[[creating-a-virtual-desktop]]
=== 创建虚拟桌面

如果您的Raspberry Pi是无头的（即没有插入显示器）或控制机器人，则它不太可能运行图形桌面。

VNC 服务器可以为您创建 *虚拟桌面* ，让您按需进行图形远程访问。此虚拟桌面仅存在于Raspberry Pi的内存中：

要创建并连接到虚拟桌面，请执行以下操作：

* 在 Raspberry Pi上（使用终端或通过 SSH）, 运行 `vncserver`。 记下VNC服务器将打印到您的终端的IP地址/显示编号 (例如 `192.167.5.149:1`).
* 	在您将用于控制的设备上，将此信息输入 https://www.realvnc.com/download/viewer/[VNC 查看器]。

要销毁虚拟桌面，请运行以下命令：

[,bash]
----
vncserver -kill :<display-number>
----

这还将停止与此虚拟桌面的任何现有连接。
