[[camera-serial-interface-2-csi2-unicam]]
== 相机串行接口 2 （CSI2） “Unicam”

Raspberry Pi系列上使用的SoC都有两个相机接口，支持CSI-2 D-PHY 1.1或CCP2（紧凑型相机端口2）源。该接口的代号为“Unicam”。Unicam的第一个实例支持2个CSI-2数据通道，而第二个实例支持4个。每条通道可以以高达1Gbit/s（DDR，因此最大链路频率为500MHz）运行。

但是，Raspberry Pi的正常变体仅公开第二个实例，并且仅将2个数据通道路由到相机连接器。计算模块范围从两个外设路由出所有通道。

[[software-interfaces]]
=== 软件接口

有 3 个独立的软件接口可用于与 Unicam 外设通信：

[[firmware]]
==== 固件

NOTE: 此接口仅在使用旧版相机堆栈时可用。

闭源GPU固件具有Unicam驱动程序和三个摄像头传感器以及一个桥接芯片。它们是Raspberry Pi Camera v1.3（Omnivision OV5647），Raspberry Pi Camera v2.1（Sony IMX219），Raspberry Pi HQ相机（Sony IMX477），以及东芝TC358743 HDMI->CSI2桥接芯片不支持的驱动程序。不支持更新的相机，例如相机模块 3（索尼 IMX708）。

此驱动程序将源驱动程序、Unicam、ISP 和调谐器控制集成到一个完整的相机堆栈中，提供经过处理的输出图像。它可以通过MMAL，OpenMAX IL和V4L2使用bcm2835-v4l2内核模块。此接口仅支持Raspberry Pi相机。

[[software-interfaces]]
==== MMAL rawcam 组件

NOTE: 此接口仅在使用旧版相机堆栈时可用。

这是 V4L2 驱动程序可用之前的临时选项。MMAL 组件vc.ril.rawcam允许以与 V2L4 驱动程序相同的方式接收原始 CSI2 数据，但所有源配置都必须由用户空间通过源所需的任何接口完成。raspiraw应用程序可在https://github.com/raspberrypi/raspiraw[github]上使用。它使用此组件和OV2、IMX5647和ADV219M的标准I7282C寄存器集来支持流传输。

[[software-interfaces]]
==== V4L2

NOTE: Unicam 的 V4L2 接口仅在使用libcamera 时可用。

有一个完全开源的内核驱动程序可用于Unicam块，是叫做 BCM2835-UNICAM 的内核模块。这接口到 V4L2 子设备驱动程序，为源提供原始帧。此 bcm2835-unicam 驱动程序控制传感器，并配置 CSI-2 接收器，以便外设将原始帧（在 Debayer 之后）写入 SDRAM，使 V4L2 交付给应用程序。除了能够将CSI-2拜耳格式解压缩为16位/像素之外，图像源（例如相机传感器）和将图像数据放置在SDRAM中的bcm2835-unicam之间没有图像处理。

----
|------------------------|
|     bcm2835-unicam     |
|------------------------|
     ^             |
     |      |-------------|
 img |      |  Subdevice  |
     |      |-------------|
     v   -SW/HW-   |
|---------|   |-----------|
| Unicam  |   | I2C or SPI|
|---------|   |-----------|
csi2/ ^             |
ccp2  |             |
    |-----------------|
    |     sensor      |
    |-----------------|
----

Mainline Linux有一系列现有的驱动程序。Raspberry Pi内核树有一些额外的驱动程序和设备树覆盖来配置它们，这些驱动程序和设备树覆盖都已经过测试并确认可以工作。它们包括：

|===
| 设备 | 类型 | 备注

| Omnivision OV5647
| 5MP Camera
| Original Raspberry Pi Camera

| Sony IMX219
| 8MP Camera
| Revision 2 Raspberry Pi camera

| Sony IMX477
| 12MP Camera
| Raspberry Pi HQ camera

| Sony IMX708
| 12MP Camera
| Raspberry Pi Camera Module 3

| Toshiba TC358743
| HDMI to CSI-2 bridge
|

| Analog Devices ADV728x-M
| Analog video to CSI-2 bridge
| No interlaced support

| Infineon IRS1125
| Time-of-flight depth sensor
| Supported by a third party
|===

由于子设备驱动程序也是内核驱动程序，因此具有标准化的API，因此第三方可以自由地为他们选择的任何来源编写自己的驱动程序。

[[software-interfaces]]
=== 开发第三方驱动程序

这是推荐的通过Unicam接口的方法。

为打算与 bcm2835-unicam 模块一起使用的新设备开发驱动程序时，需要驱动程序和相应的设备树覆盖。理想情况下，驱动程序应提交到  http://vger.kernel.org/vger-lists.html#linux-media[linux 媒体] 邮件列表进行代码审查并合并到主线中，然后移动到 https://github.com/raspberrypi/linux[Raspberry Pi 内核树] ，但可能会有的例外情况是驱动程序被审查并直接合并到 Raspberry Pi 内核。

请注意，所有内核驱动程序都是在GPLv2许可下授权的，因此源代码*必须*是可用的。只运输二进制模块违反了GPLv2许可证，Linux内核就是在GPL v2许可证下获得许可的。

bcm2835-unicam 旨在尝试适应当前在主线 Linux 内核中找到的所有类型的 CSI-2 源驱动程序。从广义上讲，这些可以分为相机传感器和桥接芯片。桥接芯片允许在其他格式和 CSI-2 之间进行转换。

[[software-interfaces]]
==== 相机传感器

相机传感器的驱动程序负责设备的所有配置，通常通过 I2C 或 SPI。通常，将现有驱动程序作为基础并根据需要对其进行修改通常更容易，而不是从头开始编写驱动程序。

https://github.com/raspberrypi/linux/blob/rpi-5.4.y/drivers/media/i2c/imx219.c[IMX219 驱动程序]是一个很好的起点。此驱动程序支持 8 位和 10 位Bayer读出，因此枚举帧格式和帧大小稍微复杂一些。


传感器通常支持 https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/control.html[V4L2 用户控件]。并非所有这些控件都需要在驱动程序中实现。IMX219 驱动程序仅实现下面列出的一小部分，其实现由imx219_set_ctrl函数处理。

* `V4L2_CID_PIXEL_RATE` / `V4L2_CID_VBLANK` / `V4L2_CID_HBLANK`: 允许应用程序设置帧速率。
* `V4L2_CID_EXPOSURE`: 以线条为单位设置曝光时间。应用程序需要使用 `V4L2_CID_PIXEL_RATE`, `V4L2_CID_HBLANK`,  和帧宽度来计算行时间。
* `V4L2_CID_ANALOGUE_GAIN`: 以传感器特定单位表示的模拟增益。
* `V4L2_CID_DIGITAL_GAIN`: 传感器特定单元中的可选数字增益。
* `V4L2_CID_HFLIP / V4L2_CID_VFLIP`: 水平或垂直翻转图像。请注意，此操作可能会更改帧中数据的Bayer顺序，就像 imx219 上的情况一样。
* `V4L2_CID_TEST_PATTERN` / `V4L2_CID_TEST_PATTERN_*`:支持从传感器输出各种测试模式。这对调试很有用。
如果是 IMX219，其中许多控件直接映射到传感器本身的寄存器写入。

可以在 libcamera 的https://git.linuxtv.org/libcamera.git/tree/Documentation/sensor_driver_requirements.rst[传感器驱动程序要求]以及  https://datasheets.raspberrypi.com/camera/raspberry-pi-camera-guide.pdf[Raspberry Pi 相机调整指南]的第 3 章中找到进一步的指导。

[[software-interfaces]]
===== 设备树

设备树用于选择传感器驱动程序并配置参数，例如 CSI-2 通道数、连续时钟通道操作和链路频率（通常仅支持一个）。

* 5.4内核的IMX219https://github.com/raspberrypi/linux/blob/rpi-5.4.y/arch/arm/boot/dts/overlays/imx219-overlay.dts[设备树覆盖图]

[[software-interfaces]]
==== 桥接芯片

这些设备将传入的视频流（例如HDMI或复合）转换为Raspberry Pi CSI-2接收器可以接受的CSI-2流。

处理桥接芯片更为复杂，因为与相机传感器不同，它们必须响应输入信号并将其报告给应用程序。

处理桥接芯片的机制可以大致分为模拟或数字。

在下面的部分中使用`ioctl`时，`ioctl`名称中的`_S_`表示它是一个set函数，而`_G_`是一个get函数，并且`_ENUM`枚举一组允许的值。

[[software-interfaces]]
===== 模拟视频源

模拟视频源使用标准`ioctls`来检测和设置视频标准。 https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-g-std.html[`VIDIOC_G_STD`], https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-g-std.html[`VIDIOC_S_STD`], https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-enumstd.html[`VIDIOC_ENUMSTD`], and https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-querystd.html[`VIDIOC_QUERYSTD`]

选择错误的标准通常会导致图像损坏。设定标准通常也会设定V4L2捕获队列的分辨率。它不能通过FMT视频设置。一般来说，通过`VIDIOC_QUERYSTD`请求检测到的标准，然后在流式传输之前用`VIDIOC_S_STD`设置它是一个好主意。

[[software-interfaces]]
===== 数字视频源

对于HDMI等数字视频源，有一组备用调用允许指定所有数字时序参数 (https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-g-dv-timings.html[`VIDIOC_G_DV_TIMINGS`], https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-g-dv-timings.html[`VIDIOC_S_DV_TIMINGS`], https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-enum-dv-timings.html[`VIDIOC_ENUM_DV_TIMINGS`], and https://www.kernel.org/doc/html/latest/userspace-api/media/v4l/vidioc-query-dv-timings.html[`VIDIOC_QUERY_DV_TIMINGS`]).。

与模拟网桥一样，计时通常会固定V4L2捕获队列的分辨率，在流式传输之前调用`VIDIOC_S_DV_TIMINGS`和`VIDIOC_QUERY_DV_TIMINGS`的结果应确保格式正确。

根据桥接芯片和驱动器的不同，输入源的变化可能会通过`VIDIOC_SUBSCRIBE_EVENT`和`V4L2_EVENT_SOURCE_CHANGE`报告给应用。

[[software-interfaces]]
===== 当前支持的设备

Raspberry Pi Linux内核目前支持2个桥接芯片，ADI公司ADV728x-M用于模拟视频源，东芝TC358743用于HDMI源。

_模拟设备 ADV728x(A)-M 模拟视频转 CSI2 桥接器_

这些芯片将复合、S视频（Y/C）或分量（YPrPb）视频转换为单通道CSI-2接口，https://github.com/raspberrypi/linux/blob/rpi-5.4.y/drivers/media/i2c/adv7180.c[ADV7180内核驱动程序]支持这些芯片。

有关该芯片各种版本的产品详细信息，请访问模拟设备网页。

https://www.analog.com/en/products/adv7280a.html[ADV7280A], https://www.analog.com/en/products/adv7281a.html[ADV7281A], https://www.analog.com/en/products/adv7282a.html[ADV7282A]

由于当前内核V4L2实现中的一些缺失代码，选择源失败，因此Raspberry Pi内核版本向ADV7180内核驱动程序添加了一个名为dbg_input的内核模块参数，该驱动程序在每次调用`VIDIOC_S_STD`时设置输入源。在某个时候，主流将修复底层问题(内核API调用s_routing和用户空间调用`VIDIOC_S_INPUT`之间的分离),并且这个修改将被移除。

请注意，不支持接收隔行扫描视频，因此ADV7281（A）-M版本的芯片用途有限，因为它没有必要的I2P去隔行扫描模块。还要确保在选择设备时指定 -M 选项。没有它，您将获得一个无法与Raspberry Pi接口的并行输出总线。

目前尚无使用这些芯片的商用电路板，但该驱动器已通过模拟设备的https://www.analog.com/en/design-center/evaluation-hardware-and-software/evaluation-boards-kits/EVAL-ADV7282A-M.html[EVAL-ADV7282-M评估板]进行了测试

如果您使用ADV7282-M芯片变体，可以使用config.txt dtoverlay adv7282m加载该驱动程序；或者adv728x-m，参数为adv7280m=1、adv7281m=1或adv7281ma=1(如果使用不同型号)。例如

----
dtoverlay=adv728x-m,adv7280m=1
----

_东芝 TC358743 HDMI to CSI2 桥接器_

这是一个HDMI到CSI-2桥接芯片，能够以高达1080p60的速度转换视频数据。

有关此桥接芯片的信息可在https://toshiba.semicon-storage.com/ap-en/semiconductor/product/interface-bridge-ics-for-mobile-peripheral-devices/hdmir-interface-bridge-ics/detail.TC358743XBG.html[东芝网站]上找到

TC358743 将 HDMI 连接到 CSI-2 和 I2S 输出。https://github.com/raspberrypi/linux/blob/rpi-5.4.y/drivers/media/i2c/tc358743.c[TC358743内核模块]支持此功能。

该芯片支持RGB888、YUV444或YUV422等输入HDMI信号，最高可达1080p60。它可以转发RGB888，或将其转换为YUV444或YUV422，并在YUV444和YUV422之间进行任一方式转换。仅测试了RGB888和YUV422支持。使用 2 个 CSI-2 通道时，可以支持的最大速率为 RGB1080 的 30p888 或 YUV1080 的 50p422。在计算模块上使用 4 个通道时，可以以任一格式接收 1080p60。

HDMI通过接收设备通告它可以支持的所有模式的https://en.wikipedia.org/wiki/Extended_Display_Identification_Data[EDID]来协商分辨率。内核驱动程序不知道您希望接收的分辨率、帧速率或格式，因此需要由用户提供合适的文件。这是通过VIDIOC_S_EDID ioctl完成的，或者更容易地使用`v4l 2-CTL- fix-edid-checksums-set-edid =file=filename.txt`(添加-fix-edid-checksums选项意味着您不必在源文件中获得正确的校验和值)。生成所需的EDID文件(二进制EDID文件的文本六进制转储)并不太麻烦，也有工具可以生成它们，但这超出了本文的范围。

如上所述，使用`DV_TIMINGS` ioctls来配置驱动程序，以匹配传入的视频。最简单的方法是使用命令`v4l 2-CTL-set-dv-Bt-timings query`。如果您希望编写一个应用程序来处理不断变化的源，该驱动程序确实支持生成SOURCE_CHANGED事件。通过VIDIOC_S_FMT设置可以改变输出像素格式，但是只有像素格式字段会被更新，因为分辨率是由dv时序配置的。

有几个商用板将此芯片连接到Raspberry Pi。Auvidea B101 和 B102 是最广泛获得的，但也提供其他同等的电路板

使用`config.txt` dtoverlay `tc358743`加载此驱动程序。

该芯片还支持通过I2S捕获立体声HDMI音频。Auvidea 板将相关信号分解到一个接头上，该接头可以连接到 Raspberry Pi 的 40 针接头。所需的接线是：

[cols=",^,^,^"]
|===
| 信号 | B101 接头 | 40-pin 接头 | BCM GPIO

| LRCK/WFS
| 7
| 35
| 19

| BCK/SCK
| 6
| 12
| 18

| DATA/SD
| 5
| 38
| 20

| GND
| 8
| 39
| N/A
|===

除了`tc358743`覆盖外，还需要`TC 358743-音频`覆盖。这将为HDMI音频创建一个ALSA录音设备。请注意，没有音频重采样。音频的存在反映在V4L2控制TC 358743 _ CID _ AUDIO _ PRESENT/“AUDIO-PRESENT”中，输入音频的采样速率反映在V4L2控制TC 358743 _ CID _ AUDIO _ SAMPLING _ RATE/“AUDIO SAMPLING-frequency”中。在没有音频的情况下进行记录会产生警告，以不同于报告的采样率进行记录也会产生警告。