[[libcamera-and-libcamera-apps-packages]]
=== libcamera和libcamera-apps包

为方便起见，提供了许多apt包。为了访问它们，我们建议您以 xref:../computers/os.adoc#using-apt[通常的方式]使您的操作系统保持最新状态。

[[binary-packages]]
==== 二进制包

有两个libcamera-apps包可用，其中包含必要的可执行文件：

* libcamera-apps包含支持使用 X Windows 预览的完整应用程序。此软件包预装在Raspberry Pi OS的Bullseye版本中。

* libcamera-apps-lite省略 X Windows 支持，只有 DRM 预览可用。此软件包预安装在Raspberry Pi OS Lite的Bullseye版本中。

对于Bullseye用户，官方Raspberry Pi相机应该会自动检测。其他用户将需要xref:camera_software.adoc#if-you-do-need-to-alter-the-configuration[编辑他们的 /boot/config.txt] 文件，如果他们以前没有这样做过。

[[dependencies]]
==== 依赖

这些应用程序依赖于许多名为 library-name<n 的库包>其中 <n> 是一个版本号（实际上是 ABI，或应用程序二进制接口，版本），在撰写本文时为零。因此，我们有以下内容：

* libcamera0包包含libcamera库

* libepoxy0包包含libepoxy库

这些将在需要时自动安装。

[[dev-packages]]
==== 开发包

libcamera-apps可以自行重建，无需从头开始安装和构建libcamera和libepoxy。要实现这一点，应该安装以下软件包:

* libcamera-dev包含必要的libcamera头文件和资源。

* libepoxy-dev包含必要的libepoxy头文件和资源。只有当你想支持X11/GLES预览窗口时，你才需要它。

随后libcamera-apps可以从xref:camera_software.adoc#building-libcamera-apps-without-rebuilding-libcamera[ GitHub 签出并重建]。
