[[python-bindings-for-libcamera]]
=== Python 绑定libcamera

https://github.com/raspberrypi/picamera2[Picamera2库] 是基于libcamera的Picamera替代品，Picamera是Raspberry Pi传统相机堆栈的Python接口。Picamera2提供了一个易于使用的Python API。

有关 Picamera2 的文档可在  https://github.com/raspberrypi/picamera2[on Github] 和  https://datasheets.raspberrypi.com/camera/picamera2-manual.pdf[Picamera2 手册]中找到。

[[installation]]
==== 安装

Picamera2仅在Raspberry Pi OS Bullseye（或更高版本）图像（32位和64位）上受支持。

NOTE: 截至2022年9月，Picamera2预装在从Raspberry Pi下载的图片上。它可以在所有的Raspberry Pi板上运行，甚至可以运行到Pi 0，尽管在一些功能较弱的设备上，某些方面的性能可能会更差。

Picamera2 在以下设备上不受支持：

. 基于 Buster 或早期版本的映像。
. Raspberry Pi操作系统旧版映像。
. Bullseye（或更高版本）图像，其中旧相机堆栈已重新启用。

在Raspberry Pi OS映像上，Picamera2现在安装了所有GUI（Qt和OpenGL）依赖项。在Raspberry Pi OS Lite上，它是在没有GUI依赖项的情况下安装的，尽管预览图像仍然可以使用DRM / KMS显示。如果这些用户希望使用其他 X-Windows GUI 功能，他们将需要运行

----
sudo apt install -y python3-pyqt5 python3-opengl
----

NOTE: 不需要对 Picamera2 本身进行任何更改。

如果您的映像未预装 Picamera2 apt，则推荐安装和更新 Picamera2。

----
$ sudo apt update
sudo apt upgrade
----

此后，您可以使用以下方法安装Picamera2以及所有GUI（Qt和OpenGL）依赖项。

----
$ sudo apt install -y python3-picamera2
----

如果您不需要 GUI 依赖项，请使用

----
$ sudo apt install -y python3-picamera2 --no-install-recommends
----

NOTE: 如果您之前已经使用pip安装了Picamera2，那么您也应该使用命令pip3 uninstall picamera2卸载它。

NOTE: 如果已经安装了Picamera2，可以用sudo apt install-y python 3-picamera 2进行更新，或者作为完整系统更新的一部分(例如sudo apt升级)。