[[libav-integration-with-libcamera-vid]]
=== Libav 与 Libcamera-VID 的集成

libcamera-vid可以使用 FFMPEG/libav 编解码器后端对音频和视频流进行编码，并保存到本地文件或通过网络流式传输。目前，视频通过硬件H.264编码器进行编码，音频由许多可用的软件编码器进行编码。要列出可用的输出格式，请使用该ffmpeg -formats命令。

要启用 libav 后端，请使用--codec libav命令行选项。启用后，以下配置选项可用：

----
    --libav-format,     libav output format to be used <string>
----

设置要使用的 libav 输出格式。这些输出格式可以指定为容器（例如 mkv、mp4、avi）或流输出（例如 h264 或 mpegts）。如果未提供此选项，libav 将尝试从命令行参数-o指定的文件名推断输出格式。

示例：要将视频保存在 mkv 容器中，以下命令是等效的：

----
libcamera-vid --codec libav -o test.mkv
libcamera-vid --codec libav --libav-format mkv -o test.raw
----

----
    --libav-audio,     Enable audio recording
----

设置此选项可与视频流一起启用音频编码。启用音频编码后，必须使用支持音频的输出格式（例如 mpegts、mkv、mp4）。

----
    --audio-codec,     Selects the audio codec <string>
----

选择用于编码的软件音频编解码器。默认情况下使用。要列出可用的音频编解码器，请使用该aacffmpeg -codec命令。

----
    --audio-bitrate,     Selects the audio bitrate <number>
----

设置音频编码比特率（以位/秒为单位）。

Example: 要使用mp2编解码器以16千位/秒的速度录制音频，请使用lib camera-vid-codec libav-o test.mp4-audio _ codec MP2-audio-bitrate 16384

----
    --audio-samplerate,     Set the audio sampling rate <number>
----

以 Hz 为单位设置音频采样率以进行编码。设置为 0（默认值）以使用输入采样率。

----
    --audio-device,     Chooses an audio recording device to use <string>
----

选择要用于音频录制的 ALSA 输入设备。可以使用以下命令获取音频设备字符串：

----
pi@pi4:~ $ pactl list | grep -A2 'Source #' | grep 'Name: '
    Name: alsa_output.platform-bcm2835_audio.analog-stereo.monitor
    Name: alsa_output.platform-fef00700.hdmi.hdmi-stereo.monitor
    Name: alsa_output.usb-GN_Netcom_A_S_Jabra_EVOLVE_LINK_000736B1214E0A-00.analog-stereo.monitor
    Name: alsa_input.usb-GN_Netcom_A_S_Jabra_EVOLVE_LINK_000736B1214E0A-00.mono-fallback
----

----
    --av-sync,     Audio/Video sync control <number>
----
此选项可用于将音频样本时间戳相对于视频帧的给定值（以微秒为单位）移动。也可以使用负值。

[[network-streaming-with-libav]]
==== 使用 libav 进行网络流式传输

可以使用 libav 后端作为音频/视频的网络流源。为此，-o参数指定的输出文件名必须作为协议 url 提供，有关协议使用的更多详细信息，请参阅 ffmpeg 协议。一些例子：

使用 TCP 流式传输音频/视频
----
libcamera-vid -t 0 --codec libav --libav-format mpegts --libav-audio -o "tcp://0.0.0.0:1234?listen=1"
----

使用 UDP 流式传输音频/视频
----
libcamera-vid -t 0 --codec libav --libav-format mpegts --libav-audio  -o "udp://<ip-addr>:<port>"
----
