[[libcamera-jpeg]]
=== `libcamera-jpeg`

libcamera-jpeg是一个简单的静态图像捕捉应用程序。它故意避开了libcamera-still的一些附加特性，后者试图更全面地模仿raspistill。因此，代码更容易理解，并且在实践中仍然提供了许多相同的功能。

要捕获全分辨率 JPEG 图像，请使用

[,bash]
----
libcamera-jpeg -o test.jpg
----
这将显示大约 5 秒的预览，然后将全分辨率 JPEG 图像捕获到test.jpg文件中。

该选项可用于更改预览显示的时间长度，和选项将更改捕获的静止图像的分辨率。例如-t <duration>--width--height
-t <duration >选项可用于改变预览显示的时间长度，而- width和- height选项将改变捕获的静止图像的分辨率。例如

[,bash]
----
libcamera-jpeg -o test.jpg -t 2000 --width 640 --height 480
----
将捕获 VGA 大小的图像。

[[exposure-control]]
==== 曝光控制

所有这些libcamera-apps都允许用户以固定的快门速度和增益运行相机。例如

[,bash]
----
libcamera-jpeg -o test.jpg -t 2000 --shutter 20000 --gain 1.5
----
将捕获曝光为 20 毫秒、增益为 1.5 倍的图像。请注意，增益将作为传感器内的模拟增益应用，直到达到内核传感器驱动程序允许的最大模拟增益，之后其余增益将作为数字增益应用。

Raspberry Pi 的 AEC/AGC 算法允许应用程序指定曝光补偿，即通过给定的停靠点数使图像变暗或变亮的能力，如下所示

[,bash]
----
libcamera-jpeg --ev -0.5 -o darker.jpg
libcamera-jpeg --ev 0 -o normal.jpg
libcamera-jpeg --ev 0.5 -o brighter.jpg
----

[[further-remarks-on-digital-gain]]
===== 关于数字增益的进一步评论

数字增益由ISP（图像信号处理器）施加，而不是由传感器施加。数字增益将始终非常接近1.0，除非：

* 请求的总增益（通过--gain选件或相机调谐中的曝光配置文件）超过了传感器内可用作模拟增益的总增益。只有所需的额外增益将用作数字增益。

* 其中一个颜色增益小于 1（请注意，颜色增益也应用为数字增益）。在这种情况下，广告的数字增益将稳定为1 / min（red_gain，blue_gain）。这实际上意味着其中一个颜色通道 - 而不是绿色通道 - 正在应用统一数字增益。

* AEC/AGC 正在发生变化。当AEC/AGC移动时，数字增益通常会在一定程度上变化，以试图消除任何波动，但它会很快恢复到其“正常”值。
