[[still-command-line-options]]
=== 仍然使用命令行选项

----
	--quality,	-q		JPEG quality <number>
----

设置 JPEG 质量。100 表示最高质量，93 表示默认值。仅在保存 JPEG 文件时适用。

例: `libcamera-jpeg -o test.jpg -q 80`

----
	--exif,		-x		Add extra EXIF tags <string>
----

给定的额外EXIF标签保存在JPEG文件中。仅在保存 JPEG 文件时适用。

使用libexif库支持EXIF，因此有一些相关的限制。特别是，libexif似乎可以识别许多标签，但不知道它们的正确格式。软件目前会将这些(在许多情况下是不正确的)视为ASCII，但会向终端打印一个警告。当我们遇到这些异常时，可以将它们添加到软件的已知异常表中。

显然，应用程序需要提供包含特定相机数据（如曝光时间）的EXIF标签。但是对于与相机无关的其他标签，一个合理的解决方法是使用类似exiftool .

例：libcamera-still -o test.jpg --exif IDO0.Artist=Someone

----
	--timelapse			Time interval between timelapse captures <milliseconds>
----

这将使libcamera-still进入定时模式，在该模式下，它将根据已设置的超时(- timeout或-t)运行，并在此期间以此处指定的间隔拍摄重复的图像。(lib camera-仅静止。)

示例：libcamera-still -t 100000 -o test%d.jpg --timelapse 10000每 10 秒捕获一个图像，持续约 100 秒。	

----
	--framestart			The starting value for the frame counter <number>
----

将计数器值写入输出文件名时，这将指定计数器的起始值。

示例:lib camera-still-t 100000-o test % d . jpg-time lapse 10000-frame start 1每隔10s捕捉一个图像，持续约100s，从1而不是0开始。(lib camera-仅静止。)

----
	--datetime			Use date format for the output file names
----

使用当前日期和时间构造输出文件名，格式为 MMDDhhmmss.jpg，其中 MM = 2 位月份编号，DD = 2 位日期编号，hh = 2 位 24 小时数，mm = 2 位分钟数，ss = 2 位秒数。（仅。libcamera-still）

例：libcamera-still --datetime

----
	--timestamp			Use system timestamps for the output file names
----

使用当前系统时间戳（自 1970 年开始以来的秒数）作为输出文件名。（仅libcamera-still）

例：libcamera-still --timestamp

----
	--restart			Set the JPEG restart interval <number>
----

将 JPEG 重新启动间隔设置为给定值。默认值为零。

例：libcamera-still -o test.jpg --restart 20

----
	--keypress,	-k		Capture image when Enter pressed
----

这会将libcamera-still切换到按键模式。当超时过期或在终端窗口中按下回车键时，它将捕获一个静止图像。键入x和Enter会导致libcamera-still退出而不进行采集。

例：libcamera-still -t 0 -o test.jpg -k

----
	--signal,	-s		Capture image when SIGUSR1 received
----

这会将libcamera-still切换到信号模式。当超时过期或收到SIGUSR1时，它将捕获一幅静止图像。SIGUSR2将导致libcamera-still退出而不捕获。

例：
libcamera-still -t 0 -o test.jpg -s &

然后
kill -SIGUSR1 $!

----
	--thumb				Set thumbnail parameters <w:h:q> or none
----

设置关联缩略图的尺寸和质量参数。默认值为 320x240 和质量 70。

例：libcamera-still -o test.jpg --thumb 640:480:80

可以给出该none值，在这种情况下，图像中根本不保存缩略图。

----
	--encoding,	-e		Set the still image codec <string>
----

选择要使用的静止图像编码。有效的编码器包括：

* `jpg` - JPEG (默认)
* `png` - PNG 格式
* `bmp` - BMP 格式
* `rgb` - 未压缩 RGB 像素的二进制转储
* `yuv420` - 未压缩的 YUV420 像素的二进制转储。

请注意，此选项决定了编码方式，因此输出文件名的扩展名将被忽略。但是，对于- datetime和- timestamp选项，文件扩展名取自上面列出的编码器名称。(lib camera-仅静止。)

例: `libcamera-still -e png -o test.png`

----
	--raw,		-r		Save raw file
----

在通常的输出图像旁边保存一个DNG格式的原始拜耳文件。文件名通过将输出文件扩展名替换为. dng来给出。这些是标准的DNG文件，可以使用dcraw或RawTherapee等标准工具进行处理。(lib camera-仅静止。)

原始文件中的图像数据正是来自传感器的图像数据，ISP或其他任何东西都没有处理。保存在文件中的EXIF数据，除其他外，包括：

* 曝光时间
* 模拟增益（ISO 标签是所用模拟增益的 100 倍）
* 白平衡增益（即“作为镜头中性”值的倒数）
* ISP 使用的颜色矩阵。

----
	--latest			Make symbolic link to latest file saved <string>
----

这会导致libcamera-still创建一个指向最近保存的文件的符号链接，从而使其更容易识别。(lib camera-仅静止。)

例：libcamera-still -t 100000 --timelapse 10000 -o test%d.jpg --latest latest.jpg

----
	--autofocus-on-capture			Whether to run an autofocus cycle before capture
----

如果设置，这将导致在捕获图像之前运行自动对焦循环。

如果没有指定自动对焦模式，或者设置为默认或手动，这将是唯一的自动对焦循环。

如果--autofocus-mode设置为auto ，则在预览窗口开始时将有一个额外的自动对焦周期。

如果--autofocus-mode设置为continuous ，则忽略此选项。

也可以使用。--autofocus-on-capture 1 代替--autofocus-on-capture 和--autofocus-on-capture 0作为完全省略参数的替代方法

例：libcamera-still --autofocus-on-capture -o test.jpg

此选项仅支持某些相机模块（例如Raspberry Pi相机模块 3）。