[[libcamera-hello]]
=== `libcamera-hello`

libcamera-hello相当于相机的“Hello World”应用程序。它启动相机，显示预览窗口，而不执行任何其他操作。例如

[,bash]
----
libcamera-hello
----
应该会显示一个大约5秒钟的预览窗口。-t <持续时间>选项允许用户选择窗口显示的时间长度，其中<持续时间>以毫秒为单位。要无限期运行预览，请使用:

[,bash]
----
libcamera-hello -t 0
----

可以通过单击窗口的关闭按钮或在终端中使用Ctrl-C来停止预览。

[[options]]
==== 选项

libcamera-apps使用第三方库来解释命令行选项。这包括长格式选项和短格式选项，长格式选项的选项名由多个以-开头的字符组成，短格式选项只能是以单个-开头的单个字符。在很大程度上，选择的选项名称与传统raspicam应用程序使用的名称相匹配，只是我们不能再用单个-来处理多字符选项名称。任何此类传统选项都已被删除，必须使用带-的长格式来代替。
这些选项大致分为 3 组，即常见选项、特定于静止图像的选项和用于视频编码的选项。它们在应用的所有应用程序中都以相同的方式受支持。
有关完整列表，请参阅xref:camera_software.adoc#common-command-line-options[命令行选项文档]。


[[the-tuning-file]]
==== 调优文件

Raspberry Pi的libcamera实现包括一个针对每种不同类型的相机模块的调整文件。这是一个描述或“调整”参数的文件，这些参数将被传递给算法和硬件以产生最佳图像质量。libcamera只能自动确定正在使用的图像传感器，而不是作为一个整体的模块——即使整个模块会影响“调整”。

因此，有时需要覆盖特定传感器的默认调整文件。
例如，NOIR（无红外滤光片）版本的传感器需要与标准版本不同的AWB设置，因此IMX219 NOIR应使用运行
[,bash]
----
libcamera-hello --tuning-file /usr/share/libcamera/ipa/raspberrypi/imx219_noir.json
----

如果您使用的是 Soho 企业 SE327M12 模块，则应使用

[,bash]
----
libcamera-hello --tuning-file /usr/share/libcamera/ipa/raspberrypi/se327m12.json
----

请注意，这也意味着用户可以复制现有的优化文件并根据自己的首选项对其进行更改，只要--tuning-file参数指向新版本即可。

最后，与其他libcamera-hello命令行选项一样，tuning-file参数同样适用于所有libcamera-apps。

[[preview-window]]
==== 预览窗口

大多数在窗口中显示libcamera-apps预览图像。当 X Windows 未运行时，它将使用 Linux DRM（直接渲染管理器）直接绘制到显示器，否则它将尝试使用 X Windows。两条路径都使用与 GPU 共享的零拷贝缓冲区，其结果是不支持 X 转发。

出于这个原因，还有第三种预览窗口，它确实支持 X 转发，并且可以通过该--qt-preview选项请求。此实现既不能受益于零拷贝缓冲区共享，也不能受益于 3D 加速，这使得它的计算成本很高（尤其是对于大型预览），因此通常不建议这样做。

NOTE: 使用Gtk2的旧系统在与OpenCV链接时，可能会产生Glib-GObject错误，并且无法显示Qt预览窗口。在这种情况下，请(以root用户身份)编辑文件/etc/xdg/qt5ct/qt5ct.conf，并将包含style=gtk2的行替换为style=gtk3。

预览窗口可以使用-n （--nopreview） 选项完全禁止显示。

该--info-text选项允许用户请求使用“%指令”在窗口标题栏上显示某些有用的图像信息。例如

[,bash]
----
libcamera-hello --info-text "red gain %rg, blue gain %bg"
----
将显示当前的红色和蓝色增益值。

对于 HQ 相机，--info-text "%focus"用于显示对焦测量值，这将有助于对焦镜头。

xref:camera_software.adoc#common-command-line-options[命令行选项文档]中提供了--info-text参数的完整说明。
