[[getting-started]]
=== 开始

[[using-the-camera-for-the-first-time]]
==== 首次使用相机

NOTE: 在Raspberry Pi 3和运行Bullseye的早期设备上，您需要重新启用Glamor以使X-Windows硬件加速预览窗口工作。为此，在终端窗口输入sudo raspi-config，然后选择高级选项、Glamor和Yes。最后退出raspi-config，让它重启你的Raspberry Pi。

当运行基于Bullseye的Raspberry Pi操作系统时，已经安装了5个基本的libcamera应用程序。在这种情况下，官方的Raspberry Pi摄像头也会被自动检测并启用。

您可以通过输入以下内容来检查一切是否正常：

[,bash]
----
libcamera-hello
----

您应该会看到相机预览窗口约 5 秒钟。

仍在运行Buster的用户应该升级到Bullseye。那里不再支持新的基于 libcamera 的堆栈，任何仍在使用 Buster 的人都应该继续使用旧的相机堆栈。

NOTE: Raspberry Pi 3和更旧的设备可能默认没有使用正确的显示驱动程序。参考/boot/config.txt文件，确保dtoverlay=vc4-fkms-v3d或dtoverlay=vc4-kms-v3d当前处于活动状态。如果需要更改，请重新启动。

[[if-you-do-need-to-alter-the-configuration]]
==== 如果确实需要更改配置

在以下情况下，您可能需要更改/boot/config.txt文件中的相机配置：

* 您使用的是第三方相机（制造商的说明应说明您需要进行的更改）。

* 您使用的是官方的Raspberry Pi相机，但希望使用非标准的驱动程序/覆盖。

如果您确实需要添加自己的dtoverlay,目前可以识别以下内容。

|===
| 相机模组 | 在 `/boot/config.txt`

| V1 camera (OV5647)
| `dtoverlay=ov5647`

| V2 camera (IMX219)
| `dtoverlay=imx219`

| HQ camera (IMX477)
| `dtoverlay=imx477`

| GS camera (IMX296)
| `dtoverlay=imx296`

| Camera Module 3 (IMX708)
| `dtoverlay=imx708`

| IMX290 and IMX327
| `dtoverlay=imx290,clock-frequency=74250000` or `dtoverlay=imx290,clock-frequency=37125000` (both modules share the imx290 kernel driver; please refer to instructions from the module vendor for the correct frequency)

| IMX378
| `dtoverlay=imx378`

| OV9281
| `dtoverlay=ov9281`
|===

要覆盖自动摄像机检测，Bullseye 用户还需要删除条目camera_auto_detect=1(如果在config.txt文件中存在)。编辑此文件后，您的Raspberry Pi需要重新启动。

NOTE: 设置camera_auto_detect=0将完全禁用启动时间检测。
