[[libcamera-still]]
=== `libcamera-still`

libcamera-still与libcamera-jpeg非常相似，但支持更多的传统raspistill选项。和以前一样，可以用

[,bash]
----
libcamera-still -o test.jpg
----

[[encoders]]
==== 编码

libcamera-still允许以多种不同的格式保存文件。它支持png，bmp两者和编码。它还允许将文件另存为 RGB 或 YUV 像素的二进制转储，完全没有编码或文件格式。在后一种情况下，读取文件的应用程序必须自行了解像素排列。

[,bash]
----
libcamera-still -e png -o test.png
libcamera-still -e bmp -o test.bmp
libcamera-still -e rgb -o test.data
libcamera-still -e yuv420 -o test.data
----
请注意，保存图像的格式取决于-e（等效）--encoding选项，并且不会根据输出文件名自动选择。

[[raw-image-capture]]
==== 原始图像捕获

原始图像是由图像传感器直接生成的图像，在ISP（图像信号处理器）或任何CPU内核对其应用任何处理之前。对于彩色图像传感器，这些通常是拜耳格式的图像。请注意，原始图像与我们之前看到的已处理但未编码的 RGB 或 YUV 图像有很大不同。

捕获原始图像使用

[,bash]
----
libcamera-still -r -o test.jpg
----

这里，-r选项(也叫- raw)表示捕获raw图像和JPEG图像。事实上，原始图像就是产生JPEG的精确图像。原始图像以DNG (Adobe Digital Negative)格式保存，并与许多标准应用程序兼容，如dcraw或RawTherapee。原始图像被保存到一个具有相同名称但扩展名为的文件中。dng，因此本例中为test.dng。

这些DNG文件包含有关图像捕获的元数据，包括黑电平，白平衡信息和ISP用于产生JPEG的颜色矩阵。这使得这些DNG文件更方便以后使用上述一些工具进行“手动”原始转换。“使用”exiftool显示编码到 DNG 文件中的所有元数据：

----
File Name                       : test.dng
Directory                       : .
File Size                       : 24 MB
File Modification Date/Time     : 2021:08:17 16:36:18+01:00
File Access Date/Time           : 2021:08:17 16:36:18+01:00
File Inode Change Date/Time     : 2021:08:17 16:36:18+01:00
File Permissions                : rw-r--r--
File Type                       : DNG
File Type Extension             : dng
MIME Type                       : image/x-adobe-dng
Exif Byte Order                 : Little-endian (Intel, II)
Make                            : Raspberry Pi
Camera Model Name               : /base/soc/i2c0mux/i2c@1/imx477@1a
Orientation                     : Horizontal (normal)
Software                        : libcamera-still
Subfile Type                    : Full-resolution Image
Image Width                     : 4056
Image Height                    : 3040
Bits Per Sample                 : 16
Compression                     : Uncompressed
Photometric Interpretation      : Color Filter Array
Samples Per Pixel               : 1
Planar Configuration            : Chunky
CFA Repeat Pattern Dim          : 2 2
CFA Pattern 2                   : 2 1 1 0
Black Level Repeat Dim          : 2 2
Black Level                     : 256 256 256 256
White Level                     : 4095
DNG Version                     : 1.1.0.0
DNG Backward Version            : 1.0.0.0
Unique Camera Model             : /base/soc/i2c0mux/i2c@1/imx477@1a
Color Matrix 1                  : 0.8545269369 -0.2382823821 -0.09044229197 -0.1890484985 1.063961506 0.1062747385 -0.01334283455 0.1440163847 0.2593136724
As Shot Neutral                 : 0.4754476844 1 0.413686484
Calibration Illuminant 1        : D65
Strip Offsets                   : 0
Strip Byte Counts               : 0
Exposure Time                   : 1/20
ISO                             : 400
CFA Pattern                     : [Blue,Green][Green,Red]
Image Size                      : 4056x3040
Megapixels                      : 12.3
Shutter Speed                   : 1/20
----
我们注意到只有一个校准光源（由AWB算法确定的光源，即使它总是被标记为“D65”），并且将ISO值除以100得到正在使用的模拟增益。

[[very-long-exposures]]
==== 长时间曝光

为了拍摄曝光时间很长的图像，我们需要小心禁用AEC/AGC和AWB，否则这些算法将迫使用户在收敛时等待多个帧。禁用它们的方法是提供显式值。此外，可以使用该--immediate选项跳过捕获的整个预览阶段。

因此，要执行 100 秒曝光捕获，请使用

`libcamera-still -o long_exposure.jpg --shutter 100000000 --gain 1 --awbgains 1,1 --immediate`

作为参考，三款官方Raspberry Pi相机的最大曝光时间可以在xref:../accessories/camera.adoc#hardware-specification[此表]中找到。
