[[libcamera-vid]]
=== `libcamera-vid`

libcamera-vid是视频捕获应用程序。默认情况下，它使用Raspberry Pi的硬件H.264编码器。它将显示一个预览窗口，并将编码的比特流写入指定的输出。例如，要将 10 秒的视频写入文件，请使用

[,bash]
----
libcamera-vid -t 10000 -o test.h264
----
生成的文件可以播放vlc（以及其他应用程序）
[,bash]
----
vlc test.h264
----
请注意，这是一个未打包的视频比特流，它没有包装在任何类型的容器格式中(如mp4文件)。- save-pts选项可用于输出帧时间戳，以便随后使用mkvmerge等工具将比特流转换为适当的格式。

libcamera-vid -o test.h264 --save-pts timestamps.txt
然后，如果您想要一个 MKV 文件：

mkvmerge -o test.mkv --timecodes 0:timestamps.txt test.h264

[[encoders-2]]
==== 编码

例如，支持运动JPEG，以及未压缩和未格式化的YUV420
[,bash]
----
libcamera-vid -t 10000 --codec mjpeg -o test.mjpeg
libcamera-vid -t 10000 --codec yuv420 -o test.data
----
在这两种情况下，--codec参数确定输出格式，而不是输出文件的扩展名。

该--segment参数将输出文件分解为段大小的块（以毫秒为单位）。这对于通过指定非常短（1毫秒）的段将运动 JPEG 流分解为单独的 JPEG 文件非常方便。
[,bash]
----
libcamera-vid -t 10000 --codec mjpeg --segment 1 -o test%05d.jpeg
----
请注意，输出文件名通常只有在我们避免每次都覆盖前一个文件时才明智，例如使用包含计数器的文件名（如上所述）。下面提供了有关输出文件名的更多信息。

[[network-streaming]]
==== 网络流

NOTE: 本节介绍来自libcamera-vid 的本机流式处理。但是，也可以使用 libav 后端进行网络流。有关更多详细信息，请参阅 libav 部分。

[[udp]]
===== UDP

要使用UDP流式传输视频，请在Raspberry Pi（服务器）上使用
[,bash]
----
libcamera-vid -t 0 --inline -o udp://<ip-addr>:<port>
----
where `<ip-addr>` is the IP address of the client, or multicast address (if appropriately configured to reach the client). On the client use (for example)
[,bash]
----
vlc udp://@:<port> :demux=h264
----
或者
----
ffplay udp://<ip-addr-of-server>:<port> -fflags nobuffer -flags low_delay -framedrop
----
具有相同的<port>值。

[[tcp]]
===== TCP

可以使用 TCP 流式传输视频。将Raspberry Pi用作服务器
[,bash]
----
libcamera-vid -t 0 --inline --listen -o tcp://0.0.0.0:<port>
----
和客户端
[,bash]
----
vlc tcp/h264://<ip-addr-of-server>:<port>
----
或者
----
ffplay tcp://<ip-addr-of-server>:<port> -vf "setpts=N/30" -fflags nobuffer -flags low_delay -framedrop
----
每秒 30 帧的低延迟流。

Raspberry Pi将等到客户端连接，然后开始流式传输视频。

[[rtsp]]
===== RTSP

vlc在Raspberry Pi上对于格式化RTSP流很有用，尽管还有其他RTSP服务器可用。
[,bash]
----
libcamera-vid -t 0 --inline -o - | cvlc stream:///dev/stdin --sout '#rtp{sdp=rtsp://:8554/stream1}' :demux=h264
----
这可以播放
[,bash]
----
vlc rtsp://<ip-addr-of-server>:8554/stream1
----
或者
----
ffplay rtsp://<ip-addr-of-server>:8554/stream1 -vf "setpts=N/30" -fflags nobuffer -flags low_delay -framedrop
----

在所有情况下，服务器上的预览窗口(Raspberry Pi)都可以用-n(--no preview)选项取消。还要注意- inline选项的使用，它强制将流头信息包含在每个I(内部)帧中。这一点很重要，这样，如果客户端错过了流的开头，它就可以正确地理解流。

NOTE: 最新版本的 VLC 似乎在播放 H.264 流时存在问题。我们建议使用上述ffplay命令进行播放，直到这些问题得到解决。

[[high-framerate-capture]]
==== 高帧率捕获
使用libcamera-vid捕获高帧率视频（通常超过 60 fps）同时最大限度地减少丢帧需要一些注意事项：

1. The https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels[H.264 target level] must be set to 4.2 with the `--level 4.2` argument.
1.必须使用- level 4.2参数将 https://en.wikipedia.org/wiki/Advanced_Video_Coding#Levels[H.264目标级别]设置为4.2。

2.软件颜色去噪处理必须与参数--denoise cdn_off一起关闭。

3.对于超过 100 fps 的速率，使用该-n选项禁用显示窗口将释放一些额外的 CPU 周期，以帮助避免丢帧。

4. 建议在/boot/config.txt中设置force_turbo=1，以确保CPU时钟不会在视频捕获期间受到抑制。详情请见此处。

5. 调整ISP输出分辨率--width 1280 --height 720或甚至更低的分辨率以实现您的帧速率目标。

6.在Pi 4上，您可以通过在/boot/config.txt中添加gpu_freq=550或更高版本来对GPU进行超频以提高性能，详细信息请参见https://www.raspberrypi.com/documentation/computers/config_txt.html#overclocking[此处。]

1280x720 120fps 视频编码的示例命令为：

[,bash]
----
libcamera-vid --level 4.2 --framerate 120 --width 1280 --height 720 --save-pts timestamp.pts -o video.264 -t 10000 --denoise cdn_off -n
----