[[setting-up-a-bridged-wireless-access-point]]
== 设置桥接无线接入点

Raspberry Pi 可用作现有以太网网络中的桥接无线接入点。这会将网络扩展到无线计算机和设备。
如果要创建独立的无线网络，请考虑改为xref:configuration.adoc#setting-up-a-routed-wireless-access-point[设置路由接入点]。

----
                                         +- RPi -------+
                                     +---+ 10.10.0.2   |          +- Laptop ----+
                                     |   |     WLAN AP +-)))  (((-+ WLAN Client |
                                     |   |  Bridge     |          | 10.10.0.5   |
                                     |   +-------------+          +-------------+
                 +- Router ----+     |
                 | Firewall    |     |   +- PC#2 ------+
(Internet)---WAN-+ DHCP server +-LAN-+---+ 10.10.0.3   |
                 |   10.10.0.1 |     |   +-------------+
                 +-------------+     |
                                     |   +- PC#1 ------+
                                     +---+ 10.10.0.4   |
                                         +-------------+
----

桥接无线接入点可以使用Raspberry Pi 4，Raspberry Pi 3或Raspberry Pi Zero W的内置无线功能，或使用支持接入点模式的合适USB无线加密狗来创建。 某些 USB 加密狗可能需要对其设置稍作更改。如果您在使用 USB 无线加密狗时遇到问题，请查看https://forums.raspberrypi.com/[论坛]。

[[intro-to-bridged-wap]]
=== 开始之前

* 确保您对Raspberry Pi具有管理访问权限。作为安装的一部分，网络设置将完全重置：建议使用本地访问，将屏幕和键盘连接到Raspberry Pi。
+
[NOTE]
====
如果通过 SSH 远程安装，请按 *名称* 而不是 IP 地址连接到您的Raspberry Pi，例如 `ssh pi@raspberrypi.local`，因为您的Raspberry Pi在网络上的地址可能会在安装后发生变化。如果需要，您还应该准备好添加屏幕和键盘，以防您在安装后与Raspberry Pi失去联系。
====
* 将Raspberry Pi连接到以太网并启动Raspberry Pi操作系统。
* 确保Raspberry Pi上的Raspberry Pi操作系统是 xref:os.adoc#updating-and-upgrading-raspberry-pi-os[最新]的，如果在此过程中安装了软件包，请重新启动。 
* 准备好无线客户端（笔记本电脑、智能手机等）来测试您的新接入点。

[[access-point-software-install]]
=== 安装 AP 和管理软件

为了用作桥接接入点，Raspberry Pi 需要安装接入点软件包 `hostapd`：
----
sudo apt install hostapd
----

启用无线接入点服务并将其设置为在Raspberry Pi启动时启动：

----
sudo systemctl unmask hostapd
sudo systemctl enable hostapd
----

软件安装完成。稍后我们将配置接入点软件。

[[bridging]]
=== 设置网桥

在Raspberry Pi上运行的桥接网络设备将使用其内置接口连接以太网和无线网络。

[[create-a-bridge-device-and-populate-the-bridge]]
==== 创建网桥设备并填充网桥

通过使用以下命令创建文件来添加网桥网络设备br0，内容如下：

----
sudo nano /etc/systemd/network/bridge-br0.netdev
----

文件内容：

----
[NetDev]
Name=br0
Kind=bridge
----

为了将以太网网络与无线网络桥接，首先通过创建以下文件将内置以太网接口 （`eth0`） 添加为网桥成员：

----
sudo nano /etc/systemd/network/br0-member-eth0.network
----

文件内容：

----
[Match]
Name=eth0

[Network]
Bridge=br0
----

NOTE: 接入点软件将在服务启动时将无线接口wlan0添加到网桥。无需为该接口创建文件。这种情况特定于无线 LAN 接口。

接入点软件将在服务启动时将无线接口wlan0添加到网桥。无需为该接口创建文件。这种情况特定于无线 LAN 接口。

----
sudo systemctl enable systemd-networkd
----

[[define-the-bridge-device-ip-configuration]]
==== 定义网桥设备 IP 配置

作为网桥设备成员的网络接口永远不会分配 IP 地址，因为它们通过网桥进行通信。桥接设备本身需要一个 IP 地址，以便您可以在网络上访问您的Raspberry Pi。

`dhcpcd`，Raspberry Pi上的 DHCP 客户端会自动为每个活动接口请求一个 IP 地址。因此，我们需要阻止处理  `eth0` 和 `wlan0`，并 `dhcpcd` 仅通过 DHCP 进行配置 `br0`。

----
sudo nano /etc/dhcpcd.conf
----

在文件开头附近添加以下行（第一行上方interface xxx，如果有）：

----
denyinterfaces wlan0 eth0
----

Go to the end of the file and add the following:

----

interface br0
----

使用此行，接口 `br0` 将通过 DHCP 根据默认值进行配置。保存文件以完成计算机的 IP 配置。

[[ensure-wireless-operation]]
=== 确保无线操作

世界各国对电信无线电频段的使用进行监管，以确保无干扰运行。

Linux 操作系统通过允许应用程序配置两个字母的“WiFi 国家/地区代码”来帮助用户遵守这些 https://wireless.wiki.kernel.org/en/developers/regulatory/statement[规则]，例如 `US` 用于在美国使用的计算机。

在Raspberry Pi OS中，在用户配置WiFi国家/地区代码之前，5 GHz无线网络将被禁用，通常作为初始安装过程的一部分（有关详细信息，请参阅本节中的xref:configuration.adoc#configuring-networking[无线配置]页面。
要确保 WiFi 无线电不会在Raspberry Pi上被阻止，请执行以下命令：


----
sudo rfkill unblock wlan
----

此设置将在启动时自动恢复。接下来，我们将在接入点软件配置中定义适当的国家/地区代码。

[[configure-access-point-software]]
=== 软件配置AP

创建位于 `/etc/hostapd/hostapd.conf` 的配置文件 `hostapd` ，为新无线网络添加各种参数。

----
sudo nano /etc/hostapd/hostapd.conf
----

将以下信息添加到配置文件中。此配置假设我们使用通道 7，网络名称为 `NameOfNetwork` ，密码 `AardvarkBadgerHedgehog`。请注意，名称和密码 *不* 应有引号。密码的长度应介于 8 到 64 个字符之间。


----
country_code=GB
interface=wlan0
bridge=br0
ssid=NameOfNetwork
hw_mode=g
channel=7
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=AardvarkBadgerHedgehog
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
----

Note the lines `interface=wlan0` and `bridge=br0`: these direct `hostapd` 请注意这一行 `country_code=GB`：它将计算机配置为在英国使用正确的无线频率。调整此行并指定您所在国家/地区的两个字母的 ISO 代码。请参阅 https://en.wikipedia.org/wiki/ISO_3166-1[维基百科] 以获取两个字母的ISO 3166-1国家/地区代码列表。
要使用 5 GHz 频段，可以将操作模式从 `hw_mode=g` 更改为 `hw_mode=a`。`hw_mode` 
的可能值为：

* a = IEEE 802.11a (5 GHz) (Raspberry Pi 3B+ onwards)
* b = IEEE 802.11b (2.4 GHz)
* g = IEEE 802.11g (2.4 GHz)

请注意，在更改 `hw_mode` 时，您可能还需要更改channel - 有关允许的组合列表，请参阅https://en.wikipedia.org/wiki/List_of_WLAN_channels[维基百科]。


[[run-wireless-access-point]]
=== 运行新的无线 AP

现在重新启动Raspberry Pi并验证无线接入点是否自动可用。

----
sudo systemctl reboot
----

Raspberry Pi重新启动后，使用无线客户端搜索无线网络。您在 `/etc/hostapd/hostapd.conf` 文件中指定的网络 SSID 现在应该存在，并且应该可以使用指定的密码访问它。
如果您的无线客户端可以访问本地网络和互联网，则恭喜您设置了新的接入点！
如果您遇到困难，请联系 https://forums.raspberrypi.com/[论坛]寻求帮助。请在您的消息中参考此页面。
