[[setting-up-a-routed-wireless-access-point]]
== 设置路由无线接入点

以太网网络中的Raspberry Pi可以用作无线接入点，创建辅助网络。由此产生的新无线网络完全由Raspberry Pi管理。
如果您希望将现有以太网网络扩展到无线客户端，请考虑改为 xref:configuration.adoc#setting-up-a-bridged-wireless-access-point[桥接接入点].。

----
                                         +- RPi -------+
                                     +---+ 10.10.0.2   |          +- Laptop ----+
                                     |   |     WLAN AP +-)))  (((-+ WLAN Client |
                                     |   | 192.168.4.1 |          | 192.168.4.2 |
                                     |   +-------------+          +-------------+
                 +- Router ----+     |
                 | Firewall    |     |   +- PC#2 ------+
(Internet)---WAN-+ DHCP server +-LAN-+---+ 10.10.0.3   |
                 |   10.10.0.1 |     |   +-------------+
                 +-------------+     |
                                     |   +- PC#1 ------+
                                     +---+ 10.10.0.4   |
                                         +-------------+
----

可以使用Raspberry Pi 4，Raspberry Pi 3或Raspberry Pi Zero W的内置无线功能，或使用支持接入点模式的合适USB无线加密狗来创建路由无线接入点。 某些 USB 加密狗可能需要对其设置稍作更改。如果您在使用 USB 无线加密狗时遇到问题，请查看 https://forums.raspberrypi.com/[论坛]。

本文档在运行全新安装的Raspberry Pi OS Buster的Raspberry Pi 3B上进行了测试。


[[intro]]
=== Before you Begin

* 确保您对Raspberry Pi具有管理访问权限。网络设置将作为安装的一部分进行修改：建议使用本地访问，将屏幕和键盘连接到Raspberry Pi。
* 将Raspberry Pi连接到以太网并启动Raspberry Pi操作系统。
* 确保Raspberry Pi上的Raspberry Pi操作系统是 xref:os.adoc#updating-and-upgrading-raspberry-pi-os[最新] 的，如果在此过程中安装了软件包，请重新启动。
* 记下Raspberry Pi所连接的以太网网络的IP配置：
 ** 在本文档中，我们假设IP网络 `10.10.0.0/24` 是在以太网LAN上配置的，并且Raspberry Pi将管理无线客户端的IP网络 `192.168.4.0/24`。
 ** 请选择另一个用于无线的 IP 网络，例如 `192.168.10.0/24`，如果您的以太网 LAN 已经在使用 IP 网络 `192.168.4.0/24`。
* 准备好无线客户端（笔记本电脑、智能手机等）来测试您的新接入点。

[[software-install]]
=== 安装 AP 和管理软件

为了用作接入点，Raspberry Pi需要安装接入点软件包hostapd：

----
sudo apt install hostapd
----

启用无线接入点服务并将其设置为在Raspberry Pi启动时启动：

----
sudo systemctl unmask hostapd
sudo systemctl enable hostapd
----

为了向无线客户端提供网络管理服务（DNS，DHCP），Raspberry Pi需要安装软件包 `dnsmasq` ：

----
sudo apt install dnsmasq
----

最后，安装 `netfilter-persistent` 及其插件 `iptables-persistent`。此实用程序通过保存防火墙规则并在Raspberry Pi启动时恢复它们来帮助：

----
sudo DEBIAN_FRONTEND=noninteractive apt install -y netfilter-persistent iptables-persistent
----

软件安装完成。稍后我们将配置软件包。

[[routing]]
=== 设置网络路由器

Raspberry Pi将运行和管理独立的无线网络。它还将在无线和以太网之间路由，为无线客户端提供互联网访问。如果您愿意，可以通过跳过下面的“启用路由和 IP 伪装”部分来选择跳过路由，并在完全隔离的情况下运行无线网络。

[[define-the-wireless-interface-ip-configuration]]
==== 定义无线接口 IP 配置

Raspberry Pi为无线网络运行DHCP服务器;这需要Raspberry Pi中无线接口 （`wlan0`） 的静态 IP 配置。 Raspberry Pi还充当无线网络上的路由器，按照惯例，我们将为其提供网络中的第一个 IP 地址: `192.168.4.1`.

要配置静态 IP 地址，请使用以下命令编辑dhcpcd配置文件：

----
sudo nano /etc/dhcpcd.conf
----

转到文件末尾并添加以下内容：

----
interface wlan0
    static ip_address=192.168.4.1/24
    nohook wpa_supplicant
----

[[enable-routing-and-ip-masquerading]]
==== 启用路由和 IP 伪装

本节将 Raspberry Pi 配置为允许无线客户端访问主（以太网）网络上的计算机，并从那里访问互联网。

NOTE: 如果您希望阻止无线客户端访问以太网网络和互联网，请跳过此部分。

要启用路由，即允许流量在Raspberry Pi中从一个网络流向另一个网络，请使用以下命令创建一个文件，内容如下：
----
sudo nano /etc/sysctl.d/routed-ap.conf
----

文件内容：

----
# Enable IPv4 routing
net.ipv4.ip_forward=1
----

启用路由将允许来自网络 `192.168.4.0/24` 的主机到达 LAN 和主路由器，连接互联网。为了允许此外部无线网络上的客户端与互联网之间的流量而不更改主路由器的配置，Raspberry Pi可以使用“伪装”防火墙规则将无线客户端的IP地址替换为LAN上自己的IP地址。

* 主路由器将看到来自无线客户端的所有传出流量来自Raspberry Pi，从而允许与互联网通信。
* Raspberry Pi将接收所有传入流量，替换 IP 地址，并将流量转发到原始无线客户端。

Raspberry Pi将接收所有传入流量，替换 IP 地址，并将流量转发到原始无线客户端。

----
sudo iptables -t nat -A POSTROUTING -o eth0 -j MASQUERADE
----

现在保存 IPv4（包括上述规则）和 IPv6 的当前防火墙规则，以便在 `netfilter-persistent` 服务启动时加载：

----
sudo netfilter-persistent save
----

过滤规则将保存到目录 `/etc/iptables/` 中。如果将来更改防火墙的配置，请确保在重新启动之前保存配置。

[[configure-the-dhcp-and-dns-services-for-the-wireless-network]]
==== 为无线网络配置 DHCP 和 DNS 服务

DHCP 和 DNS 服务由 `dnsmasq` 提供。默认配置文件用作所有可能的配置选项的模板，而我们只需要几个。从空文件开始更容易。

重命名默认配置文件并编辑一个新配置文件：

----
sudo mv /etc/dnsmasq.conf /etc/dnsmasq.conf.orig
sudo nano /etc/dnsmasq.conf
----

将以下内容添加到文件并保存：

----
interface=wlan0 # Listening interface
dhcp-range=192.168.4.2,192.168.4.20,255.255.255.0,24h
                # Pool of IP addresses served via DHCP
domain=wlan     # Local wireless DNS domain
address=/gw.wlan/192.168.4.1
                # Alias for this router
----

Raspberry Pi将在 `192.168.4.2` 和 `192.168.4.20` 之间提供 IP 地址，租用时间为 24 小时，到无线 DHCP 客户端。您应该能够从无线客户端以该gw.wlan名称访问Raspberry Pi。

NOTE: 为专用网络预留了三个 IP 地址块。有一个 A 类块从 `10.0.0.0` 到 `10.255.255.255` ，一个 B 类块从 `172.16.0.0` 到 `172.31.255.255` ，可能最常用的是 C 类块从 `192.168.0.0` 到 `192.168.255.255` 。

还有 `dnsmasq` 更多选项 ;有关详细信息，请参阅默认配置文件 （`/etc/dnsmasq.conf`） 或http://www.thekelleys.org.uk/dnsmasq/doc.html[联机文档]。


[[wifi-cc-rfkill]]
=== 确保无线操作

世界各国对电信无线电频段的使用进行监管，以确保无干扰运行。

Linux 操作系统通过允许应用程序配置两个字母的“WiFi 国家/地区代码”来帮助用户遵守这些 https://wireless.wiki.kernel.org/en/developers/regulatory/statement[规则]，例如 `US` 用于在美国使用的计算机。

在Raspberry Pi OS中，在用户配置WiFi国家/地区代码之前，5 GHz无线网络将被禁用，通常作为初始安装过程的一部分（有关详细信息，请参阅本节中的xref:configuration.adoc#configuring-networking[无线配置]页面。
要确保 WiFi 无线电不会在Raspberry Pi上被阻止，请执行以下命令：

----
sudo rfkill unblock wlan
----

此设置将在启动时自动恢复。接下来，我们将在接入点软件配置中定义适当的国家/地区代码。

[[ap-config]]
=== 配置 AP 软件

创建位于 `/etc/hostapd/hostapd.conf` 的配置文件 `hostapd` ，为新无线网络添加各种参数。

----
sudo nano /etc/hostapd/hostapd.conf
----

将以下信息添加到配置文件中。此配置假设我们使用通道 7，网络名称为 `NameOfNetwork` ，密码 `AardvarkBadgerHedgehog`。请注意，名称和密码 *不* 应有引号。密码的长度应介于 8 到 64 个字符之间。

----
country_code=GB
interface=wlan0
ssid=NameOfNetwork
hw_mode=g
channel=7
macaddr_acl=0
auth_algs=1
ignore_broadcast_ssid=0
wpa=2
wpa_passphrase=AardvarkBadgerHedgehog
wpa_key_mgmt=WPA-PSK
wpa_pairwise=TKIP
rsn_pairwise=CCMP
----

请注意这一行 `country_code=GB`：它将计算机配置为在英国使用正确的无线频率。调整此行并指定您所在国家/地区的两个字母的 ISO 代码。请参阅 https://en.wikipedia.org/wiki/ISO_3166-1[维基百科] 以获取两个字母的ISO 3166-1国家/地区代码列表。
要使用 5 GHz 频段，可以将操作模式从 `hw_mode=g` 更改为 `hw_mode=a`。`hw_mode` 
的可能值为：

* a = IEEE 802.11a (5 GHz) (Raspberry Pi 3B+ onwards)
* b = IEEE 802.11b (2.4 GHz)
* g = IEEE 802.11g (2.4 GHz)

请注意，在更改 `hw_mode` 时，您可能还需要更改channel - 有关允许的组合列表，请参阅https://en.wikipedia.org/wiki/List_of_WLAN_channels[维基百科]。

[[conclusion]]
=== 运行新的无线 AP

现在重新启动Raspberry Pi并验证无线接入点是否自动可用。

----
sudo systemctl reboot
----

Raspberry Pi重新启动后，使用无线客户端搜索无线网络。您在 `/etc/hostapd/hostapd.conf` 文件中指定的网络 SSID 现在应该存在，并且应该可以使用指定的密码访问它。

如果在Raspberry Pi上启用了SSH，则假设该 `pi` 帐户存在，则应该可以从无线客户端连接到它，如下所示： `ssh pi@192.168.4.1` 或 `ssh pi@gw.wlan`
如果您的无线客户端可以访问您的Raspberry Pi（以及互联网，如果您设置了路由），那么恭喜您设置了新的接入点！
如果您遇到困难，请联系 https://forums.raspberrypi.com/[论坛] 寻求帮助。请在您的消息中参考此页面。
