[[rotating-your-display]]
== 旋转显示器

旋转Raspberry Pi显示器的选项取决于它正在运行的显示驱动程序软件，这可能还取决于您使用的Raspberry Pi。

[[fake-or-full-kms-graphics-driver]]
=== Fake 或 Full KMS 图形驱动程序 

NOTE: 这是Raspberry Pi 4 Model B的默认设置。

如果您正在运行Raspberry Pi桌面，则使用 `Screen Configuration Utility` 桌面 `Preferences` 菜单实现旋转。这将调出连接到Raspberry Pi的一个或多个显示器的图形表示。右键单击要旋转的显示屏，然后选择所需的选项。

也可以使用命令行 `xrandr` 选项更改这些设置。以下命令分别提供 0°、-90°、+90° 和 180° 旋转。

[,bash]
----
xrandr --output HDMI-1 --rotate normal
xrandr --output HDMI-1 --rotate left
xrandr --output HDMI-1 --rotate right
xrandr --output HDMI-1 --rotate inverted
----

请注意，该 `--output` 条目指定轮换应用于哪个设备。您只需在命令行上键入 `xrandr` 即可确定设备名称，该命令行将显示所有连接设备的信息，包括名称。
您还可以使用该--reflect选项使用命令行镜像显示。反射可以是'normal' 'x', 'y' 或 'xy'之一。这会导致输出内容反映在指定的轴上。例如：

[,bash]
----
xrandr --output HDMI-1 --reflect x
----

如果仅使用控制台（没有图形桌面），则需要设置适当的内核命令行标志。按照此xref:configuration.adoc#the-kernel-command-line[页面]上的说明更改控制台设置。

=== 传统的图形驱动程序

NOTE: 这是Raspberry Pi 4 型号 B 之前的型号的默认设置。

使用旧版显示驱动程序时，`config.txt` 有一些轮换选项。

`display_hdmi_rotate` 用于旋转HDMI显示器，`display_hdmi_rotate` 用于旋转任何连接的LCD面板（使用DSI或DPI接口）。这些选项可旋转桌面和控制台。每个选项都采用以下参数之一：

|===
| display_*_rotate | result

| 0
| no rotation

| 1
| rotate 90 degrees clockwise

| 2
| rotate 180 degrees clockwise

| 3
| rotate 270 degrees clockwise

| 0x10000
| horizontal flip

| 0x20000
| vertical flip
|===

请注意，90 度和 270 度旋转选项在 GPU 上需要额外的内存，因此这些选项不适用于 16MB GPU 拆分。

您可以通过将它们添加在一起来将旋转设置与翻转组合在一起。您还可以以相同的方式进行水平和垂直翻转。例如，垂直和水平翻转的 180 度旋转将0x20000 + 0x10000 + 2 = 0x30002。