[[setting-up-a-headless-raspberry-pi]]
== 设置无显示的Raspberry Pi

如果您不使用显示器或键盘来运行 Raspberry Pi（称为headless），但您仍然需要进行一些无线设置，则可以在 xref:getting-started.adoc#installing-the-operating-system[创建映像] 
时启用无线网络和 SSH。
在 SD 卡上创建映像后，通过将其插入 Linux 或 Windows 计算机上的读卡器，可以访问 xref:configuration.adoc#the-boot-folder[boot 文件夹]。将某些文件添加到此文件夹将在Raspberry Pi首次启动时激活某些设置功能。

IMPORTANT: 如果您正在安装 Raspberry Pi OS，并打算headless运行它，则需要创建一个新的用户帐户。由于您将无法使用 xref:getting-started.adoc#configuration-on-first-boot[首次启动向导] 创建用户帐户，因为它需要显示器和键盘，因此您 *必须* 将 `userconf.txt` 文件添加到启动文件夹以在首次启动时创建用户，或使用 Raspberry Pi 成像器中的 xref:getting-started.adoc#advanced-options[高级菜单] 使用用户帐户配置操作系统。

[[configuring-networking-2]]
=== 配置网络

您需要为特定无线网络定义一个 `wpa_supplicant.conf` 文件。将此文件放到 SD 卡的启动文件夹中。当Raspberry Pi首次启动时，它会将该文件复制到 Linux 根文件系统中的正确位置，并使用这些设置启动无线网络。Raspberry Pi的 IP 地址在开机后不会立即可见，因此此步骤对于无头连接它至关重要。根据您创建此文件的操作系统和编辑器，该文件可能具有不正确的换行符或错误的文件扩展名，因此请确保使用说明此问题的编辑器。Linux 需要换行符 （LF） 换行符。

WARNING: Raspberry Pi连接到电源后，请确保等待几分钟（最多 5 分钟）让它启动并在网络上注册。

A xref:configuration.adoc#wireless-networking-command-line[`wpa_supplicant.conf`] 文件示例:

----
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
country=<Insert 2 letter ISO 3166-1 country code here>
update_config=1

network={
 ssid="<Name of your wireless LAN>"
 psk="<Password for your wireless LAN>"
}
----

国家/地区代码应设置为您使用的国家/地区的两个字母的 ISO/IEC alpha2 代码，例如:

* GB (英国)
* FR (法国)
* DE (德国)
* US (美国)
* SE (瑞典)

下面是一个更详细的示例，应该适用于大多数典型的 wpa2 个人网络。下面的模板适用于 2.4GHz/5GHz 隐藏或非网络。在 ssid - psk 周围使用引号可以帮助避免任何奇怪的情况，如果您的网络 ssid 或密码有特殊的字符（！ @ # $ 等）

----
ctrl_interface=DIR=/var/run/wpa_supplicant GROUP=netdev
update_config=1
country=<Insert 2 letter ISO 3166-1 country code here>

network={
        scan_ssid=1
        ssid="<Name of your wireless LAN>"
        psk="<Password for your wireless LAN>"
        proto=RSN
        key_mgmt=WPA-PSK
        pairwise=CCMP
        auth_alg=OPEN
}
----

NOTE: 一些较旧的Raspberry Pi板和一些USB无线加密狗不支持5GHz网络。

NOTE: 在没有键盘或显示器的情况下，您将需要某种 xref:remote-access.adoc[远程访问] 无头Raspberry Pi的方法。对于无头设置，可以通过将一个名为 `ssh` 的文件（没有任何扩展名）放在 SD 卡的启动文件夹中来启用 SSH。有关详细信息，请参阅有关 xref:remote-access.adoc#ssh[设置 SSH 服务器]的部分。


[[configuring-a-user]]
=== 配置用户

您需要在 SD 卡的启动分区中添加一个userconf.txt;这是SD卡的一部分，当它安装在Windows或MacOS计算机中时可以看到。

此文件应包含一行文本，包括 `username:password` 因此，您需要的用户名，紧跟冒号，紧跟您要使用的密码的加密表示形式。

要生成加密密码，最简单的方法是在已经运行的Raspberry Pi上使用 OpenSSL – 打开终端窗口并输入：

----
openssl passwd -6
----

这将提示您输入密码并验证。然后，它将生成看起来像一串随机字符的内容，实际上是所提供密码的加密版本。