[[changing-the-default-pin-configuration]]
== 更改默认引脚配置

WARNING: 此功能适用于高级用户。

截至 2014 年 <7> 月，Raspberry Pi 固件通过用户提供的设备树 blob 文件支持自定义默认引脚配置。要了解您的固件是否足够新，请运行 `vcgencmd version`

[[device-pins-during-boot-sequence]]
=== 启动序列期间的器件引脚

在启动序列期间，GPIO 引脚会经历各种操作

. 上电 -- 引脚默认为具有默认拉动的输入; https://datasheets.raspberrypi.com/bcm2835/bcm2835-peripherals.pdf[数据手册] 中描述了每个引脚的默认状态
. 通过引导进行设置
. 依据 `bootcode.bin`
. 依据 `dt-blob.bin`
. 通过在 xref:config_txt.adoc#gpio-control[GPIO command]  `config.txt` 中设置
. 附加固件引脚 (例如 UARTS)
. 内核/设备树

在软复位时，相同的过程适用，但默认拉取除外，默认拉取仅适用于上电复位。

请注意，从阶段 1 到阶段 4 可能需要几秒钟。在此期间，GPIO 引脚可能未处于连接的外设（如 `dtblob.bin` 或 `config.txt`中所定义）所期望的状态。由于不同的 GPIO 引脚具有不同的默认拉取，因此应为外设执行以下操作之一：


* 选择一个 GPIO 引脚，该引脚默认为复位时外设需要拉取
* 将外设的启动延迟到达到第 4/5 阶段
* 添加适当的上拉/下拉电阻

[[providing-a-custom-device-tree-blob]]
=== 自定义 Device Tree Blob
要将设备树源 （`.dts`） 文件编译为设备树 blob （`.dtb`） 文件，必须通过运行 `sudo apt install device-tree-compiler` 来安装设备树编译器。然后可以按如下方式使用该 `dtc` 命令：

----
sudo dtc -I dts -O dtb -o /boot/dt-blob.bin dt-blob.dts
----

同样，如果需要，可以将 `.dtb` 文件转换回文件 `.dts`。

----
dtc -I dtb -O dts -o dt-blob.dts /boot/dt-blob.bin
----

[[sections-of-the-dt-blob]]
=== `dt-blob` 章节

`dt-blob.bin` 用于在启动时配置二进制 blob （视频核心）。Linux 内核目前没有使用它，但稍后我们将重新配置 Raspberry Pi 内核以使用 dt-blob 进行配置时，将添加一个内核部分。`dt-blob` 可以配置所有版本的Raspberry Pi，包括计算模块，以使用替代设置。以下部分在 dt-blob 中有效：

. `videocore`
+
本部分包含所有视频核心 blob 信息。所有后续部分必须包含在此部分中。

. `pins_*`
+
有许多单独的 `pins_*` 部分，基于特定的Raspberry Pi模型，即：

* *pins_rev1* Rev1 pin setup. 由于移动了I2C引脚，因此存在一些差异。
* *pins_rev2* Rev2 pin setup. 这包括 P5 上的附加编解码器引脚。
* *pins_bplus1* Raspberry Pi 1 Model B+ rev 1.1, 包括完整的 40 针连接器。
* *pins_bplus2* Raspberry Pi 1 Model B+ rev 1.2, 交换低功耗和局域网运行引脚。
* *pins_aplus* Raspberry Pi 1 Model A+, 缺少以太网。
* *pins_2b1* Raspberry Pi 2 Model B rev 1.0; 通过 I2C0 控制 SMPS。
* *pins_2b2* Raspberry Pi 2 Model B rev 1.1; 通过软件 I2C 控制 42 和 43 上的 SMPS。
* *pins_3b1* Raspberry Pi 3 Model B rev 1.0
* *pins_3b2* Raspberry Pi 3 Model B rev 1.2
* *pins_3bplus* Raspberry Pi 3 Model B+
* *pins_3aplus* Raspberry Pi 3 Model A+
* *pins_pi0* Raspberry Pi Zero
* *pins_pi0w* Raspberry Pi Zero W
* *pins_cm* Raspberry Pi Compute Module 1. 默认值是芯片的默认值，因此它是有关芯片上默认上拉/下拉的有用信息来源。
* *pins_cm3* Raspberry Pi Compute Module 3
+
Each `pins_*` section can contain `pin_config` and `pin_defines` sections.

. `pin_config`
+
该 `pin_config` 部分用于配置各个引脚。此部分中的每个项目都必须是命名引脚部分，例如 `pin@p32` ，表示 GPIO32。有一个特殊的部分 `pin@default`，其中包含pin_config部分中未明确命名的任何内容的默认设置。
. `pin@pinname`
+
此部分可以包含以下项的任意组合：

 .. `polarity`
  *** `active_high`
  *** `active_low`
 .. `termination`
  *** `pull_up`
  *** `pull_down`
  *** `no_pulling`
 .. `startup_state`
  *** `active`
  *** `inactive`
 .. `function`
  *** `input`
  *** `output`
  *** `sdcard`
  *** `i2c0`
  *** `i2c1`
  *** `spi`
  *** `spi1`
  *** `spi2`
  *** `smi`
  *** `dpi`
  *** `pcm`
  *** `pwm`
  *** `uart0`
  *** `uart1`
  *** `gp_clk`
  *** `emmc`
  *** `arm_jtag`
 .. `drive_strength_mA`
驱动强度用于设置引脚的强度。请注意，您只能为引脚指定单个驱动器强度。<8> 和 <16> 是有效值。

. `pin_defines`
+
此部分用于将特定的视频核心功能设置为特定引脚。这使用户能够将相机电源使能引脚移动到其他位置，或移动HDMI热插拔位置：Linux无法控制的事情。请参考下面的 DTS 文件示例。

[[clock-configuration]]
=== 时钟配置

可以通过此接口更改时钟的配置，尽管很难预测结果！时钟系统的配置非常复杂。有五个独立的PLL，每个PLL都有自己的固定（或可变，在PLLC的情况下）VCO频率。然后，每个VCO都有许多不同的通道，可以使用不同的VCO频率划分来设置这些通道。每个时钟目标都可以配置为来自其中一个时钟通道，尽管源到目标的映射有限，因此
并非所有通道都可以路由到所有时钟目标。

以下是可用于更改特定时钟的几个示例配置。当提出时钟配置请求时，我们将添加到此资源中。

----
clock_routing {
   vco@PLLA  {    freq = <1966080000>; };
   chan@APER {    div  = <4>; };
   clock@GPCLK0 { pll = "PLLA"; chan = "APER"; };
};

clock_setup {
   clock@PWM { freq = <2400000>; };
   clock@GPCLK0 { freq = <12288000>; };
   clock@GPCLK1 { freq = <25000000>; };
};
----

上述内容会将 PLLA 设置为运行在 1.96608GHz 的源 VCO（此 VCO 的限制为 600MHz - 2.4GHz），将 APER 信道更改为 /4，并将 GPCLK0 配置为通过 APER 从 PLLA 源。这用于为音频编解码器提供产生 12288000 频率范围所需的 48000Hz。

[[sample-device-tree-source-file]]
=== 示例设备树源文件

示例文件来自固件存储库 https://github.com/raspberrypi/firmware/blob/master/extra/dt-blob.dts. 这是主Raspberry Pi blob，其他文件通常是从它派生的。

